### ISSUE TITLE
What is `scid` for?

### ISSUE THREAD

**Issue by djKooks** [cloudflare/quiche#1007]
This is not an issue, just a question for implementation.
Currently I'm trying to make some simple server/client app for study, but bit blocked on defining `scid`.

```
// Client connection.
let conn = quiche::connect(Some(&server_name), &scid, to, &mut config)?;

// Server connection.
let conn = quiche::accept(&scid, None, from, &mut config)?;
```

- How should I define `scid`?
- Is this should be same for defining client/server?
- Also, will it be okay to think `server_name` and `from` as "host address" in usual server/client app?

(hope there are some discord/gitter channel, for simple QnA...)

**Comment by LPardue** [comment]
For SCID see https://www.rfc-editor.org/rfc/rfc9000.html#section-5.1. Each end picks one, the peer uses that value as the DCID in packets it sends. Picking a value is a deployment choice that needs to follow guidance in the RFC.

`server_name` is used for client-side cert validation . `from` is used by the server, its the client's socket object.
