### ISSUE TITLE
Need some help on our research project

### ISSUE THREAD

**Issue by caroljun** [cloudflare/quiche#1021]
Hi, this is Carol Fung, associate professor at Virginia Commonwealth University. I am currently working on a research project with my student to test the resistance of QUIC protocol against DDoS attacks. We were trying to use your code for experiment and found we had trouble running it. Could anyone give a hand? To show our appreciation, we can add an acknowledgement or add you as a co-author when the paper is published. Thanks much.

**Comment by LPardue** [comment]
Hello. Is this related to #1015 ? Is so let's focus the conversation there and see if we can get you going. If there's anything you'd like to share with more confidentiality than GitHub feel free to email me lucas [at] cloudflare . com

**Comment by caroljun** [comment]
Yes. #1015 was sent by my student. We will appreciate much if you can help us out.

**Comment by LPardue** [comment]
closing this one, let's continue on #1015 if needed

**Comment by caroljun** [comment]
Sure. We still need help with the project.
My student should email you soon.

Carol
