### ISSUE TITLE
8 core cpu, nginx process  only use one  cpu 100%.

### ISSUE THREAD

**Issue by Songdantes** [cloudflare/quiche#1022]
nginx version: nginx-1.16.1 or  nginx-1.18 
quiche version:  v0.9.0(https://github.com/cloudflare/quiche/tree/0.9.0)
when I patch quiche to nginx，the cpu can’t run  balanced. The vesion of nginx-1.16.1 and  nginx-1.18 both have this problem.
![POPO20210802-105805](https://user-images.githubusercontent.com/12936628/127836772-edd55740-60a1-4ee7-a11f-7111d3579333.png)

**Comment by junhochoi** [comment]
How does your test look like?

**Comment by Songdantes** [comment]
Page view 20million per day，page view greater than 100 per second. After a period of normal operation , only one cpu used 100%.
-------------------------------------------
config  file like below

server {
    listen 443 ssl http2 default_server reuseport;
    listen 443 quic reuseport;
    server_name  xxx;
    access_log  xxx  main;
 
    ssl_certificate /etc/nginx/xxx.pem;
    ssl_certificate_key /etc/nginx/xxx.key;
    ssl_session_timeout 1d;
    ssl_session_cache shared:MozSSL:10m;
   
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers off;
    
    ssl_stapling on;
    ssl_stapling_verify on;

    add_header alt-svc 'h3-29=":443";ma=86400,h3-27=":443";ma=86400';
}

**Comment by Songdantes** [comment]
I used perl made a flame diagram ,  found lots of  function "quiche::stream::StreamMap::get"  
![1627995482115](https://user-images.githubusercontent.com/12936628/128020032-2689bd09-a6f0-4db8-8879-78f9d8e8645d.jpg)
![1627994209864](https://user-images.githubusercontent.com/12936628/128020050-d227e237-76e9-409c-bf29-17e4482e985d.jpg)

**Comment by junhochoi** [comment]
So this is not a synthetic test but a real end user traffic? How is your other parts of nginx.conf, especially regarding worker process? Also, do you see 100% cpu while no traffic? I'm curious to see if this is a worker unbalancing issue or just a quiche bug which can make 100% cpu.

**Comment by Songdantes** [comment]
It is a real end user traffic.when I use nginx without a patch of quic ,all of the cpu are balanced , no cpu used 100%.



---Original---
From: "Junho ***@***.***&gt;
Date: Tue, Aug 3, 2021 23:40 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [cloudflare/quiche] 8 core cpu, nginx process  only use one  cpu 100%. (#1022)




 
So this is not a synthetic test but a real end user traffic? How is your other parts of nginx.conf, especially regarding worker process? Also, do you see 100% cpu while no traffic? I'm curious to see if this is a worker unbalancing issue or just a quiche bug which can make 100% cpu.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by junhochoi** [comment]
Can you try latest quiche and its nginx patch? I'm curious if this is fixed by https://github.com/cloudflare/quiche/commit/28c0288cd55e7c986e88aeb922d65283b1e17852

**Comment by Songdantes** [comment]
thx.I will have a try.

**Comment by Songdantes** [comment]
Based on the  latest master branch made a patch , It has been running normally for one day,  I think this problem has beed resoved, thanks.

**Comment by junhochoi** [comment]
Great to hear! Thanks
