### ISSUE TITLE
Determining why a connection is closed / expose local_error

### ISSUE THREAD

**Issue by kevinjohna6** [cloudflare/quiche#1023]
On a quic server, while garbage collecting connections, I would like to determine why the connection closed.
Most of this was made possible by exposing `peer_error`, but I am not sure how to differentiate between a client timeout or a `CONNECTION_CLOSE` sent by the server, without maintaining state external to quiche.

As a possible solution, I have dealt with this by exposing `local_error` (fc17d0a), and checking both peer_error and local_error to determine the reason for close.

**Comment by LPardue** [comment]
Hi!

Exposing the `local_error` seems reasonable to me, especially because quiche will internally close connections when the protocol is violated. Having that information available to the app is useful for audit purposes.
