### ISSUE TITLE
Any plan to support priority in nginx?

### ISSUE THREAD

**Issue by weiwei99** [cloudflare/quiche#1035]
Current nginx patch does not support priority, do you have any plan to support http3 priority in nginx?

**Comment by LPardue** [comment]
This is something we'd like to do but needs to be managed against other the needs of other work. So there is currently no ETA.

**Comment by weiwei99** [comment]
Any guide for the implementation?

**Comment by LPardue** [comment]
The quiche code has been validated in the past using quiche example apps, so as far as I know it should work. Detailed test cases are needed to understand if there is something that is not behaving as expected.

**Comment by LPardue** [comment]
This is completed as of 0.18. Setting different priorities for streams is left as a job for the specific application.
