### ISSUE TITLE
ubuntu1604  build nginx fail

### ISSUE THREAD

**Issue by luojieio** [cloudflare/quiche#1041]
objs/src/http/modules/ngx_http_upstream_least_conn_module.o \
objs/src/http/modules/ngx_http_upstream_random_module.o \
objs/src/http/modules/ngx_http_upstream_keepalive_module.o \
objs/src/http/modules/ngx_http_upstream_zone_module.o \
objs/ngx_modules.o \
-ldl -lpthread -lcrypt -lpcre ../quiche/deps/boringssl/.openssl/lib/libssl.a ../quiche/deps/boringssl/.openssl/lib/libcrypto.a -ldl -lpthread ../quiche/target/release/libquiche.a -lpthread -lz \
-Wl,-E
../quiche/target/release/libquiche.a(std-008055cc7d873802.std.cf1c8f7e-cgu.0.rcgu.o): In function `std::f32::_$LT$impl$u20$f32$GT$::lerp::h6395a3c9e15adad4':
/rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b//library/std/src/f32.rs:914: undefined reference to `fmaf'
../quiche/target/release/libquiche.a(std-008055cc7d873802.std.cf1c8f7e-cgu.0.rcgu.o): In function `std::f64::_$LT$impl$u20$f64$GT$::lerp::h20746ba37427db50':
/rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b//library/std/src/f64.rs:916: undefined reference to `fma'
collect2: error: ld returned 1 exit status
objs/Makefile:260: recipe for target 'objs/nginx' failed
make[1]: *** [objs/nginx] Error 1
make[1]: Leaving directory '/data/nginx-1.16.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
root@043b2fd662fa:/data/nginx-1.16.1#

**Comment by luojieio** [comment]
root@043b2fd662fa:/data/nginx-1.16.1# cargo -V
cargo 1.55.0 (32da73ab1 2021-08-23)

root@043b2fd662fa:/data/nginx-1.16.1# rustc -V
rustc 1.55.0 (c8dfcfe04 2021-09-06)

**Comment by junhochoi** [comment]
Can you try #1042 ?

**Comment by luojieio** [comment]
wow,thank you vevry much, it's ok
