### ISSUE TITLE
ECN remarking can kill a connection

### ISSUE THREAD

**Issue by WesleyRosenblum** [cloudflare/quiche#1051]
Since quiche [cannot process](https://github.com/cloudflare/quiche/blob/master/src/frame.rs#L187-L189) ACK ECN frames (type 0x03), this means that a peer that transmits these frames to a quiche endpoint will have their acknowledgements dropped. Since quiche does not mark packets as ECN capable, it wouldn't be expected for a peer to send the ACK ECN frame, so this is normally not an issue. However, it is possible for middleboxes to remark IP packets to ECT0 or ECT1 (see[ QUIC Transport §13.4.2.1 ](https://www.rfc-editor.org/rfc/rfc9000.html#section-13.4.2.1).) If this happens, an ECN capable peer may start sending ACK ECN frames, which quiche will drop. Since there is no mechanism that clears or resets ECN counts, these ACK ECN frames may continue to be transmitted until the connection is eventually terminated. To remedy this, quiche could process the ACK ECN frames as a regular ACK frame by stripping the ECN Counts, instead of dropping the whole packet.

Thanks for considering this issue and let me know if you need any further information!

**Comment by LPardue** [comment]
Thanks for filing an issue @WesleyRosenblum, I made a PR that should let us handle reception of 0x03 frames more gracefully.
