### ISSUE TITLE
Cannot open include file: 'sys/socket.h':  

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#1061]
[INFO]   D:\a\netty-incubator-codec-quic\netty-incubator-codec-quic\target\quiche\include\quiche.h(37): fatal error C1083: Cannot open include file: 'sys/socket.h': No such file or directory [D:\a\netty-incubator-codec-quic\netty-incubator-codec-quic\target\native-build\vs2010.vcxproj]

**Comment by yaraPB** [comment]
You could open it with the WSL (like the Ubuntu one)
