### ISSUE TITLE
Where is the Dockerfile for examples?

### ISSUE THREAD

**Issue by duskmoon314** [cloudflare/quiche#1076]
Hi, I'm new to quiche and want to learn by running examples. But there isn't any Dockerfile in the examples folder. It seems that it has been moved from examples/Dockerfile to extras/docker/, but there isn't an extras folder now. So I wonder where can I find the Dockerfile?

I think it might be friendly to provide Dockerfile and docker-compose.yml to show how to set up an environment and use quiche.

**Comment by FrangaL** [comment]
https://github.com/FrangaL/docker-nginx-http3/blob/master/Dockerfile

**Comment by LPardue** [comment]
Currently https://github.com/cloudflare/quiche/blob/master/Dockerfile.

For more complicated setups using Docker compose, I suggest using the excellent QUIC Interop Runner https://github.com/marten-seemann/quic-interop-runner
