### ISSUE TITLE
ffi: Should quiche_conn_new_with_tls be exported?

### ISSUE THREAD

**Issue by nqv** [cloudflare/quiche#108]
Commit https://github.com/cloudflare/quiche/commit/2c56f3ab454b330a2a01dfcb6ba4893b5ce50319 unexported Connection::with_tls.
I'm wondering if we should remove the function `quiche_conn_new_with_tls` as well

**Comment by ghedo** [comment]
We use `quiche_conn_new_with_tls()` in our internal codebase, so we can't unexport it.

The reason why the Rust function was unexported was that the `Handshake` type is not public, so there's no way to use that function from outside of the crate anyway, but in the future we may export it again if we can figure out a nice API for it.

One idea is to move the BoringSSL FFI code to a separate crate, so it can be used on its own (this way we could also reduce the API surface we expose, e.g. in `Config` to configure TLS-related things), but that's not very high priority right now.
