### ISSUE TITLE
stream_send returns Ok(0) with non-zero buffer lengths

### ISSUE THREAD

**Issue by francoismichel** [cloudflare/quiche#1095]
Hello,

I am using the API through the C bindings and use a large number of concurrent streams. Some of them contain only a few hundreds of bytes before indicating the FIN bit.

Here is a part of the specification of stream_send:

   
    ...
    /// Applications can provide a 0-length buffer with the fin flag set to
    /// true. This will lead to a 0-length FIN STREAM frame being sent at the
    /// latest offset. This is the only case where `Ok(0)` is returned.
    ...
    pub fn stream_send(
        &mut self, stream_id: u64, buf: &[u8], fin: bool,
    ) -> Result<usize>

On a congested environment where the congestion window is full, we can have configurations where send_stream() returns Ok(0) even if the length of `buf` is nonzero but `fin` set to `true`.

Take a look at the implementation of `stream_send()` below : 

        ...
        // Truncate the input buffer based on the connection's send capacity if
        // necessary.
        let cap = self.tx_cap;
        if cap == 0 && !fin {
            return Err(Error::Done);
        }

        let (buf, fin) = if cap < buf.len() {
            (&buf[..cap], false)
        } else {
            (buf, fin)
        };
        ...

If we are congested, `tx_cap` will be 0. If the buffer does not have a zero length but `fin` is set to `true`, `stream_send` won't return `Err(Error::Done)` as it won't enter the if, but will return `Ok(0)` instead. A fix would be to either update the specification or update the if like the following:

        if cap == 0 && (!fin || buf.len() > 0)) {
            return Err(Error::Done);
        }

There is **another** codepath where `stream_send` could return `Ok(0)`: when the connection-level flow control allows sending more data but the stream-level flow control does not allow such sending, `stream.send.write` will be called. Then, the `write()` method of the stream's `SendBuf` will return `Ok(0)`. This can also be avoided by making the `cap()` method of the Stream's `SendBuf` return `Err(Error::Done)` when the capacity is 0 or making the `write()` method of the `SendBuf` return the error when the capacity is 0. 

Do you think the spec needs to be update or do we need to update the code ?

Regards

**Comment by ghedo** [comment]
I think we should fix the code here, thanks for investigating. Would you mind providing a PR?

**Comment by francoismichel** [comment]
Sure, no problem

**Comment by francoismichel** [comment]
Hi, fixing the test suite upon the change was finally easier than expected. The code change is this available in PR #1099.
Feel free to request changes if needed.
