### ISSUE TITLE
Documentation for the C Wrapper

### ISSUE THREAD

**Issue by marcfielding1** [cloudflare/quiche#1097]
Heya,

Is there a guide or documentation around the methods used in the C wrapper please, sorry If I've missed them?

Thanks

Marc

**Comment by LPardue** [comment]
There's not really much in the way of C API documentation unfortunately. The C API is pretty close to the rust API, which is documented at https://docs.quic.tech/quiche/#structs

quiche_config_* -> https://docs.quic.tech/quiche/struct.Config.html
quiche_conn_* -> https://docs.quic.tech/quiche/struct.Connection.html
etc.

**Comment by LPardue** [comment]
Closing since the immediate question was answered. While it might be nice to improve the C docs, the Rust docs are a lot more ergonomic to maintain and read, and port over ok.
