### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by Alexendoo** [cloudflare/quiche#11]
Would be a nice to consume it through cargo install. Either way it's worth reserving the quiche name while it's available for future use

**Comment by ghedo** [comment]
Just uploaded the first alpha version https://crates.io/crates/quiche :tada: 

Looks like we'll need to port the README to markdown to get the nice rendering though :/

**Comment by ghedo** [comment]
Redid the README now, so it will be included in the next upload.
