### ISSUE TITLE
Question about server example

### ISSUE THREAD

**Issue by Jonas-Heinrich** [cloudflare/quiche#1102]
Hi,

I was wondering why the example server `ClientMap` is used as a mapping of both `conn_id` and `hdr.dcid` to clients. [For example](https://github.com/cloudflare/quiche/blob/2649457a566e320bbb4edc74d5a26fd8f6a22547/examples/server.rs#L178:L179) in the check if the connection already exists:

```rust
// [...]
let client = if !clients.contains_key(&hdr.dcid) &&
    !clients.contains_key(&conn_id)
// [...]
```

However, as far as I understand the `if` branch, only `hdr.dcid` is ever inserted:

https://github.com/cloudflare/quiche/blob/2649457a566e320bbb4edc74d5a26fd8f6a22547/examples/server.rs#L272

where `scid` is 

https://github.com/cloudflare/quiche/blob/2649457a566e320bbb4edc74d5a26fd8f6a22547/examples/server.rs#L259

If the `conn_id` lookup could be dropped, its calculation could also be moved into the `if` branch. I suppose this could improve performance.

I am aware that this changed in the new examples (`apps/src/bin/quiche-server.rs`), however I do not get why the distinction is necessary there either.

Thanks,
Jonas

**Comment by LPardue** [comment]
The original context for this design is https://github.com/cloudflare/quiche/commit/06c0d497a4e08da31e8d3684a7bcf03cca38448d#diff-c590b3c924c35c2f241746522284e4709df490d73a38aaa7d6de4ed1eac2f546

**Comment by Jonas-Heinrich** [comment]
@LPardue
That clarifies it, thank you!
