### ISSUE TITLE
How to test partial request feature on client side

### ISSUE THREAD

**Issue by psionic12** [cloudflare/quiche#1107]
I got some rare error online report that my lib got small size returned then the body when using `send_request`, I read the doc and it suggest to retry later when connection is writable, so I decide to implement the partial request feature.

I follow the code in examples (though it is partial response, but I think both request and response can be partially sending, right?), and write my own codes.

The problem is that I don't know how I can test this, I tried in my test environment with really large request body, but quiche can just send in one piece, I tried some config settings in quiche.h, but seems not helping.

So is there anyway I can force quiche to have really small buffer, so my request body won't send at once?

**Comment by LPardue** [comment]
You'll typically be able to send a congestion control window worth of data each iteration. The easiest way to test client side partial writes is to configure quiche-server with small flow control window using --max-stream-data. A value of 8000 is probably small enough to block client writes without the congestion window playing a part.

**Comment by psionic12** [comment]
@LPardue thanks for helping, I'll try.

**Comment by psionic12** [comment]
@LPardue I found three configs which has relations to --max-stream-data:
```
    config.set_initial_max_stream_data_bidi_local(1_000_000);
    config.set_initial_max_stream_data_bidi_remote(1_000_000);
    config.set_initial_max_stream_data_uni(1_000_000);
```

Do you main modify these on the http3-server.rs? I'm not sure what is the quiche-server you mentioned, and didn't find command line parameter "--max-stream-data" either...
