### ISSUE TITLE
Building quiche under Windows MSYS2 targeting x86_64-pc-windows-gnu failed

### ISSUE THREAD

**Issue by NetherDevil** [cloudflare/quiche#1136]
I used command `cargo.exe build --package quiche --release --features ffi,pkg-config-meta,qlog` to build it. At first the process went on smoothly, but it failed when compiling quiche v0.10.0:
```
# cargo build --package quiche --release --features ffi,pkg-config-meta,qlog
   Compiling quiche v0.10.0 (D:\quiche\quiche)
error: could not find native static library `crypto`, perhaps an -L flag is missing?

error: could not compile `quiche` due to previous error
```
I used `git clone --recursive https://github.com/cloudflare/quiche` to clone the repository. While compiling BoringSSL, it threw some errors like `undefined symbol: pthread_rwlock_init`, so I added `-lpthread` in `CMAKE_CXX_FLAGS` and `CMAKE_C_FLAGS` in the file `CMakeList.txt` of BoringSSL, and it was successfully built after that. I am not sure if it is the reason why the build process failed.

Btw, I noticed that the BoringSSL binary `bssl.exe` and its static library `libcrypto.a` was generated in directory `D:\quiche\target\release\build\quiche-<RANDOM STRING>\out\build`. not `D:\quiche\quiche\deps\boringssl\build`. Is it normal behavior?

**Comment by junhochoi** [comment]
We have a CI for `x86_64-pc-windows-msvc`, `i686-pc-windows-msvc` platform but not `x86_64-pc-windows-gnu`. https://github.com/cloudflare/quiche/blob/master/quiche/src/build.rs#L29 has some windows support but probably not msys2 (I never tried)

**Comment by NetherDevil** [comment]
Successfully built with MSVC. Thanks.

~~The MSVC compiler is sooooo big~~
