### ISSUE TITLE
no-std support

### ISSUE THREAD

**Issue by nico-abram** [cloudflare/quiche#115]

**Comment by ghedo** [comment]
I don't think this is possible. We rely on several std APIs (e.g. collections).

**Comment by nico-abram** [comment]
I know some collections are now in the alloc crate (Which is available in no-std enviroments that provide an allocator) like Vec and Box. Not sure if everything that would be needed is available though

**Comment by ghedo** [comment]
@nico-abram Yeah, but e.g. we need `HashMap` which AFAICT it's not in `alloc`.
