### ISSUE TITLE
Why cant webtransport trigger http3 data event?

### ISSUE THREAD

**Issue by kalradivyanshu** [cloudflare/quiche#1150]
I changed the headers in accordance to https://github.com/cloudflare/quiche/issues/1132#issuecomment-1018293465 and the connection got established in https://googlechrome.github.io/samples/webtransport/client.html. But when I send a bidirectional stream, the event `quiche::h3::Event::Data` is not triggered. I think the bidirectional frame has this format: https://www.ietf.org/id/draft-ietf-webtrans-http3-02.html#name-bidirectional-streams. Any help would be appreciated.

**Comment by LPardue** [comment]
WebTransport changes the semantics of an HTTP/3 connection. That requires changes into quiche's h3 library to support branching between operating as a conventional HTTP/3 endpoint OR a WebTransport over HTTP/3 endpoint. 

For instance, sending DATA frames as the first frame on new bidirectional streams is not permitted by the  HTTP/3 specification; see https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-4.1. quiche enforces this rule; you won't see a `quiche::h3::Event::Data` in that circumstance.

But WebTransport over HTTP/3 doesn't use DATA frames. https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02#section-4.2 sayes 

> WebTransport endpoints can initiate bidirectional streams by opening
   an HTTP/3 bidirectional stream and sending an HTTP/3 frame with type
   WEBTRANSPORT_STREAM (type=0x41).  The format of the frame SHALL be
   the frame type, followed by the session ID, encoded as a variable-
   length integer, followed by the user-specified stream data
   (Figure 2).  The frame SHALL last until the end of the stream.

As per HTTP/3, quiche ignores unknown frame types. To support Webtransport, quiche needs additional code for frame parsing and other stream-state handlers. There's no quick win here. quiche needs to be modified to support a semantic extension and it needs to apply the rules of each specification appropriately in all circumstances and variants concurrently.

**Comment by kalradivyanshu** [comment]
Thanks for the reply :) I was able to edit the frametype, and get a bidirectional stream connected and got the data. I am trying to build a simple echo server (get data on the bidirectional stream, and send the same data back on the same stream) to send data back on the bidirectional stream, should I use the underlying quiche's `stream_send()` method, or the `h3.send_body`. I am able to send some data with `stream_send()` but sometimes it throws `Error::done`, but `h3.send_body` throws `stream: FrameUnexpected`, is this because of the same issue as recieving? Does this mean, I need to alter `h3.send_body` also, rather than using the underlying `stream_send()`?

**Comment by LPardue** [comment]
If you're tying to send on bidirectional streams, quiche's HTTP/3 layer will also enforce the rules I mentioned above. It sounds like you're hitting that with the FrameUnexpected error on send_body()

It is possible to call stream_send() directly. However, as a long term solution this poses some problems because of the possibility of things becoming desynchronized. As a workaround for experimentation it should work. You should expect Error::Done to be returned when the stream doesn't have enough capacity, this is normal due to flow control or congestion control https://docs.quic.tech/quiche/struct.Connection.html#method.stream_send. The app will need to pause stream writes, flush packets, and enter the read loop to process packets that might grant more credits.

**Comment by kalradivyanshu** [comment]
Got it, thanks. Is there a document on how to prevent/handle the `Error::Done` issue?

**Comment by kalradivyanshu** [comment]
Ok, so I was able to make `send_body()` work, the problem was I hadnt initialized the local part of the stream, so this condition was being hit:
(https://github.com/cloudflare/quiche/blob/master/quiche/src/h3/mod.rs#L1000)
```
if !s.local_initialized() {
    return Err(Error::FrameUnexpected);
}
```

However I am receiving some extra bytes in the webtransport chrome example. If I send `[u8]` containing `[119, 119, 119]` I receive in chrome `[0, 3, 119, 119, 119]`. I suspect it is some extra data that quiche is sending that is required by the http3 protocol, but webtransport is perhaps parsing it as payload data.

Why would this be happening? Any insights into whats going on?

**Comment by LPardue** [comment]
WebTransport streams are not HTTP/3 requests or response. WebTransport rewrites the rules for bidirection streams, see https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02#section-4.2, and quiche's HTTP/3 layer does not support other things redefining the rules. So fighting against quiche is not going to be a path to fulfillment.  

> I suspect it is some extra data that quiche is sending that is required by the http3 protocol, but webtransport is perhaps parsing it as payload data.

Yes, this is the DATA frame, which is how request and response body is sent - https://datatracker.ietf.org/doc/html/draft-ietf-quic-http-34#section-7.2.1

If you just want to experiment, the is would sufice to service the Extended CONNECT request for [session establishment](https://datatracker.ietf.org/doc/html/draft-ietf-webtrans-http3-02#section-3.2) and then start using quiche's stream_send()/stream_recv() directly. This is, however, not a very sustainable long-term solution. Instead, quiche's h3 layer should be modified as I already mentioned.

**Comment by kalradivyanshu** [comment]
makes a lot of sense. I have modified the h3 layer only and the data being sent is what is being received back, so thank you for your help :) 

The new problem now is that if I send data from the webtransport client at a rate higher than 2 megabits per second, some of the data never makes it to my quiche app. I suspect that congesion control is playing a role there, and will be probing the new reno congestion algorithm in quiche. 

But other than that, so far it seems to be working. Thanks 🥧.

**Comment by LPardue** [comment]
The congestion control and flow control aspect should be common no matter what happens at the application. You'll have some capacity to send with, and stream_send() will consume it. The only way to get more is to send and receive packets to/from the peer. If you get the sequence right, then it's possible to get use most of the available network capacity. Once in the 10 gigabit/s other factors start to come into play.

**Comment by LPardue** [comment]
quiche doesn't formally support WebTransport. The interaction between HTTP/3 and WebTransport is a known constraint that applies to any form of HTTP/3 semantic extension. So I don't see this as any specific issue with quiche. It seems like you've been able to work around these constraints, which should allow experimentation. Therefore I'm going to close this issue.

If there are quiche-specific issues that you identify beyond these known constraints, feel free to open a new, separate issue.

**Comment by endel** [comment]
Hi @kalradivyanshu, nice to see you experimenting with WebTransport here! Do you keep a public fork with your modifications for WebTransport? I'm interested in checking this out, too! Cheers

**Comment by kalradivyanshu** [comment]
Hey, unfortunately the code is part of a NDA I have signed. However if you have questions, I can answer them. Do note, I havent implemented webtransport 100% yet, I am still struggling with throughput. Cheers.

**Comment by kalradivyanshu** [comment]
Hey @LPardue I am now able to handle flow control much better. Thanks for the advice there. However I am still struggling to get the bitrate to go above 10 mbps (for one connection), (I am not hitting Done error or congestion, and the server bandwidth is about 4 - 8 gbps), my current hypothesis is that it is because of I am using the default rust [std::net::UdpSocket](https://doc.rust-lang.org/std/net/struct.UdpSocket.html) I came across this blog: https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/ but couldn't find any library that implemented UDP GSO for rust, except for one, which has been abandoned. Is my hypothesis correct? Or am I looking in the wrong direction? I am using tokio for my event loop, and running the server on a single core, and the client on a separate  core.

Any help is appreciated, thanks :)

**Comment by LPardue** [comment]
You should definitely be able to get over 10 mbps even without GSO. You'd need to look into the debug and/or qlogs to figure out what's really happening here.

**Comment by kalradivyanshu** [comment]
Oh okay I will do that. At what point will I start hitting the limit with [std::net::UdpSocket](https://doc.rust-lang.org/std/net/struct.UdpSocket.html)? Can I push it to 1 gbps?

**Comment by LPardue** [comment]
There's a load of potential factors at play, the best bet is to benchmark UDP perf with iPerf (beware caveats  so read up on those) and use that as your baseline for QUIC perf.

As per the blog, you can modify socket behaviour with cmsg. So using something like nix crate will give access to more options configuring socket. For example see https://github.com/cloudflare/quiche/pull/1138
