### ISSUE TITLE
nginx build instructions may need revisiting

### ISSUE THREAD

**Issue by c-taylor** [cloudflare/quiche#1153]
I tried a build today from `main/0.11.0`.

Using the current instructions (I note some path changes) cargo fails to find libssl.so.1.1
```
[100%] Built target bssl
make[3]: Leaving directory '/var/tmp/nginx-quiche/quiche/deps/boringssl/build'
/usr/bin/cmake3 -E cmake_progress_start /var/tmp/nginx-quiche/quiche/deps/boringssl/build/CMakeFiles 0
make[2]: Leaving directory '/var/tmp/nginx-quiche/quiche/deps/boringssl/build'
cd ../quiche && cargo build --verbose --no-default-features --features ffi --release 
cargo: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
make[1]: *** [objs/Makefile:1361: ../quiche/target/release/libquiche.a] Error 127
make[1]: Leaving directory '/var/tmp/nginx-quiche/nginx-1.18.0'
make: *** [Makefile:8: build] Error 2
```

I have done some light troubleshooting, cloning an old branch of quiche that I have previously built/used but the problem persists...

My suspicion is that the boringssl repo pulled in has changed...

**Comment by c-taylor** [comment]
Tracing cargo, I can neither see it looking in the build paths, nor for the .a file

**Comment by ghedo** [comment]
I think your cargo/rust installation might be broken somehow. Does running cargo outside of quiche work?

You could also try installing rust from scratch using rustup https://rustup.rs/.

**Comment by c-taylor** [comment]
Thanks for the prompt reply...

It looks like that is exactly it: I had tried 2x versions (one too old for the features)...
Will review the environment...

Hitting an undefined ref for ring now, but this can probably close...
