### ISSUE TITLE
Possible usecases for MaybeUninit?

### ISSUE THREAD

**Issue by nico-abram** [cloudflare/quiche#116]
This commit (https://github.com/cloudflare/quiche/commit/f454accefa77b6ac51362e65cce0f7b35a196512) replaced 2 usages of the now deprecated std::mem::uninitialized() with zero initialized arrays. I think it might be worth investigating if it might be worth it to use MaybeUninit where those where used.

**Comment by ghedo** [comment]
Note that https://github.com/cloudflare/quiche/pull/117 removes one of those. The other one is not that critical, so the added complexity might not be worth it.

**Comment by ghedo** [comment]
Closing since it's unlikely we'll do this (though would be open to PRs I guess), as there's only one place where MaybeUninit might be useful, and I think the benefits would not outweight the added complexity.
