### ISSUE TITLE
Qlog/Sqlog not generated

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#1165]
The environment variable QLOGDIR is specified before starting the server and client to generate the qlogs, 
export QLOGDIR="Location in which the qlogs are generated"

**SERVER:**
I start the quiche server (qlogs are not generated) by using,

```
sudo cargo run --manifest-path=Cargo.toml --bin quiche-server -- --cert /etc/letsencrypt/fullchain.pem --key /etc/letsencrypt/privkey.pem --listen 132.177.11.138:4433 --root /export/home/html
```

While analyzing the quice-server, when the environment variable is specified by the user qlogs should be generated.

```
 // Only bother with qlog if the user specified it.
               # [cfg(feature = "qlog")]
                {
                if let Some(dir) = std::env::var_os("QLOGDIR") {
                    let id = format!("{:?}", &scid);
                    let writer = make_qlog_writer(&dir, "server", &id);

                     conn.set_qlog(
                        std::boxed::Box::new(writer),
                        "quiche-server qlog".to_string(),
                        format!("{} id={}", "quiche-server qlog", id),
                    );
                }
                }
```

**CLIENT:** 
When I render the html file through the browser, qlogs are not generated

```
./Google\ Chrome\ Canary \
  --enable-quic \
  --quic-version=h3-29 \
  --origin-to-force-quic-on=132.177.11.138:4433 \
 https://132.177.11.138:4433
```

But qlogs are generated on the quiche client (client-453deeaef262ea96942d752d501ec2d670eb38c3.sqlog), the command used is

```
cargo run --manifest-path=Cargo.toml --bin quiche-client -- https://132.177.11.138:4433 --no-verify 
```

I have done several experiments with an older version of quiche and qlogs were generated at each run. But after I installed the newer version (current version) of quiche qlogs are not generated. 

Why qlogs or serialized qlogs are not generated on the server side and while invoked by the browser.  Any insights would be helpful!

**Comment by LPardue** [comment]
The default quiche-server seems to generate logs for me.

Could it be a permissions thing. Have you tried running without sudo?

**Comment by Samy432** [comment]
While operating with sudo the server starts (since the location in which the certificate resides, needs superuser access). If I omit sudo, TLS fails. Here is a backtrace

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TlsFail', apps/src/bin/quiche-server.rs:84:54
stack backtrace:
   0:     0x55a24ec5ab90 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf2e8f024ff77f512
   1:     0x55a24ec7b57c - core::fmt::write::h4b8b6ba0cd5250c6
   2:     0x55a24ec54715 - std::io::Write::write_fmt::he7cc310873fff3e0
   3:     0x55a24ec5c5bb - std::panicking::default_hook::{{closure}}::h63ae463f142febca
   4:     0x55a24ec5c133 - std::panicking::default_hook::hb108960ab0998e8b
   5:     0x55a24ec5cc94 - std::panicking::rust_panic_with_hook::h7cf30b9055d6a0e0
   6:     0x55a24ec5c760 - std::panicking::begin_panic_handler::{{closure}}::h6fa11123890d2867
   7:     0x55a24ec5b054 - std::sys_common::backtrace::__rust_end_short_backtrace::hb3b67b5057f1b4f3
   8:     0x55a24ec5c6c9 - rust_begin_unwind
   9:     0x55a24e660971 - core::panicking::panic_fmt::h31433dac3d1c5dbf
  10:     0x55a24e660a63 - core::result::unwrap_failed::h235348617cf42a6e
  11:     0x55a24ea198ca - core::result::Result<T,E>::unwrap::hc7a71c81acce4799
                               at /builddir/build/BUILD/rustc-1.57.0-src/library/core/src/result.rs:1298:23
  12:     0x55a24e66c157 - quiche_server::main::hbbd927434a81f0cd
                               at /export/home/sc1065/new-quiche/quiche/apps/src/bin/quiche-server.rs:84:5
  13:     0x55a24e6629bb - core::ops::function::FnOnce::call_once::h2b78c7dd002ed480
                               at /builddir/build/BUILD/rustc-1.57.0-src/library/core/src/ops/function.rs:227:5
  14:     0x55a24e6734de - std::sys_common::backtrace::__rust_begin_short_backtrace::hdc50e0c4e96dc868
                               at /builddir/build/BUILD/rustc-1.57.0-src/library/std/src/sys_common/backtrace.rs:123:18
  15:     0x55a24e661fc1 - std::rt::lang_start::{{closure}}::h2176aeeb03b2f0f1
                               at /builddir/build/BUILD/rustc-1.57.0-src/library/std/src/rt.rs:146:18
  16:     0x55a24ec5a86b - std::rt::lang_start_internal::h2216f7249a5de08d
  17:     0x55a24e661f90 - std::rt::lang_start::h23d2b769b9462945
                               at /builddir/build/BUILD/rustc-1.57.0-src/library/std/src/rt.rs:145:17
  18:     0x55a24e6725dc - main
  19:     0x7fd8d6073b75 - __libc_start_main
  20:     0x55a24e66116e - _start
  21:                0x0 - <unknown>

May be I will try to get a local copy of the certificate by changing the permissions from the system administrator and see if the logs are generated. Thanks!

**Comment by junhochoi** [comment]
You may try `sueo -E cargo...` or `sudo env QLOGDIR=<dir> cargo...`, if the environment variable is not passed into sudo.

In my linux bash,

```
$ export AA=1; sudo env | grep AA
$ export AA=1; sudo -E env | grep AA
AA=1
```

**Comment by Libby-24** [comment]
@junhochoi passing the environment variable to sudo works at server side! 

```
sudo env QLOGDIR="path to /quiche/qlog" cargo run --manifest-path=Cargo.toml --bin quiche-server -- --cert /etc/letsencrypt/rb3.cs.unh.edu/fullchain.pem --key /etc/letsencrypt/rb3.cs.unh.edu/privkey.pem --listen 132.177.11.138:4433 --root /export/home/html
```
While rendering the webpage in a bowser from my local machine, here are the commands I try,

```export QLOGDIR="/Users/Sam/Desktop/qlog";sudo -E env ```

```
./Google\ Chrome\ Canary \
  --enable-quic \
  --quic-version=h3-29 \
  --origin-to-force-quic-on=132.177.11.138:4433 \
 https://132.177.11.138:4433
```

In this scenario, the qlogs are not generated when using the browser as a client.  How should I approach this situation? Thanks in advance

**Comment by junhochoi** [comment]
I don't think Chrome supports qlog.

**Comment by Samy432** [comment]
I am trying to use net log from chrome and visualize using qvis.  May be that's one way to do it!
