### ISSUE TITLE
Access log and Debug logs

### ISSUE THREAD

**Issue by Libby-24** [cloudflare/quiche#1166]
Nginix obtained from the patch contains access logs and error logs. Does stand alone quiche server generate access logs and error logs?

**Comment by LPardue** [comment]
quiche-server is intended to be a fairly basic tool. It doesn't provide logs like nginx does with access and error logs. However, it does support both stdout/stderr logging at various levels using [RUSTLOG](https://docs.rs/env_logger/latest/env_logger/). And in addition it supports the [qlog specification](https://datatracker.ietf.org/doc/html/draft-ietf-quic-qlog-main-schema) via the QLOGDIR directive.  For example, `RUST_LOG=trace QLOGDIR=/var/log/qlog quiche-server ...` will give detailed logging about QUIC and HTTP/3 events and more.

**Comment by Libby-24** [comment]
Makes sense! Thanks @LPardue
