### ISSUE TITLE
why quiche_h3_recv_dgram return 1?

### ISSUE THREAD

**Issue by zhngs** [cloudflare/quiche#1184]
ssize_t recv_len = quiche_h3_recv_dgram(h3_conn_, quic_conn_, &flowid, &flowid_len,thread_net_buf, THREAD_LOCAL_BUF_LEN);
As shown above, recv might have a value of 1. Is that normal？

**Comment by LPardue** [comment]
This is an H3 Datagram according to draft 00. The return value is the length of the datagram inclusive of flow ID length. If the value is 1, that indicates the payload length is likely zero and the 1 byte comes from the varint encoding of the flow ID. 0 payload is allowed in the specification. 

So I would assume the sender is emitting an empty H3 Datagram. If you have more logs, that should show it.

**Comment by zhngs** [comment]
Thank you, I know the http3 Datagram protocol. The sender is the Datagram of WebTransport and is unlikely to send empty data. In addition, through my actual test, I found that there are always some abnormal packages in 10,000 Datagrams, such as returning only one byte or the datagram length is shorter than the original. I'm confused about that.

**Comment by LPardue** [comment]
We'd need to see logs and/or a simplified reproduction case to hope to diagnose if there is a problem.

**Comment by zhngs** [comment]
I'm sorry. I retested it a few times, and I made a mistake. Thank you for your patient answer.
