### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by chiwangnvp** [cloudflare/quiche#1187]
Caused by:
  process didn't exit successfully: `D:\ALVR\target\release\build\quiche-a5fe1d85ea90b9f1\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-pc-windows-msvc = None
  CMAKE_TOOLCHAIN_FILE_x86_64_pc_windows_msvc = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-pc-windows-msvc = None
  CMAKE_GENERATOR_x86_64_pc_windows_msvc = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-pc-windows-msvc = None
  CMAKE_PREFIX_PATH_x86_64_pc_windows_msvc = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-pc-windows-msvc = None
  CMAKE_x86_64_pc_windows_msvc = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\ALVR\\alvr\\sockets\\src\\stream_socket\\quiche\\deps/boringssl" "-G" "Visual Studio 16 2019" "-Thost=x64" "-Ax64" "-DCMAKE_INSTALL_PREFIX=D:\\ALVR\\target\\release\\build\\quiche-375c182478ef9e1b\\out" "-DCMAKE_C_FLAGS= -nologo -MD -Brepro" "-DCMAKE_C_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS= -nologo -MD -Brepro" "-DCMAKE_CXX_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS= -nologo -MD -Brepro" "-DCMAKE_ASM_FLAGS_RELEASE= -nologo -MD -Brepro" "-DCMAKE_BUILD_TYPE=Release"
  -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.18363.
  -- The C compiler identification is MSVC 19.28.29913.0
  -- The CXX compiler identification is MSVC 19.28.29913.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.28.29910/bin/Hostx64/x64/cl.exe - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- The ASM_NASM compiler identification is unknown
  -- Didn't find assembler
  -- Configuring incomplete, errors occurred!
  See also "D:/ALVR/target/release/build/quiche-375c182478ef9e1b/out/build/CMakeFiles/CMakeOutput.log".
  See also "D:/ALVR/target/release/build/quiche-375c182478ef9e1b/out/build/CMakeFiles/CMakeError.log".

  --- stderr
  CMake Error at CMakeLists.txt:115 (enable_language):
    No CMAKE_ASM_NASM_COMPILER could be found.

**Comment by chiwangnvp** [comment]
I installed cmake / clang... through visual studio installer and set cmake in windows' env path.

**Comment by junhochoi** [comment]
> No CMAKE_ASM_NASM_COMPILER could be found.

You'll need `nasm` in Windows: https://github.com/cloudflare/quiche#building

**Comment by chiwangnvp** [comment]
Got it
