### ISSUE TITLE
failed build when I porting quiche to some kind of Android project

### ISSUE THREAD

**Issue by chiwangnvp** [cloudflare/quiche#1191]
error: failed to run custom build command for `quiche v0.12.0 (D:\ALVR\alvr\sockets\src\stream_socket\quiche)`

Caused by:
  process didn't exit successfully: `D:\ALVR\target\release\build\quiche-a5fe1d85ea90b9f1\build-script-build` (exit code: 101)
  --- stdout
  CMAKE_GENERATOR_aarch64-linux-android = None
  CMAKE_GENERATOR_aarch64_linux_android = None
  TARGET_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  Info: default compiler flags are disabled
  Info: default compiler flags are disabled
  Info: default compiler flags are disabled
  CMAKE_PREFIX_PATH_aarch64-linux-android = None
  CMAKE_PREFIX_PATH_aarch64_linux_android = None
  TARGET_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_aarch64-linux-android = None
  CMAKE_aarch64_linux_android = None
  TARGET_CMAKE = None
  CMAKE = None
  running: "cmake" "D:\\ALVR\\alvr\\sockets\\src\\stream_socket\\quiche\\deps/boringssl" "-DANDROID_ABI=arm64-v8a" "-DCMAKE_TOOLCHAIN_FILE=E:\\BaiduNetdiskDownload\\android-ndk-r20-windows-x86_64\\android-ndk-r20\\build/cmake/android.toolchain.cmake" "-DANDROID_NATIVE_API_LEVEL=21" "-DANDROID_STL=c++_shared" "-DCMAKE_INSTALL_PREFIX=D:\\ALVR\\target\\aarch64-linux-android\\release\\build\\quiche-2c087510027a42be\\out" "-DCMAKE_C_FLAGS= --target=aarch64-linux-android24" "-DCMAKE_CXX_FLAGS= --target=aarch64-linux-android24" "-DCMAKE_ASM_FLAGS= --target=aarch64-linux-android24" "-DCMAKE_BUILD_TYPE=Release"
  -- Building for: Visual Studio 16 2019
  -- Configuring incomplete, errors occurred!
  See also "D:/ALVR/target/aarch64-linux-android/release/build/quiche-2c087510027a42be/out/build/CMakeFiles/CMakeOutput.log".

  --- stderr
  CMake Error at CMakeLists.txt:9 (project):
    Failed to run MSBuild command:

      C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe

    to get the value of VCTargetsPath:

      鐢ㄤ簬 .NET Framework 鐨? Microsoft (R) 鐢熸垚寮曟搸鐗堟湰 16.9.0+57a23d249
      鐗堟潈鎵?鏈?(C) Microsoft Corporation銆備繚鐣欐墍鏈夋潈鍒┿??

      鐢熸垚鍚姩鏃堕棿涓? 2022/3/10 17:32:37銆?
      鑺傜偣 1 涓婄殑椤圭洰鈥淒:\ALVR\target\aarch64-linux-android\release\build\quiche-2c087510027a42be\out\build\CMakeFiles\3.19.20122902-MSVC_2\VCTargetsPath.vcxproj鈥?(榛樿鐩爣)銆?
      C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(816,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\ALVR\target\aarch64-linux-android\release\build\quiche-2c087510027a42be\out\build\CMakeFiles\3.19.20122902-MSVC_2\VCTargetsPath.vcxproj]
      宸插畬鎴愮敓鎴愰」鐩?淒:\ALVR\target\aarch64-linux-android\release\build\quiche-2c087510027a42be\out\build\CMakeFiles\3.19.20122902-MSVC_2\VCTargetsPath.vcxproj鈥?(榛樿鐩爣)鐨勬搷浣? - 澶辫触銆?

      鐢熸垚澶辫触銆?

      鈥淒:\ALVR\target\aarch64-linux-android\release\build\quiche-2c087510027a42be\out\build\CMakeFiles\3.19.20122902-MSVC_2\VCTargetsPath.vcxproj鈥?(榛樿鐩爣) (1) ->
      (_CheckForInvalidConfigurationAndPlatform 鐩爣) ->
        C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(816,5): error : The BaseOutputPath/OutputPath property is not set for project 'VCTargetsPath.vcxproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\ALVR\target\aarch64-linux-android\release\build\quiche-2c087510027a42be\out\build\CMakeFiles\3.19.20122902-MSVC_2\VCTargetsPath.vcxproj]

          0 涓鍛?
          1 涓敊璇?

      宸茬敤鏃堕棿 00:00:00.38

    Exit code: 1

**Comment by chiwangnvp** [comment]
I build this on Windows, by the way.

**Comment by junhochoi** [comment]
Have you tried our android build instruction? (https://github.com/cloudflare/quiche#building-for-android)
However, our CI only test android build using linux, so there might be other problems when building with Windows.

**Comment by chiwangnvp** [comment]
Thank you for your information, I will try it.

**Comment by chiwangnvp** [comment]
It's done. Thank you.

**Comment by david-stroup** [comment]
hi @chiwangnvp! Could you tell how you fixed it for Windows? I experienced a similar issue.
