### ISSUE TITLE
How about using mio-v0.8 in examples?

### ISSUE THREAD

**Issue by sile** [cloudflare/quiche#1196]
Current examples use a bit older version of mio (v0.6). So what do you think of updating the crate version?
I just tried modifying the examples to use mio-v0.8 (see [sile/quiche#use-latest-mio-in-examples](https://github.com/cloudflare/quiche/compare/master...sile:use-latest-mio-in-examples) branch for the diff), and it wasn't a difficult task.
If there are no special reasons that this project needs to keep using the mio-v0.6, I'd like to create a PR from the above branch.

**Comment by ghedo** [comment]
No reason, other than nobody worked on this before. Feel free to create a PR!

**Comment by sile** [comment]
I see, thanks! I just created the PR: #1200
