### ISSUE TITLE
I made a GUI tool for testing HTTP/3

### ISSUE THREAD

**Issue by alexandrehtrb** [cloudflare/quiche#1214]
Hello,

This is not an issue, I am just sharing in case it could help someone.

I got interested in HTTP/3 and QUIC a few months ago and noticed the lack of a GUI tool, like Postman, for testing. Postman does not support HTTP versions other than 1.1 currently.
I made a tool for that, with support for HTTP/2 and HTTP/3. It uses .NET 6 and msquic on Linux:

https://github.com/alexandrehtrb/Pororoca

**Comment by LPardue** [comment]
Not a comment on the technical merits of your project but advertising a project via an issue is not an appropriate use of the issue tracker.
