### ISSUE TITLE
follow cloudflare quiche to enable nginx support http3. but can not access it from curl(build with ngtcp2) or chrome(canary)

### ISSUE THREAD

**Issue by ShawnBian** [cloudflare/quiche#1219]
Hi  all

I just follow this link https://blog.cloudflare.com/experiment-with-http-3-using-nginx-and-quiche/ to enable nginx support http3

you can see below for nginx listen on 443 for both tcp and udp :
[root@nginxhttp3cloudflare sbin]# netstat -nalp  | grep :443
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      18549/nginx: master 
udp        0      0 0.0.0.0:443             0.0.0.0:*                           18549/nginx: master 

here is configure parameters:

root@nginxhttp3cloudflare sbin]# ./nginx -V
nginx version: nginx/1.16.1
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC) 
built with OpenSSL 1.1.0 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/webapps/nginx --sbin-path=/webapps/nginx/sbin/nginx --conf-path=/webapps/nginx/config/nginx.conf --error-log-path=/webapps/nginx/logs/nginx_error.log --http-log-path=/webapps/nginx/logs/nginx_access.log --pid-path=/webapps/nginx/logs/nginx.pid --user=nginx --group=nginx --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-mail --with-mail_ssl_module --with-http_v2_module --with-http_v3_module --with-openssl=../quiche/deps/boringssl --with-quiche=../quiche
[root@nginxhttp3cloudflare sbin]# 

here is the configure file:

server {
        listen       443 quic reuseport;
        listen       443 ssl http2;
        server_name  www.kaixinduole.com;
        access_log  logs/www.kaixinduole.com.https.log  main;
        ssl_certificate /cert/www.kaixinduole.com/www.kaixinduole.com.pem;
        ssl_certificate_key /cert/www.kaixinduole.com/www.kaixinduole.com.key;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        #ssl_protocols TLSv1.3;
        add_header alt-svc 'h3-23=":443"; ma=86400';

        location / {
            root   html;
            proxy_pass http://backend;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }

    server {
        listen       80 http2;
        server_name  www.kaixinduole.com;
        access_log  logs/www.kaixinduole.com.http.log  main;
        #ssl_certificate /cert/www.kaixinduole.com/www.kaixinduole.com.pem;
        #ssl_certificate_key /cert/www.kaixinduole.com/www.kaixinduole.com.key;
        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        #add_header alt-svc 'h3-23=":443"; ma=86400';

        location / {
            root   html;
            #proxy_pass http://backend;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }
    }
    server {
        listen       80;
        server_name  www.bianmingkai.com;
        access_log  logs/www.bianmingkai.com.http.log  main;
        #ssl_certificate /cert/www.bianmingkai.com/www.bianmingkai.com.pem;
        #ssl_certificate_key /cert/www.bianmingkai.com/www.bianmingkai.com.key;
        #ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        #add_header alt-svc 'h3-23=":443"; ma=86400';

        location / {
            root   html;
            #proxy_pass http://backend;
            index  index.html index.htm;
        }

but I can not access it via curl（ curl has already support http3)

root@ubuntu1:/usr/local/src/curl/src# ./curl --http3 https://nghttp2.org:4433/ -I
HTTP/3 200 
server: nghttp3/ngtcp2 server
content-type: text/html
content-length: 6616

root@ubuntu1:/usr/local/src/curl/src# ./curl --http3 https://www.kaixinduole.com:443/ -I
curl: (56) Failed to connect to www.kaixinduole.com port 443 after 8 ms: Failure when receiving data from the peer
root@ubuntu1:/usr/local/src/curl/src# 

Could you please help to point out the reason? really thanks

**Comment by ghedo** [comment]
Don't know if this is the problem, but the `www.kaixinduole.com` domain doesn't resolve to anything for me.

**Comment by ShawnBian** [comment]
Thank you for the feedback , it is notthe issues ,since we have add the record to hosts file .so that you can not resolve it from internet .thanks

**Comment by ShawnBian** [comment]
I have done the dns resolution .  you can have a try from internet .thanks 
root@ubuntu1:/usr/local/src/curl/src# dig www.kaixinduole.com

; <<>> DiG 9.16.1-Ubuntu <<>> www.kaixinduole.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 59401
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;www.kaixinduole.com.		IN	A

;; ANSWER SECTION:
www.kaixinduole.com.	1708	IN	A	40.73.4.214

;; Query time: 4 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Tue Apr 26 10:08:43 UTC 2022
;; MSG SIZE  rcvd: 64

root@ubuntu1:/usr/local/src/curl/src# ./curl --http3 https://www.kaixinduole.com
curl: (56) Failed to connect to www.kaixinduole.com port 443 after 11 ms: Failure when receiving data from the peer
root@ubuntu1:/usr/local/src/curl/src#

**Comment by ghedo** [comment]
Does your curl build use ngtcp2 or quiche? Anyway, it seems like the quiche version used by your server might be a bit old? So you can try updating it and see if that fixes the problem.

Also, the blog post you followed is quite old as well, the latest information regarding the NGINX build is at https://github.com/cloudflare/quiche/tree/master/nginx#readme= (e.g. the `add_header alt-svc ...` configuration is different).

**Comment by ShawnBian** [comment]
the curl builds with ngtcp2.
Personally, I  don't think it has something to with the version,I have another Nginx(http3) server which uses Nginx 1.19, also have the same problem ..

**Comment by LPardue** [comment]
Did ypu allow UDP port 443 in the firewall?

**Comment by ghedo** [comment]
> I have another Nginx(http3) server which uses Nginx 1.19

I said _quiche_ version, not NGINX. Specifically, when I tried yesterday, it looked like your server didn't advertise QUIC v1, which is needed for ngtcp2 to connect to it, though I can't check this again right now as it looks like the DNS records are gone. As for Chrome, you need to configure the `alt-svc` header as describe at https://github.com/cloudflare/quiche/tree/master/nginx#running= for it to be able to negotiate HTTP/3, in addition to updating the quiche version.

**Comment by ShawnBian** [comment]
HI,

thank you for the feedback , before I just shutdown the dns server ,now I have already made it running and the dns resolution is working now .

I followed the latest link that you have shared to install the newly quiche:

[root@nginxhttp3cloudflare sbin]# ./nginx -V
nginx version: nginx/1.16.1 (quiche-3628e4e)
built by gcc 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC) 
built with OpenSSL 1.1.1 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/webapps/nginx --sbin-path=/webapps/nginx/sbin/nginx --conf-path=/webapps/nginx/config/nginx.conf --error-log-path=/webapps/nginx/logs/nginx_error.log --http-log-path=/webapps/nginx/logs/nginx_access.log --pid-path=/webapps/nginx/logs/nginx.pid --user=nginx --group=nginx --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-mail --with-mail_ssl_module --build=quiche-3628e4e --with-http_ssl_module --with-http_v2_module --with-http_v3_module --with-openssl=../quiche/quiche/deps/boringssl --with-quiche=../quiche
[root@nginxhttp3cloudflare sbin]# 


but it seems still not working:

root@ubuntu1:/usr/local/src/curl/src# ./curl --http3 https://www.kaixinduole.com -v --trace-time 
23:18:52.030458 *   Trying 10.240.0.5:443...
23:18:52.030684 * Connect socket 5 over QUIC to 10.240.0.5:443
23:18:52.040187 *  CAfile: /etc/ssl/certs/ca-certificates.crt
23:18:52.040234 *  CApath: none
23:18:52.044571 *  subjectAltName: host "www.kaixinduole.com" matched cert's "www.kaixinduole.com"
23:18:52.044617 * Verified certificate just fine
23:18:52.044657 * Connected to www.kaixinduole.com () port 443 (#0)
23:18:52.044789 * h2h3 [:method: GET]
23:18:52.044846 * h2h3 [:path: /]
23:18:52.044897 * h2h3 [:scheme: https]
23:18:52.044953 * h2h3 [:authority: www.kaixinduole.com]
23:18:52.044994 * h2h3 [user-agent: curl/7.83.0-DEV]
23:18:52.045040 * h2h3 [accept: */*]
23:18:52.045091 * Using HTTP/3 Stream ID: 0 (easy handle 0x55a53d0bf210)
23:18:52.045215 > GET / HTTP/3
23:18:52.045215 > Host: www.kaixinduole.com
23:18:52.045215 > user-agent: curl/7.83.0-DEV
23:18:52.045215 > accept: */*
23:18:52.045215 > 
23:18:52.046222 * ngh3_stream_recv returns 0 bytes and EAGAIN
23:18:52.046428 * ngh3_stream_recv returns 0 bytes and EAGAIN

**Comment by ShawnBian** [comment]
Hi , 

please ignore the post above, now it is work for both curl and chrome .thanks for the help

root@ubuntu1:/usr/local/src/curl/src# ./curl --http3 https://www.kaixinduole.com -v 
*   Trying 10.240.0.5:443...
* Connect socket 5 over QUIC to 10.240.0.5:443
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
*  subjectAltName: host "www.kaixinduole.com" matched cert's "www.kaixinduole.com"
* Verified certificate just fine
* Connected to www.kaixinduole.com () port 443 (#0)
* h2h3 [:method: GET]
* h2h3 [:path: /]
* h2h3 [:scheme: https]
* h2h3 [:authority: www.kaixinduole.com]
* h2h3 [user-agent: curl/7.83.0-DEV]
* h2h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55ecb378f210)
> GET / HTTP/3
> Host: www.kaixinduole.com
> user-agent: curl/7.83.0-DEV
> accept: */*
> 
* ngh3_stream_recv returns 0 bytes and EAGAIN
< HTTP/3 200 
< server: nginx/1.16.1
< date: Wed, 27 Apr 2022 23:36:22 GMT
< content-type: text/html; charset=UTF-8
< content-length: 44
< vary: Accept-Encoding
< last-modified: Tue, 26 Apr 2022 02:50:13 GMT
< etag: "2c-5dd85c07a08bf"
< accept-ranges: bytes
< alt-svc: h3=":443"; ma=86400
< 
index.html service for apache from 10.3.0.5
* Connection #0 to host www.kaixinduole.com left intact

before we close this ticket ,do you have any docs  describe the http3 protocol in details such as how to use quiche to do tls handshake etc..

**Comment by ghedo** [comment]
> do you have any docs describe the http3 protocol in details such as how to use quiche to do tls handshake etc..

If you want  documentation about quiche specifically, you can look at https://docs.quic.tech/quiche/

If you want documentation on QUIC and HTTP/3 in general, your best bet is probably looking at the official documents, see https://quicwg.org/

**Comment by ShawnBian** [comment]
thanks
