### ISSUE TITLE
Questions about flow control for Datagrams in QUIC/quiche

### ISSUE THREAD

**Issue by kalradivyanshu** [cloudflare/quiche#1222]
We are trying to send a lot of datagrams using quiche (we are using `quiche::h3::send_dgram`). However the system touches 800 - 900 mbps and quickly reduces to 550-600 and stays there. We suspect that this is a issue with flow control, since CPU and network is underutilized (iperf shows that the network can send 1.5 gbps of data on UDP, and CPU usage is less than 50%). Going through https://www.rfc-editor.org/rfc/rfc9000.htm and https://datatracker.ietf.org/doc/html/draft-ietf-quic-datagram it seems to me, that even though QUIC datagrams are ack-eliciting, QUIC's internal flow control doesnt apply to them. But they are affected by congestion control.

```
   DATAGRAM frames do not provide any explicit flow control signaling,
   and do not contribute to any per-flow or connection-wide data limit.
```
(from https://datatracker.ietf.org/doc/html/draft-ietf-quic-datagram#section-5.3)

So that might be what is happening, we are sending way too many datagram than the connection can handle, and triggering congestion control. So the question is how should we do flow control for datagram, should we just go through the implementation details of flow control in RFC9000 and do that for Datagram on the application side? Are there any resources of best practices to create flow control for unreliable datagrams?

**Comment by LPardue** [comment]
For fear of stating what is already known, flow control and congestion control are different things.

Congestion control is intended as a way to best utilise the network path capacity. And various algorithms have different approaches to achieving that. Flow control happens above that and is intended to best utilise the recievers resource limita. It's possible for flow control to limit the rate of data but very unlikely for flow control to improve it more than the congestion controller would allow.

As I keep saying, to have any hope of advising on these issues, we would need to see qlogs and to analyse the actual behaviour of connections you are investigating. Without that, all we can do is speculate with limited data, and that isn't an effective use of time.

**Comment by kalradivyanshu** [comment]
Makes sense, here are the qlogs for the client and server:

[qlogs.zip](https://github.com/cloudflare/quiche/files/8619960/qlogs.zip)

**Comment by LPardue** [comment]
It seems in the bad client case that you're not filling the congestion window, it would be interesting to know why that's happening

![image](https://user-images.githubusercontent.com/6571445/167488199-ab891567-8df0-44eb-931d-ea5aceccbdd4.png)
