### ISSUE TITLE
Quiche 0.13.0 panics with 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by lorban** [cloudflare/quiche#1232]
We (the Jetty project) recently tried to upgrade from quiche 0.12.0 to 0.13.0 and while running our test suite, we encountered frequent process crashes when the H3 tests are running.

We obviously are using quiche via FFI, but so far this has worked like a charm and everything worked without problem until that upgrade to version 0.13.0 so we're inclined to believe the problem is in quiche itself.

Here's the info we managed to collect when our test process crashes:

```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', quiche/src/lib.rs:5499:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/std/src/panicking.rs:517:5
   1: core::panicking::panic_fmt
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:101:14
   2: core::panicking::panic
             at /rustc/09c42c45858d5f3aedfa670698275303a3d19afa/library/core/src/panicking.rs:50:5
   3: quiche::Connection::delivery_rate_check_if_app_limited
             at /home/ubuntu/github/quiche/0.13.0/quiche/src/lib.rs:5499:13
   4: quiche::Connection::process_frame
             at /home/ubuntu/github/quiche/0.13.0/quiche/src/lib.rs:5046:20
   5: quiche::Connection::recv_single
             at /home/ubuntu/github/quiche/0.13.0/quiche/src/lib.rs:2288:29
   6: quiche::Connection::recv
             at /home/ubuntu/github/quiche/0.13.0/quiche/src/lib.rs:1866:30
   7: quiche_conn_recv
             at /home/ubuntu/github/quiche/0.13.0/quiche/src/ffi.rs:652:11
   8: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by junhochoi** [comment]
Thanks @lorban for reporting! This function is added after 0.12.0.
I made a fix in #1233, can you try if it's fixed?

**Comment by lorban** [comment]
@junhochoi I built the branch you used for https://github.com/cloudflare/quiche/pull/1233 and re-ran our test suite multiple times against this build and I haven't seen a crash since.

Thanks for the quick feedback and the fix!

**Comment by ghedo** [comment]
https://github.com/cloudflare/quiche/pull/1233 is merged, closing. Thanks @lorban for reporting the issue!
