### ISSUE TITLE
Clarify which configuration options are mandatory

### ISSUE THREAD

**Issue by jyn514** [cloudflare/quiche#1250]
Using `quiche::Config::default()` will almost never work. At least the following options have to be set:
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_streams_bidi
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_streams_uni
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_data
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_stream_data_bidi_local
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_stream_data_bidi_remote
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_initial_max_stream_data_uni

In most cases, the ALPN and certificates have to be set as well:
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.set_application_protos
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_verify_locations_from_file (for clients)
- https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_cert_chain_from_pem_file / https://docs.rs/quiche/latest/quiche/struct.Config.html#method.load_priv_key_from_pem_file (for servers)

It would be great to document these prominently somewhere, as well as clarify the existing documentation which says
> When set to a non-zero value quiche will only allow at most v bytes of incoming stream data to be buffered for each locally-initiated bidirectional stream.
> The default value is 0.

That misleadingly implies that quiche will allow an unlimited number of bytes when it's set to 0, which is not the case; instead it allows no bytes.

**Comment by CMCDragonkai** [comment]
This was confusing to me. If you run a QUIC server, and you don't pass in  certificate chain or private key, even if you are not verifying peers, it will result in `TlsFail` error when you perform `conn.recv()`.

But for the client, they don't need to set it all. It's only necessary for the server.

This means certificate and key is mandatory for servers even if you were to disable `verify_peer()` on both sides.

Was this intentional?

**Comment by AurelienFT** [comment]
I encour the same problem as you @CMCDragonkai do you have any help ? I don't wanna use certificated for now.

**Comment by LPardue** [comment]
QUIC uses TLS for the handshake. If you aren't using certificates, what other means of authorization would you use?

**Comment by AurelienFT** [comment]
> QUIC uses TLS for the handshake. If you aren't using certificates, what other means of authorization would you use?

I want to use asymmetric cryptography for example with ed25519

**Comment by LPardue** [comment]
We use boringSSL, so before considering what quiche can do you'd want to figure out if your design can fit within the TLs extension framework and then whether BoringSSL implements it. If this is already the case, specific pointers would help

**Comment by AurelienFT** [comment]
> We use boringSSL, so before considering what quiche can do you'd want to figure out if your design can fit within the TLs extension framework and then whether BoringSSL implements it. If this is already the case, specific pointers would help

Ok I need to check BoringSSL. Thank you !

**Comment by CMCDragonkai** [comment]
In my case I'm interested in passing the TLS certificate as an in-memory structure, not as a file path.

**Comment by AurelienFT** [comment]
Me too ! I wrote an issue about that : https://github.com/cloudflare/boring/issues/105

**Comment by LPardue** [comment]
Loading certificates from memory is possible by manually creating a TLS context, populating it yourself, and using `with_boring_ssl_ctx` to create a Config object.
