### ISSUE TITLE
No ACK is sent when the cwnd is full

### ISSUE THREAD

**Issue by francoismichel** [cloudflare/quiche#1277]
Hello,

It seems that in `send_single()` in `lib.rs`, ACKs are only added to packets when the congestion window has remaining space.

This can lead to problems when both endpoints are sending: the receiver of new data won't be able to send the ACK frames
and it can lead to poor performances or connection interruption that I experienced during some tests.

The `left` variable should maybe not be capped to the `cwnd_available` of the path while ACKs have not been packed into the packet.

I can work on a PR to fix the issue.

What do you think ?

**Comment by LPardue** [comment]
Hey @francoismichel . Thanks for the report. I think you're correct in your assessment that we are missing opportunities to send ACKs if cwnd is full. From RFC 9000, only ACK-only packets don't count against cwnd. So a better solution might be to have a branch of code in send_single() that is invoked when the cwnd_available = 0, that branch would only consider sending ACKs (transmission or retransmission).

**Comment by francoismichel** [comment]
Just opened #1385 to fix this. It seems to work correctly.

It changes quite a few lines of code because of the renaming of the `left` variable and `cargo fmt`.

> So a better solution might be to have a branch of code in send_single() that is invoked when the cwnd_available = 0, that branch would only consider sending ACKs (transmission or retransmission).

I did not follow this exact approach to be able to correctly handle the cases where 0 < cwnd_available < ack_frame_size. Let me know if you wish to change anything.
