### ISSUE TITLE
unknown "quic" variable

### ISSUE THREAD

**Issue by thb007** [cloudflare/quiche#1289]
When adding "add_header QUIC-Status $quic" to the nginx configuration, when starting nginx, an error is reported and nginx is "prompted: [emerg] unknown "quic" variable"

```
root@debian:~/build/nginx-1.23.1# systemctl restart nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl status nginx.service" and "journalctl -xe" for details.
root@debian:~/build/nginx-1.23.1# nginx -t
nginx: [emerg] unknown "quic" variable

```

**Comment by steklopod** [comment]
I have `nginx: [emerg] invalid parameter "quic" in /etc/nginx/sites/admin.colaba.online.conf:16` :-(

**Comment by ghedo** [comment]
If you are using the NGINX patch [we provide](https://github.com/cloudflare/quiche/tree/master/nginx), there is no `$quic` variable so this is expected, but there is one called `$http3` as per [our documentation](https://github.com/cloudflare/quiche/tree/master/nginx#list-of-variables).

If on the other hand you are using the QUIC support provided by NGINX upstream, then you should contact the NGINX project itself for support.

**Comment by steklopod** [comment]
Thank you for reply. I took this from the link that you provided
![4E79814B-34DD-4385-9EDF-B8BE80593C4F](https://user-images.githubusercontent.com/29500153/182124234-14439a95-c268-4f9c-b881-23caa9729c73.jpeg)

removing this solves the error

**Comment by ghedo** [comment]
@steklopod ah, sorry, didn't realize that was in the example. We'll update that.

**Comment by ghedo** [comment]
@steklopod  Actually wait, that is a completely different issue, that is not a variable, and removing the thing you highlighted just disables QUIC support if you are using the patch we provided. But again, if you are using the QUIC support provided by NGINX, then this repo has nothing to do with that.
