### ISSUE TITLE
Consider using rustls

### ISSUE THREAD

**Issue by khionu** [cloudflare/quiche#129]
It's worth reading the [basis and history of `ring`](https://github.com/briansmith/ring#ring). It's essentially a careful port of BoringSSL. Lots of crates use `ring`, and there is an easy-to-use implementation of TLS over `ring` called [`rustls`](https://github.com/ctz/rustls/). While they do need a proper security audit, [they have investigated getting a grant for one](https://github.com/ctz/rustls/issues/189). 

If it's a goal of `quiche` to be considerate of the Rust Ecosystem, it would be worthwhile to investigate.

**Comment by ghedo** [comment]
This is unlikely to happen I'm afraid, as we run BoringSSL in our production TLS and QUIC services, and supporting both would mean that the rustls port would always be second-class to the BoringSSL one, as well as add additional complexity to the codebase that we can do without.
