### ISSUE TITLE
Suggestion: Add the address pointer parameter non-null check to the FFI interface function

### ISSUE THREAD

**Issue by Jamesinit** [cloudflare/quiche#1293]
Today I had a problem: quiche_conn_send function panic. 
At first I thought it was a problem inside the function, but it turns out that the args CONN address passed in is empty, causing panic when using the Connection object in the function.

**Comment by LPardue** [comment]
I'm not seeing much upside to this proposal. 

It would place a unilateral additional overhead on all applications that use the C API. Apps that want to check for NULL can do that themselves very easily. Apps that already do that would then encounter a redundant second NULL-pointer check. 

Furthermore, if a NULL was encountered, how would quiche even respond? Return an error or explicitly panic?

Given the error is drastic and not that hard to debug when it occurs, I think status quo is ok.
