### ISSUE TITLE
Data in transit before STOP_SENDING is received causes a "leak" in flow control

### ISSUE THREAD

**Issue by kevinjohna6** [cloudflare/quiche#1320]
Data in transit before STOP_SENDING is received by a peer will cause a "leak" in the flow control, reducing the usable window, eventually causing a communication stall or timeout.

Data written in a draining stream will never get added to `FlowControl`'s `consumed`, leading to a permanent/growing difference between `tx_data` on one peer and `consumed` on the other. This reduces the usable window, and eventually prevents MAX_DATA from being sent, causing the transmitting peer to timeout or stall.

Here is an example where the difference reached the window size and caused a connection timeout:
```
Server:
  rx_data: 173888119
  flow_control:
    consumed: 171413633
    max_data: 173888119
    window: 3145728

Client:
  tx_cap: 0
  tx_data: 173888119
  max_tx_data: 173888119
  last_tx_data: 173888119
```

Test sequence that exhibits this behavior:
```rs
let mut buf = [0; 65535];

let mut config = Config::new(crate::PROTOCOL_VERSION).unwrap();
config
    .load_cert_chain_from_pem_file("examples/cert.crt")
    .unwrap();
config
    .load_priv_key_from_pem_file("examples/cert.key")
    .unwrap();
config
    .set_application_protos(&[b"proto1", b"proto2"])
    .unwrap();
config.set_initial_max_data(30);
config.set_initial_max_stream_data_bidi_local(10000);
config.set_initial_max_stream_data_bidi_remote(10000);
config.set_initial_max_streams_bidi(10);
config.verify_peer(false);

let mut pipe = testing::Pipe::with_config(&mut config).unwrap();
assert_eq!(pipe.handshake(), Ok(()));

assert_eq!(pipe.client.stream_send(0, b"a", false), Ok(1));
assert_eq!(pipe.advance(), Ok(()));
assert_eq!(pipe.server.stream_recv(0, &mut buf), Ok((1, false)));
assert_eq!(pipe.server.stream_shutdown(0, Shutdown::Read, 123), Ok(()));

assert_eq!(pipe.server.rx_data, 1);
assert_eq!(pipe.client.tx_data, 1);
assert_eq!(pipe.client.max_tx_data, 30);

assert_eq!(pipe.client.stream_send(0, &buf[..pipe.client.tx_cap], false), Ok(29));
assert_eq!(pipe.advance(), Ok(()));

assert_eq!(pipe.server.stream_readable(0), false); //nothing can be consumed

// the client has increased its tx_data, and server has received it,
// but will never add those bytes to flow_control.consumed.
// this leaves the client's tx_cap stuck at 0
assert_eq!(pipe.client.tx_data, 30);
assert_eq!(pipe.server.rx_data, 30);
assert_eq!(pipe.client.tx_cap, 0);

//the client is unable to send any additional data

panic!("connection stuck");
```

I'm guessing that data received for a draining stream (and the data cleared from the buffer) should be added to the consumed counter right away.

> STREAM frames received after sending a STOP_SENDING frame are still
   counted toward connection and stream flow control, even though these
   frames can be discarded upon receipt.

**Comment by ghedo** [comment]
Thanks for the report and test case. It looks like the problem is that the server doesn't update the max_data limit, even if the drained data was technically "consumed". I made https://github.com/cloudflare/quiche/pull/1321 to fix the issue.
