### ISSUE TITLE
linux sendfile?

### ISSUE THREAD

**Issue by LumiereDeLOmbre** [cloudflare/quiche#1338]
Hi,
Do you plan to have sendfile enabled in the protocol? In order to.. send files faster.

Otherwise, where is a good place to start to implement it?
I am a c++ dev, not rust, so I am not really sure about the best move here.. thanks

**Comment by LeHibou2** [comment]
(not in the protocol itself, but its implementation, of course)

**Comment by junhochoi** [comment]
It's out of scope - sendfile() is using TCP.

**Comment by LumiereDeLOmbre** [comment]
Oups my bad thanks
