### ISSUE TITLE
panic when using --early-data and --session-file together

### ISSUE THREAD

**Issue by moderation** [cloudflare/quiche#1343]
With latest main commit, `quiche-client` panics when using `--early-data` and `--session-file` together. When used individually the requests work fine

`quiche-client --early-data --session-file=/home/<user>/.quiche-client.cache https://www.google.com/`
```
thread 'main' panicked at 'Unable to create HTTP/3 connection, check the server's uni stream limit and window size: InternalError', apps/src/common.rs:980:15
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by LPardue** [comment]
Thanks for the report @moderation. Confirmed the problem. Added a fix and a test case in https://github.com/cloudflare/quiche/pull/1345
