### ISSUE TITLE
Can't download big files by using quiche integrated with curl

### ISSUE THREAD

**Issue by GauravChawda** [cloudflare/quiche#1360]
I have file-server (caddy) running on localhost using http/3 protocol serving one file of 2319MiB. 
When I try to download that file using curl with http3 support, the download stops at 129MiB (see attached screenshot). 
Same file can be downloaded successfully by using http/2 protocol or by using web browser (Firefox in my case).

Can anyone give me insights what exactly is happening here and how to resolve this issue.

![quiche-issue](https://user-images.githubusercontent.com/42804494/200749067-f63b6150-ef13-4080-b8e8-cfc99d56d8f7.png)

**Comment by LPardue** [comment]
Might be related to https://github.com/cloudflare/quiche/issues/1115

**Comment by icing** [comment]
@LPardue thanks, will do tomorrow. #1115 could be, I think with debug logging I saw quiche dropping invalid packets at around the stall time.

**Comment by icing** [comment]
Update on this: the fix of #1115 fixed this problem.

Now, could you make a v0.17 version jump and tag? Then I will update the curl configure to check for that. Thanks!

**Comment by LPardue** [comment]
We're at v0.18 now, and in the meantime curl has continued other :bug:  squashing. @icing I think we can close this one?

**Comment by icing** [comment]
@LPardue yes, thanks for fixing this.
