### ISSUE TITLE
how to upload a img with http3?

### ISSUE THREAD

**Issue by zhangbtciab** [cloudflare/quiche#1363]
I upload a img with the interface "h3_conn.send_body(&mut conn, stream_id, &body, true).unwrap();"  and I append the header " //  b"content-type,   b"multipart/form-data".  quiche-http3 as client . nginx-quic as server .  I received the response code 415. 

this is the server log.
Content-Type is not multipart/form-data and no Content-Disposition header found, client: 172.168.1.35, server: nginx-quic, request: "POST /upload HTTP/3.0"

**Comment by LPardue** [comment]
Sounds like your request is malformed and needs to be correctly formatted in order to pass nginx's semantic HTTP handling rules. These are out of scope for quiche.
