### ISSUE TITLE
Using the same UDP socket for both client and server

### ISSUE THREAD

**Issue by CMCDragonkai** [cloudflare/quiche#1378]
Using the same UDP socket is necessary for P2P nat-traversal.

Looking over the client and server code, it appears we can of course share the same UDP socket.

However when receiving data on the UDP socket, how should we differentiate between client packets or server packets? Furthermore there could be multiple client connections on the same socket.

This was made possible in https://github.com/lucas-clemente/quic-go/issues/561.

**Comment by tbu-** [comment]
You could distinguish these by connection ID.

**Comment by CMCDragonkai** [comment]
That's what I've started to do. However I'm a bit confused about how the server examples currently derive a connection ID deterministically from the `header.dcid` and then proceeds to check whether both exist in a connection map.

How would this translate with respect to client connections? Would we do the same thing?

**Comment by CMCDragonkai** [comment]
Thanks works.
