### ISSUE TITLE
Some examples based tokio?

### ISSUE THREAD

**Issue by snow2flying** [cloudflare/quiche#139]
Thanks for your quic project,awesome, really appreciate it.
Is it possible to have some examples that based on tokio using rust's latest futues/async,not  mio using state machine?

**Comment by LoganDark** [comment]
quiche does not support async, it's not even designed to be used from Rust, it's designed to be used from C for CloudFlare's servers. It's already been a couple years but your best bet is _still_ to wait a couple more years for https://github.com/hyperium/h3 to be published
