### ISSUE TITLE
SetMaxPacingRate or similar for a QUIC connection?

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#1420]
Is there a way to set the max pacing rate from a QUIC connection client side ? For example, any API similar to the one in Google's [C++ implementation](https://quiche.googlesource.com/quiche/+/refs/heads/main/quiche/quic/core/quic_connection.h#524) ?

**Comment by lohith-bellad** [comment]
https://github.com/cloudflare/quiche/pull/1476
