### ISSUE TITLE
Confusion in doc of `send` in `Connection`

### ISSUE THREAD

**Issue by AurelienFT** [cloudflare/quiche#1428]
Hello,
I try to follow the example you provided and work with it on my side.

I'm very confused by the documentation of the `send` method of `Connection`. The docs says : 

```
Writes a single QUIC packet to be sent to the peer.
```

So I assume it will format my packet so that I can send it to the socket afterwards (as in the example). But in the following lines of the docs it says : 

```
When the application receives QUIC packets from the peer (that is, any time [recv()](https://docs.rs/quiche/0.16.0/quiche/struct.Connection.html#method.recv) is also called).
```

So I need to call `connection.recv()` and then `connection.send()` ? But why I need to call a method that prepare a packet to be sent when I receive it, and so what the point of `connection.recv()` ? It seems strange to me.

Thanks for the time you took to read my question and potentially answer it :)

**Comment by LPardue** [comment]
Hey. One of the simplest explanations I can think of is that when a QUIC endpoints receives packets, it is expected to acknowledge them (by default, QUIC acknowledges every other packet, but extensions can change that). 

Quiche takes responsibility for the QUIC-level machinery; when you feed quiche via `recv()`, the internal state can update and create the need to emit ACK frames or other types of frames via `send()`. If you don't call `send()` frequently, you risk not sending important data in a timely manner, which could cause the peer to react as if a data loss ocurred (or other problems, like flow control)

**Comment by AurelienFT** [comment]
Ok it's way more clear now. Thanks a lot ! I will add `send()` after each receive of packets !

**Comment by LPardue** [comment]
Reading 1 packet and sending 1 packet might not be great. Its worth trying out reading a batch of packets before sending a batch of packets. The specific timing and batch size that is good varies depending on use case.

**Comment by AurelienFT** [comment]
> Reading 1 packet and sending 1 packet might not be great. Its worth trying out reading a batch of packets before sending a batch of packets. The specific timing and batch size that is good varies depending on use case.

As it's shown in the doc to `send` in loop ? I can for example `connection.recv()` X packets and after make a `connection.send()` but what I need to pass as parameter of my `connection.send()` the last packet received ?

**Comment by LPardue** [comment]
Calling recv() modifies internal state. The only thing you need to pass to send() is structures related to sending, like a buffer for it to write the packet into.

**Comment by AurelienFT** [comment]
> Calling recv() modifies internal state. The only thing you need to pass to send() is structures related to sending, like a buffer for it to write the packet into.

Mhh I think there is something I'm missing. For example I want to send some data to the socket. As shown in the docs I fill my buffer and send it to `connection.send()` before sending it to `socket.send_to()`.

But when I `connection.recv()` with the data I receive multiple time. What do I send in the buffer passed to `connection.send()` an empty buffer ?

**Comment by AurelienFT** [comment]
Oh ok that is way more clear ! Thanks a lot for your time !

**Comment by LPardue** [comment]
Happy to help!

**Comment by AurelienFT** [comment]
> Happy to help!

If I can abuse your kindness, I'm really lost with the tls and `BoringSSL`. I didn't find a good example/documentation about how I can create my SslContext from a keypair ed25519. It seems pretty straightforward with a file but not with a rust structure keypair. I know it's not the same repository and not the context of the issue (I can delete my comment after) but as it's maintained by the same company, if you have an example/doc that could be very helpful.

Thanks again for your precedent answers.
