### ISSUE TITLE
quiche_h3_send_dgram return QUICHE_H3_ERR_DONE

### ISSUE THREAD

**Issue by zhngs** [cloudflare/quiche#1434]
Our server works well with quiche for a long time, but the above errors occasionally occur. I don't know what causes them. How could send datagram fail？

**Comment by zhngs** [comment]
Looking at the source code, the datagram queue is full，but I don not know why

**Comment by LPardue** [comment]
Datagrams are not flow controlled but they are congestion controlled. Sounds like your datagram producer is creating them at a rate faster than QUIC can send them, leading to the internal queue filling up.

**Comment by zhngs** [comment]
Thanks! I'll try to find out

**Comment by LPardue** [comment]
Closing since this doesn't sound like a problem in the library.
