### ISSUE TITLE
SSLKEYLOGFILE does not correctly decrypt PCAP files

### ISSUE THREAD

**Issue by jackmygreat** [cloudflare/quiche#1453]
Hello, I use the latest Quiche version, the commit version is 2183ded, but the SSLKEYLOGFILE cannot decrypt the packet.
The quiche commit number is 2183ded.
The wireshark version is 4.0.3 (v4.0.3-0-gc552f74cdc23).
The client IP is 192.168.56.103 . The server IP is 192.168.56.104
The client command is : run --package quiche_apps --bin quiche-client   -- --no-verify https://192.168.56.104:4433/Cargo.toml
The server command is : run --package quiche_apps --bin quiche-server -- --cert apps/src/bin/cert.crt --key apps/src/bin/cert.key --listen [::]:4433 --root ./

The pcap file and SSLKEYLOGFILE in server is here .
[pcap.zip](https://github.com/cloudflare/quiche/files/11060289/pcap.zip)

[sslkeylog.log](https://github.com/cloudflare/quiche/files/11060266/sslkeylog.log)

![image](https://user-images.githubusercontent.com/44282977/227466931-4738cd64-987b-43b4-b396-27f98f98a688.png)

**Comment by LPardue** [comment]
Thanks for the report. Testing locally, this seems to be caused by the version negotiation part. I didn't look closely into why, perhaps its a Wireshark regression (so cc @alagoutte @Lekensteyn ) or maybe a quiche one.

You can work around this by running the client with an explicit wire version such as `--wire-version 1`

**Comment by alagoutte** [comment]
Hi,

it is possible to attach some pcap (and SSLKEYLOGFILE) on wireshark issue tracker ? (and may be also test nighty build ?)

**Comment by jackmygreat** [comment]
@LPardue I have tested quiche with --wire-version 1. But Wireshark also has this issue.

**Comment by jackmygreat** [comment]
@alagoutte thank you

**Comment by jackmygreat** [comment]
@alagoutte I create an issue on wireshark issue tracker. The  wireshark issue is  https://gitlab.com/wireshark/wireshark/-/issues/18974

**Comment by jackmygreat** [comment]
All problems have been solved. Please see this link https://gitlab.com/wireshark/wireshark/-/issues/18974
