### ISSUE TITLE
DOES NGINX use QUICHE's congestion control?

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#1455]
QUICHE's default congestion control (CUBIC) can be changed to Reno or BBR. If I change the congestion control in quiche and start the NGINX server, will NGINX use QUICHE's changed congestion control?

The reason I ask this is, I want the details about the HTTP request, which is stored in access log in NGINX. QUICHE has qlogs but it does not have access logs (and the qlogs generated for video streaming is very huge >100MB and cannot be visualized by qvis). So, I would prefer to stick to NGINX server as I can parse the access logs. I want to study the behavior of video streaming under various congestion control algorithms. 

Any pointers is greatly appreciated.

**Comment by LPardue** [comment]
The nginx patch in this repo doesn't currently include a way that makes it easy to adjust the congestion control. But its pretty straightforward to patch in for experimentation using `quiche_config_set_cc_algorithm()`; see https://github.com/cloudflare/quiche/blob/master/quiche/include/quiche.h#L212-L219

**Comment by LPardue** [comment]
CLosing since the question was answered.

**Comment by junhochoi** [comment]
master branch (and 0.18.0) now has nginx configuration directive for QUIC congestion control: https://github.com/cloudflare/quiche/blob/master/nginx/README.md#http3_congestion_control
