### ISSUE TITLE
Stream priority in Quiche

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#1477]
By modifying the HTTP request to include the priority request (setting urgency flag), 

eg:
:method = GET
:scheme = https
:authority = video.org
:path = /video1.mp4
priority = u=0

In the above example, video1.mp4 will be transported immediately. 
1. Does quiche have the ability to transport "video1.mp4" in a prioritized stream?
2. Will additional bandwidth be assigned to the stream that is transporting "video1.mp4"?

**Comment by LPardue** [comment]
Priorities only really matter when there are multiple streams competing for the connection. In this example, there's only one object so the priority doesn't change much.

If you had multiple streams, then we implement the schedule logic defined in RFC 9218. We ironed out a few issues with that as of quiche release 0.18 so you might want to experiment with that.
