### ISSUE TITLE
Wrong RTT being calculated when pacing is turned on.

### ISSUE THREAD

**Issue by kalradivyanshu** [cloudflare/quiche#1513]
We were debugging some issues, and found a very peculiar behaviour in quiche. Quiche underreports RTT by a lot if pacing is turned on. We have a server in mumbai and one in delhi, the mumbai server is the quiche server run with:
```
QLOGDIR=./logs RUST_LOG=info cargo run --bin quiche-server --release -- --cert apps/src/bin/cert.crt --key apps/src/bin/cert.key --listen 0.0.0.0:4434 --cc-algorithm bbr --root apps/src/bin/root
```
The ping command shows the ping as 30 - 32ms:
![image](https://github.com/cloudflare/quiche/assets/12642750/c2a98ee6-a629-4809-a817-6f21180a2311)

running the server with `--disable-pacing` and then printing the path min_rtt every 200ms shows:
![image](https://github.com/cloudflare/quiche/assets/12642750/108135e4-1eac-4d47-83ba-28a46f8b5b57)

we printed this by add the following snippet:
```rust
 if last_stat_at.elapsed() > Duration::from_millis(200) {
    for stat in client.conn.path_stats() {
        log::info!("path_min_rtt: {:?}", stat.min_rtt);
    }
    last_stat_at = std::time::Instant::now();
}
```

But when we remove `--disable-pacing` the RTT is reported as 1.1 ms or even lower:

![image](https://github.com/cloudflare/quiche/assets/12642750/e03b43df-e626-4b48-b84f-5b3b261a43df)

The SO_TXTIME socket is being set:
![image](https://github.com/cloudflare/quiche/assets/12642750/b70dd64a-53ea-4f69-84dd-5a699cbae6ca)

Steps to reproduce:
1. Clone https://github.com/cloudflare/quiche in two servers with 20ms or more RTT between them.
2. run `QLOGDIR=./logs RUST_LOG=info cargo run --bin quiche-server --release -- --cert apps/src/bin/cert.crt --key apps/src/bin/cert.key --listen 0.0.0.0:4434 --cc-algorithm bbr --root apps/src/bin/root` in one of them
3. run `cargo run --bin quiche-client -- https://ip:4434/index.html --no-verify` in the other
4. check the value of rtt min either via logging it in the server or by qlog
5. repeat 2, 3, 4 but now with `QLOGDIR=./logs RUST_LOG=info cargo run --bin quiche-server --release -- --cert apps/src/bin/cert.crt --key apps/src/bin/cert.key --listen 0.0.0.0:4434 --cc-algorithm bbr --root apps/src/bin/root --disable-pacing` in the server

Expected behaviour:
The min RTT in both cases should be same

Actual behaviour:
The min RTT when pacing is on is significately lower that the actual RTT.

Qlogs: 
[rtt_bug.zip](https://github.com/cloudflare/quiche/files/11487776/rtt_bug.zip)
(`server-pacing.sqlog` is the one with pacing turned on, `server-no_pacing.sqlog` is with pacing disabled)

More info:
the quiche server was ran on a intel server running Ubuntu 22.04 with linux kernel 5.15.

**Comment by ghedo** [comment]
Just to confirm, did you also configure the `fq` packet scheduler on the server (https://man7.org/linux/man-pages/man8/tc-fq.8.html)? Otherwise the `SO_TXTIME` value will be ignored.
