### ISSUE TITLE
How to have the server send content to a client connection (beginner here!)

### ISSUE THREAD

**Issue by PatrickPicca** [cloudflare/quiche#1518]
So I'm trying to set up a working client and server connection as a part of a class project, where once a connection is formed the server is to send a file to the client. In trying to understand the steps to make this happen I'm starting with the default quiche-server. After a bit of head scratching I managed to get a quiche-client to contact the server as follows.

![4](https://github.com/cloudflare/quiche/assets/14206053/f9a9fcbc-ebb6-4aea-905f-846953af6357)

The "Recieved Packet" debug message was just me figuring out that packets are being received on the server side, from the client. The problem is, to my understanding, the default server sends nothing to the client, and the client simply prints a "Not found" message as no content has been received. Any help is figuring this process out? It's entirely possible I am completely misunderstanding what I'm trying to accomplish with this client and server, but I'm running into a wall in figuring out how to attach content to be sent by the server.

**Comment by LPardue** [comment]
Hi. The `Not Found` response is the default content sent when the server cannot find a suitable file in it's server root path. There's a default that you can override; see https://github.com/cloudflare/quiche/blob/master/apps/src/args.rs#L418 .

You can also set the envrionment variables RUST_LOG=info or RUST_LOG=trace to enable more verbose logging of the apps, which will show you things like HTTP headers.

**Comment by PatrickPicca** [comment]
I created the example.txt file you mentioned, listed the path to the root where it was located, and I managed to get the client to successfully obtained the content within! Thank you for the assistance!

**Comment by LPardue** [comment]
Resolved, so closing the issue.
