### ISSUE TITLE
Potential UB in example server

### ISSUE THREAD

**Issue by kalradivyanshu** [cloudflare/quiche#1531]
In line https://github.com/cloudflare/quiche/blob/c484819eb2d047c730c0a7f7f215e6bec56d0b4c/apps/src/sendto.rs#L76 `copy_nonoverlapping` is being used to convert `std::time::Instant` into `libc::timespec`. This causes random issues, as sometimes the timespec is completely wrong.

When this code is run in a tokio vs mio runtime, the output in tokio is completely wrong, (but correct in mio), this is UB, and can cause issue in some edge case in mio also (maybe):
```rust
let mut time_spec = libc::timespec {
    tv_sec: 0,
    tv_nsec: 0,
};
unsafe {
    std::ptr::copy_nonoverlapping(
        &send_info.at as *const _ as *const libc::timespec,
        &mut time_spec,
        1,
    )
};
println!("send_at: {:?}, libc::time_spec: {:?}", send_info.at, time_spec);
```

In mio this outputs:
`send_at: Instant { tv_sec: 266052, tv_nsec: 781812960 }, libc::time_spec: timespec { tv_sec: 266052, tv_nsec: 781812960 }`

and tokio:
`send_at: Instant { tv_sec: 266164, tv_nsec: 695809709 }, libc::time_spec: timespec { tv_sec: 266164, tv_nsec: 139728866850477 }`

The `tv_nsec` being copied is wrong in tokio, that causes FQ to drop the packet without sending it (because of wrong timespec). A much safer way of doing this (even without unsafe code) would be:

```rust
let delay = send_info.at - std::time::Instant::now();
let now = nix::time::clock_gettime(nix::time::ClockId::CLOCK_MONOTONIC)
    .unwrap() +
    delay.into();
let mut time_spec = libc::timespec {
    tv_sec: 0,
    tv_nsec: 0,
};
time_spec.tv_sec = now.tv_sec();
time_spec.tv_nsec = now.tv_nsec();
```

Ofc this uses calls to `Instant::now` and `clock_gettime`, but it runs reliably and doesnt use pointer manipulation.

cc: @Noah-Kennedy

**Comment by ghedo** [comment]
Thanks for the report. We fixed a similar issue not too long ago (https://github.com/cloudflare/quiche/pull/1483) but missed this instance. I made https://github.com/cloudflare/quiche/pull/1532 to fix that as well.
