### ISSUE TITLE
max_ack_delay parameter?

### ISSUE THREAD

**Issue by ygina** [cloudflare/quiche#1538]
Hi! What is the `max_ack_delay` parameter used for? Is it the maximum amount of time that an endpoint can go without sending an ack? If so, can you point me to where in the code this is implemented? I seem to only be able to find where this value is used to estimate the RTT. Also, by default does quiche send acks on every other ack eliciting packet it receives, or on every packet? Also hoping someone can provide pointers on where this is implemented. :)

**Comment by junhochoi** [comment]
Check out https://datatracker.ietf.org/doc/html/rfc9002#section-a.3

**Comment by ygina** [comment]
I understand what `max_ack_delay` is intended to be used for, but I just want to confirm this feature isn't implemented in quiche, correct? None of these timers seem to be relevant: https://github.com/cloudflare/quiche/blob/master/quiche/src/lib.rs#L5425. Thanks.

**Comment by junhochoi** [comment]
AFAICT max_ack_delay parameter is considered in the rtt/timer calculation with ack_delay, such as https://github.com/cloudflare/quiche/blob/94a2640a941af513104feb6b4419059c04bd579c/quiche/src/recovery/mod.rs#L778 https://github.com/cloudflare/quiche/blob/94a2640a941af513104feb6b4419059c04bd579c/quiche/src/recovery/mod.rs#LL848C20-L848C20

> Also, by default does quiche send acks on every other ack eliciting packet it receives, or on every packet?

Currently quiche try to send an ACK frame for every ack-eliciting packets. (not every two) But note that it also behaves as described in https://www.rfc-editor.org/rfc/rfc9000#section-13.2.2-5

**Comment by ygina** [comment]
Thank you! That's what I was looking for.
