### ISSUE TITLE
Unable to use Datagram extension

### ISSUE THREAD

**Issue by nEghbal** [cloudflare/quiche#1548]
Hello,

I have build the following forked branch to test the unreliable datagram extension:

[https://github.com/cloudflare/quiche/tree/75c62c1fe97578173b74f16717a7fe9f2d34d5b0](url)

However, when I enable datagram for the http3_client example by using

quiche_config_enable_dgram(config, true, 2000000, 2000000);

It still shows **max_datagram_frame_size: None** in the output.

Also, when I changed the path of the requested resource in http3_client.c

.value = (const uint8_t *) "/dev/shm/eghbal/50kb",
                .value_len = sizeof("/dev/shm/eghbal/50kb") - 1,

It cannot see any difference in the sent data by server. 
BTW, how can I save/write the resource at the client side?

Thanks,
Nooshin

**Comment by LPardue** [comment]
Hi

The C apps are very basic examples to help concisely illustrate how to use the API, which probably explains the limitations that you are seeing. Developers should build more robust and advance applications that use these are a rough template.

> I have build the following forked branch to test the unreliable datagram extension:
> 
> [https://github.com/cloudflare/quiche/tree/75c62c1fe97578173b74f16717a7fe9f2d34d5b0](url)

That's a version of quiche from over 2 years ago, can you use something more recent?

> 
> However, when I enable datagram for the http3_client example by using
> 
> quiche_config_enable_dgram(config, true, 2000000, 2000000);
> 
> It still shows **max_datagram_frame_size: None** in the output.

Who's output, the client or server?
> 
> Also, when I changed the path of the requested resource in http3_client.c
> 
> .value = (const uint8_t *) "/dev/shm/eghbal/50kb", .value_len = sizeof("/dev/shm/eghbal/50kb") - 1,
> 
> It cannot see any difference in the sent data by server. BTW, how can I save/write the resource at the client side?

What is the server and what response do you see? If you're using http3-server.c then it is hardcoded to send the simple string `byez\n`

http-client.c currently simply prints HTTP headers or data it recieves. If you want to write the object to e.g. a file, you'll need to write code that does that but that doesn't have anything to do with quiche itself.

**Comment by nEghbal** [comment]
> Hi
> 
> The C apps are very basic examples to help concisely illustrate how to use the API, which probably explains the limitations that you are seeing. Developers should build more robust and advance applications that use these are a rough template.
> 
> > I have build the following forked branch to test the unreliable datagram extension:
> > [https://github.com/cloudflare/quiche/tree/75c62c1fe97578173b74f16717a7fe9f2d34d5b0](url)
> 
> That's a version of quiche from over 2 years ago, can you use something more recent?

I chose that version because I thought that the newest version does not have an example using unreliable datagram extension. What is the latest version with an example of datagram?

> 
> > However, when I enable datagram for the http3_client example by using
> > quiche_config_enable_dgram(config, true, 2000000, 2000000);
> > It still shows **max_datagram_frame_size: None** in the output.
> 
> Who's output, the client or server?

client

> 
> > Also, when I changed the path of the requested resource in http3_client.c
> > .value = (const uint8_t *) "/dev/shm/eghbal/50kb", .value_len = sizeof("/dev/shm/eghbal/50kb") - 1,
> > It cannot see any difference in the sent data by server. BTW, how can I save/write the resource at the client side?
> 
> What is the server and what response do you see? If you're using http3-server.c then it is hardcoded to send the simple string `byez\n`
> 
> http-client.c currently simply prints HTTP headers or data it recieves. If you want to write the object to e.g. a file, you'll need to write code that does that but that doesn't have anything to do with quiche itself.

OK, I see.

**Comment by LPardue** [comment]
> I chose that version because I thought that the newest version does not have an example using unreliable datagram extension. What is the latest version with an example of datagram?

Using datagrams require implementing application layer changes that would add complexity to the examples, so we don't have those in the repository. That said, it shouldn't be to hard for others to use these APIs in building their own apps. But note that we intend to change the API soon to remove the HTTP/3 aspects and apps will need to read and write datagrams directly to the QUIC API; see https://github.com/cloudflare/quiche/pull/1291.

> 
> > > However, when I enable datagram for the http3_client example by using
> > > quiche_config_enable_dgram(config, true, 2000000, 2000000);
> > > It still shows **max_datagram_frame_size: None** in the output.
> > 
> > 
> > Who's output, the client or server?
> 
> client

Did you also enable datagram on the server? The settings advertises what the local endpoint is willing to receive. The print out is probably informing you of the remote endpoint's value.

**Comment by nEghbal** [comment]
"But note that we intend to change the API soon to remove the HTTP/3 aspects and apps will need to read and write datagrams directly to the QUIC API; see https://github.com/cloudflare/quiche/pull/1291."

Do you know that when it would be available to read/write datagrams directly in QUICHE API?

Also I have another question and the implementation of datagrams in QUICHE. Are datagrams counted in flow control or not? The RFC 9221 says that "DATAGRAM frames do not provide any explicit flow control signaling and do not contribute to any per-flow or connection-wide data limit."

Thanks.

**Comment by LPardue** [comment]
FYI #1291 was merged. The recommended way to send or receive datagrams is directly on the quiche layer via dgram_* functions e.g. https://docs.quic.tech/quiche/struct.Connection.html#method.dgram_send. The C API exposes all of these too.

Correct, datagrams are not flow controlled at the QUIC layer. However, the implementation has queues to store buffered datagrams for sending or receiver - apps con configure the maximum size of these queues.

**Comment by LPardue** [comment]
[client.rs](https://github.com/cloudflare/quiche/blob/master/quiche/examples/client.rs) and [server.rs](https://github.com/cloudflare/quiche/blob/master/quiche/examples/server.rs) are the simplest examples. You can strip out the HTTP code in them and replace with you own datagram stuff. You might want to use quiche-client.rs and quiche-server.rs as inspiration for more advanced features

**Comment by nEghbal** [comment]
Using DATAGRAMs, do you think that we can complete downloading the file **more** than one RTT sooner than using stream frames which are flow controlled if we do not care about the lost parts?

We can save up to one RTT because we do not need to wait for the retransmissions of the last window, but I am not sure about more than one RTT completion time reduction ...

**Comment by LPardue** [comment]
For an application using QUIC that cares about performance, flow control should never be allowed to be a bottleneck. So all you reduce down to is, can your download handle unrecoverable loss. Only you can answer these questions with real data.

**Comment by nEghbal** [comment]
What is the ACK ratio/rate for unreliable datagram? Is that different from the stream ACK ratio?

**Comment by LPardue** [comment]
Packets are acknowledged. Currently there should be no difference in ack rates based on packet contents.
