### ISSUE TITLE
`quiche_h3_accept` only exists in quiche.h?

### ISSUE THREAD

**Issue by ichordev** [cloudflare/quiche#1556]
`quiche.h` declares a function `quiche_h3_accept`: https://github.com/cloudflare/quiche/blob/master/quiche/include/quiche.h#L820
However, this function is not in quiche or quiche::h3's ffi.rs files, nor is a symbol for it exported in libquiche.so. Does this function really exist?

**Comment by ghedo** [comment]
Yes, you are right, I don't think that function ever existed. Probably a copy-paste error. I made https://github.com/cloudflare/quiche/pull/1558 to remove it.

Thanks for the report!

**Comment by ichordev** [comment]
Not a problem!
