### ISSUE TITLE
[Question] Localhost TLS certificate on QUIC connection

### ISSUE THREAD

**Issue by gatomod** [cloudflare/quiche#1582]
Hi, I'm new using this library and I never worked with TLS. I'm having some issues connecting into a server over QUIC.

It seems that QUIC client has some problems with TLS certificates. As I saw at other issues and documentation, at `quiche::connect`, the server field is needed to check the TLS certificates, but when using localhost I don't know why doesn't work. I created the certificates following the [Let's Encrypt localhost cert generation](https://letsencrypt.org/docs/certificates-for-localhost/#making-and-trusting-your-own-certificates) but I don't know what I'm doing wrong.

Could I share a test repo with my code? Actually I'm just trying the library and I think it would be better, I'm not sure if I'm explaining well.

Regards

**Comment by LPardue** [comment]
from your link:

> You can then configure your local web server with localhost.crt and localhost.key, and install localhost.crt in your list of locally trusted roots.

Most likely you need to ensure that the client will trust the private root you are using. If quiche isn't using the system trust store (on some platforms it doesn't) you can workaround that using the e.g. insecure `--no-verify` option of quiche-client

**Comment by gatomod** [comment]
Oh, I see. I was reading the messy client example and I noticed about the option `verify_peer`. I'm having a similar issue with AWS s2n_quic (it works fine, but it forces me to check the certificate), but that library doesn't looks to have some option for that.

Anyway, I'm still getting the `TlsFail` error, but I found that comes from the Connection `send` method.

**Comment by gatomod** [comment]
@LPardue sorry, I don't want to bother you, but I've been trying to create for 3 weeks a client-server that can share "hello world" between them, and I can't solve my undefined issue because there's not any useful resource, example or documentation, and all examples I find in GitHub are a fork of the messy one that gives Cloudflare. I thought that creating an issue could help me.

If you're busy I understand it perfectly, but at least I wait some useful response, if is not from you, from other. I have a test repo with the code, if you want it, ask me.
Thanks

**Comment by LPardue** [comment]
This is the second occasion you've called the example code messy. That isn't constructive to the discussion.

We use rustdoc extensively, so I'm not sure what your documentation comment is directed at. For convenience we host the docs at https://docs.quic.tech/ too, reported on the repo main page.

 I pointed you towards the --no-verify option, and if you'd have explore the `Config` structure API then you'd see the method https://docs.quic.tech/quiche/struct.Config.html#method.load_verify_locations_from_file method which would allow you pass in a location to a PEM file containing the CA you created following the Let's Encrypt instructions. Here's an example of making it work with the quiche-client - https://github.com/cloudflare/quiche/pull/1595

**Comment by gatomod** [comment]
Oh, I'm sorry for that, I'm just trying to learn something that I never seen and I'm a bit frustrated because I don't find nothing that can explain it well.

I'll try it when I'm free. Thanks
