### ISSUE TITLE
curl user reports timeouts on receiving response

### ISSUE THREAD

**Issue by icing** [cloudflare/quiche#1585]
As reported in https://github.com/curl/curl/issues/11644, curl with quiche v0.17.2 sometimes times out after sending a request to an NGINX server. There is a qlog file attached to the issue which might shed some light on what is going on.

Maybe we are holding it wrong in curl. Would appreciate if someone could take a look.

**Comment by icing** [comment]
Holding the qlog file agains the light and squinting my eyes, this looks like a broken UDP path where the server never acks any packets beyond the first one. Would you agree? Thanks.

**Comment by LPardue** [comment]
Looking at the supplied qlog, there is no handshake_done message being returned by the server. Not sure why that is happening. That indicates a problem in the server QUIC statemachinery rather than UDP.

**Comment by icing** [comment]
Thanks, @LPardue, will forward that to the reporter.

**Comment by junhochoi** [comment]
Looks like a simple url, you can try quiche-client to the nginx server to see if it can be isolated to quiche or curl.

**Comment by icing** [comment]
User reports that issue also happen for them with curl+ngtcp2. This strongly points to a server issue. 

Closing this, thanks for the help!
