### ISSUE TITLE
received invalid HTTP/3 headers while reading QUIC packets

### ISSUE THREAD

**Issue by Wauux** [cloudflare/quiche#1590]
Nginx error received invalid HTTP/3 headers while reading QUIC packets

Most requests are method POST

![image](https://github.com/cloudflare/quiche/assets/31003740/a05ca8b4-cbac-42d2-812d-985c9393c4b3)
![image](https://github.com/cloudflare/quiche/assets/31003740/4c83ccb1-26ef-4416-92de-7fc0a97b787d)

**Comment by LPardue** [comment]
Are you able to increase the log level? The debug or info levels should give more insight into why nginx has issues with these requests

**Comment by Wauux** [comment]
fix: config underscores_in_headers on;

**Comment by Wauux** [comment]
fix: config underscores_in_headers on;
