### ISSUE TITLE
Connection Migration Failed

### ISSUE THREAD

**Issue by Claireecf** [cloudflare/quiche#1601]
I'd like to inquire about the Connection Migration feature of QUIC in quiche client example. While downloading a large file, I noticed the connection was interrupted when I switched my internet connection. I used --enable-active-migration. Is there another configuration required, could you guide me on how to configure it?

**Comment by LPardue** [comment]
Hi. All that --enable-active-migration does is control the Transport Parameter that tells a peer migration _could_ work; see https://datatracker.ietf.org/doc/html/rfc9000#migration. However, to actually make it work, the applications need to do work themselves especially the client, which need to initiate migration. 

quiche-client includes a `--perform-migration` option to exercise basic migration features, but all it does is test the client switching to a different source port. This is too simple for the Internet connection switch you described. To make that work, a client application would need deeper hooks into the OS and network stack, which adds a fair amount of complexity. It's probably a bit too much complexity for quiche-client, which is intended to be a simple tool.

**Comment by Claireecf** [comment]
Thank you for your clarification. What I tried was using the quiche client example to inquire into a large webpage. After that, I manually switched to a different internet connection. I was under the impression that after switching the connection, the client would initiate the migration. Have I misunderstood this process?

**Comment by LPardue** [comment]
quiche-client is a simple tool that doesn't currently implement the complex logic required to detect network connectivity changes and migrate between networks. Adding support for doing that is low down the priority list.

**Comment by Claireecf** [comment]
Thank you for your explanation.

**Comment by Claireecf** [comment]
closed
