### ISSUE TITLE
Are dgrams subject to congestion control?

### ISSUE THREAD

**Issue by HaseebLUMS** [cloudflare/quiche#1625]
My understanding of the RFC 9221 is that datagrams are subject to congestion control (no flow control though). However, I see that datagrams do not respect the setting `quiche_config_set_initial_congestion_window_packets()`. 

I can see the streams changing their behavior according to the congestion window size but seems like this config does not apply to datagrams. 

So does quiche support congestion control for unreliable datagrams at all?

**Comment by LPardue** [comment]
Closing as answered
