### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by candrews** [cloudflare/quiche#163]
It's been a while since the last release and there have been some significant changes since then.

Could you please make a new release?

**Comment by ghedo** [comment]
So, the current plan is to create a new release sometimes in the next week. Though haven't quite decided yet if it's going to be another "alpha" or an actual stable release.

**Comment by ghedo** [comment]
After a slight delay, I released [v0.1.0](https://github.com/cloudflare/quiche/releases/tag/0.1.0) just now.

**Comment by candrews** [comment]
> After a slight delay, I released [v0.1.0](https://github.com/cloudflare/quiche/releases/tag/0.1.0) just now.

Thank you!

0.1.0 is now in Gentoo: https://packages.gentoo.org/packages/net-libs/quiche
