### ISSUE TITLE
Why is quiche responding with Urgency 1 and incremental true?

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#1642]
As per the RFC, the default urgency should be 3 and incremental flag should be set to false.

I am rendering a video with quiche server. 

Surprisingly for all the segments, quiche responds back with **u=1 and i flag.**

I was expecting to see u=3 in the response headers. Why is this happening? Please advice.

<img width="719" alt="Screenshot 2023-11-02 at 9 51 04 PM" src="https://github.com/cloudflare/quiche/assets/74215489/258b4a07-36df-4578-8728-3f3c8b860295">

**Comment by LPardue** [comment]
Your client is most likely sending a request priority. You can't trust any browser UI to render its actual request priority correctly. If you grab any form or more detailed logging, you can see what is actually being sent over the wire.

**Comment by Samy432** [comment]
Detailed logging from quiche server with RUST_LOG=trace or through wireshark? RUST_LOG is too big to iterate and it seems like it does not render these information. Any pointers to initiate the logging feature?

**Comment by LPardue** [comment]
Closing as no indication this is a quiche problem.
