### ISSUE TITLE
soname versioning

### ISSUE THREAD

**Issue by candrews** [cloudflare/quiche#165]
Currently, there's just the library file `libquiche.so`

It would be better if soname versioning was implemented so `libquiche.so` is a symlink to, for example, the actual library file named `libquiche.so.0.0.0`
The library should also have `DT_SONAME` set appropriately.

Could you please implement soname versioning?

**Comment by ghedo** [comment]
Again something that cargo doesn't support https://github.com/rust-lang/cargo/issues/5045

**Comment by ghedo** [comment]
in the cargo ticket above it was suggested to use the [cdylib-link-lines](https://crates.io/crates/cdylib-link-lines) crate, which supposedly would set the SONAME in the dynamic library. Though I don't know if it also renames the .so file accordingly.

I'll have a look once I have a bit of time.
