### ISSUE TITLE
chrome does not trust custom certificates for quic

### ISSUE THREAD

**Issue by haohaoCD** [cloudflare/quiche#1686]
I have written an HTP3 service using Quiche, which loads a custom certificate that has been added to the system certificate repository. However, when accessing this service using Chrome and using Wireshark to capture packets, it will display an issue of certificate distrust. Has anyone encountered this issue before and how can we solve it
![微信截图_20231213104207](https://github.com/cloudflare/quiche/assets/128157421/2755dc77-ea80-4e88-ab60-24c0f9971343)

**Comment by LPardue** [comment]
This is a chrome issue; see https://www.chromium.org/quic/playing-with-quic/ for more information.
