### ISSUE TITLE
When should `h3::Connection.poll` be called?

### ISSUE THREAD

**Issue by ghost** [cloudflare/quiche#1700]
Obviously, when `h3::Connection.poll` returns Done, we need to wait for something to happen and then call it again. The question is, what exactly do we need to wait for?

**Comment by LPardue** [comment]
`poll()` processes received transport layer stream data, so the ideal time to call it is after receiving a flight of QUIC packets e.g. reading a batch of UDP datagrams and then processing them with quiche::connection::recv

**Comment by LPardue** [comment]
I've answered the original question, not really sure what more you're looking for.

**Comment by LPardue** [comment]
The general principle is that the transport layer always needs to be driven with regularity. Receiving packets will update internal quiche state, so really that is the ideal time to try any APIs that would insert into/pull from the transport layer, or expose information such as is_established.

Timeout values are updated internally and are likely to be recalculated when packets are received. On_timeout does nothing if it is called too early. Its more optimal to cancel and recreate a timeout tiner but nothing bad would happen it multiple were to fire (caveat that on_timeout *does* need to be called, ideally as soon as it expires).
