### ISSUE TITLE
failed to run custom build command for `quiche v0.20.0 (/root/quiche/quiche)`

### ISSUE THREAD

**Issue by goheader** [cloudflare/quiche#1706]
when I Getting Started, I occured a error. 

[root@localhost apps]# cmake --version
cmake version 2.8.12.2
[root@localhost apps]# which cmake
/usr/bin/cmake
[root@localhost apps]# 

[root@localhost apps]# cargo run --bin quiche-client -- https://cloudflare-quic.com/
   Compiling quiche v0.20.0 (/root/quiche/quiche)
error: failed to run custom build command for `quiche v0.20.0 (/root/quiche/quiche)`

Caused by:
  process didn't exit successfully: `/root/quiche/target/debug/build/quiche-ecbac9205f9349c1/build-script-build` (exit status: 101)
  --- stdout
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: cd "/root/quiche/target/debug/build/quiche-bfbc9eea1708d135/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/root/quiche/quiche/deps/boringssl" "-DCMAKE_INSTALL_PREFIX=/root/quiche/target/debug/build/quiche-bfbc9eea1708d135/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /root/quiche/target/debug/build/quiche-bfbc9eea1708d135/out/build
  running: cd "/root/quiche/target/debug/build/quiche-bfbc9eea1708d135/out/build" && MAKEFLAGS="-j --jobserver-fds=7,8 --jobserver-auth=7,8" "cmake" "--build" "." "--target" "ssl" "--config" "Debug"
  gmake: *** No rule to make target 'ssl'.  Stop.

  --- stderr
  thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/cmake-0.1.50/src/lib.rs:1098:5:

  command did not execute successfully, got: exit status: 2

  build script failed, must exit now
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by goheader** [comment]
All right, I figure out why make error. 
I just use git clone https://github.com/cloudflare/quiche.git. 
I should use 
git clone --recursive https://github.com/cloudflare/quiche.git

**Comment by goheader** [comment]
closed

**Comment by ChessNineeee** [comment]
damn, have been trapped in the dependency problem of boringssl for a long time, ur solution works
