### ISSUE TITLE
Encoding payload with protobuf clashes with the protocol

### ISSUE THREAD

**Issue by ETisREAL** [cloudflare/quiche#1709]
Hello :) Hope to find you well.

I have this client that is encoding a payload using protobuf and that is trying to send the content to a receiver (duh)

This is the client code: 

``` rust
fn client_connect(client_addr: SocketAddr, peer: SocketAddr, config: &mut quiche::Config) -> Result<(), Box<dyn Error>> {
    let socket = UdpSocket::bind(client_addr).map_err(|err| {
        eprintln!("err binding to socket: {}", err);
        Box::new(err)
    })?;

    let scid = [0; quiche::MAX_CONN_ID_LEN];
    let scid = quiche::ConnectionId::from_ref(&scid);

    let mut conn = quiche::connect(None, &scid, socket.local_addr().unwrap(), peer, config)
    .map_err(|err| {
        eprintln!("error connecting: {}", err);
        Box::new(err)
    })?;
    println!(
        "connecting to {:} from {:} with scid {:?}",
        peer,
        socket.local_addr().unwrap(),
        scid,
    );

    println!("active cids: {:?}", conn.active_source_cids());
    println!("protos: {:?}", conn.application_proto());
    println!("certs: {:?}", conn.peer_cert());

    // Construct a sample request payload
    let request = payload::Request {
        fiber_id: "1201984012394812039898203989822039898039898203989847321".to_string(),
        fiber_ip: "192.168.1.1".to_string(),
    };
    // Serialize the request using Protobuf
    let mut encoded_req = request.encode_to_vec();
    let mut out_slice = encoded_req.as_mut_slice();
    println!("bytes len {}", out_slice.len());

    let (write, send_info) = match conn.send(&mut out_slice) {
        Ok(res) => (res.0, res.1.to),
        Err(quiche::Error::Done) => (out_slice.len(), peer),
        Err(err) => {
            return Err(Box::new(err));
        },
    };
    println!("write: {}", write);

    // while let Err(e) = socket.send_to(&out_slice, peer) {
    while let Err(e) = socket.send_to(&out_slice[..write], send_info) {
        if e.kind() == std::io::ErrorKind::WouldBlock {
            eprintln!(
                "{} -> {}: send() would block",
                socket.local_addr().unwrap(),
                // send_info.to
                peer
            );
            continue;
        }
    
        return Err(Box::new(e));
    }
    
    Ok(())
}
```

for reference, here is also the receiving code:

``` rust
fn server_connect(local: SocketAddr, config: &mut quiche::Config) -> Result<(), Box<dyn Error>> {
    let socket = UdpSocket::bind(local)?;
    let to = socket.local_addr()?;
    println!("server binded to {:?}", to);
    
    loop {
        let mut buf = [0; 65535]; // Default max datagram size
        let (read, from) = socket.recv_from(&mut buf)?;
        println!("read: {}", read);
        
        // Assuming read contains the received bytes as a Bytes object
        match payload::Request::decode(prost::bytes::Bytes::copy_from_slice(&buf[..read])) {
            Ok(request) => {
                // Handle the received Request struct
                println!("Received Request: {:?}", request);
            }
            Err(error) => {
                // Handle the decoding error
                println!("Error decoding Request: {:?}", error);
            }
        }

        let mut conn = quiche::accept(&ConnectionId::from_vec(vec![10]), None, local, from, config)?;

        let recv_info = quiche::RecvInfo { from, to };

        match conn.recv(&mut buf[..read], recv_info) {
            Ok(v) => println!("bytes {}", v),
            Err(err) => {
                eprintln!("error receiving connection: {:?}", err);
                return Err(Box::new(err))
            },
        };
    }
}

```

Here are the issues I am having and despite reading through all the docs and examples I can't get function properly:

1. If the payload is too small (circa below the 70 bytes) the send function return the error variant Done. As you can see from the code, I tried to circumvent this case by 'manually' setting the buffer length and the SocketAddr to send to, however on the receiving end, this still results in a 'BufferTooShort' error. So how does one properly handle small payloads?
2. If the payload is long enough to fill the buffer, then on the receiving end, when I try to decode the request payload, I get another error ('invalid wire type value: 6' ) related to protobuf decoding. But I have zero clue of what might be going wrong here. All I know, is that if I remove the QUIC layer (ie just use a raw UDP protocol) on the receiving end I can decode the message just fine

It could very well be ignorance on my side, but I'm quite new to HTTP3 in general, so please have mercy :)
If you need any more context or anything, of course just let me know.
Any help is greatly appreciated :)

**Comment by LPardue** [comment]
Application data is sent on streams or datagrams, so you need to use the related functions to buffer that data into quiche before preparing packets used conn.send(). You current code is just blattong over the top of your serilized protobuf object.  Similar on the receive side

**Comment by LPardue** [comment]
But also there's a lot of packet exchange required to bring up a connection. So if this is the full extent of the code, you'll have other issues. The exple apps give an idea of everything that's required.

**Comment by ETisREAL** [comment]
Thank you @LPardue for the prompt response. Will dig a little deeper in the example code then. Without taking any more of your time, could you please just mention a couple of this buffering functions? Simply so I get a little more order in my head
