### ISSUE TITLE
Is the chromium project using cloudflare quiche as their HTTP3 implementation? 

### ISSUE THREAD

**Issue by LifeIsStrange** [cloudflare/quiche#176]
https://quiche.googlesource.com/quiche/
Say that quiche is the http3 implementation of Google.
So is this a very weird name clash or are you collaborating and mutualising work force for creating the best possible implementation?

**Comment by ghedo** [comment]
No, that's a different implementation. Just an unfortunate coincidence that they have the same name.

**Comment by LifeIsStrange** [comment]
@ghedo you should consider to rename your implementation.
Otherwise it will create a lot of confusion and also mistakes on e.g stackoverflow.com

**Comment by ghedo** [comment]
We are not going to rename our porject. We started using the name publicly first.

**Comment by LifeIsStrange** [comment]
@ghedo being the first or second with the name is something that is inconsequential, it's a weak argument.
You found that name and Google made the mistake to take it when it was already taken, okay. 
But if we look at what matters, that is : real world consequences:
Google quiche is going to be order of magnitude more used than cloudflare quiche.
This means at least two negative consequences:
The first is, if someone is talking about quiche on internet, some people will think he talk about Google, and others (a minority) will think he talk about cloudflare. 
The second negative consequence is really the obvious one that should make you change your mind about renaming:
Cloudflare quiche users will—as everybody—ask and read questions about quiche on stackoverflow.com 
They will be confused and disappointed to find Google quiche answers. They might take and waste time before understanding the confusion. 
Secondly, Google quiche users will have the same cognitive pollution on stackoverflow.com.
Those arguments should outweight the almost non existant drawback of renaming cloudflare quiche if you honestly quantify it.

The final decision is yours.

**Comment by LPardue** [comment]
Over the years, there have been various official and unofficial projects that package the Chromium source code. The most relevant to this discussion is `proto-quic`, the precursor to Google's QUICHE. That rename has already caused some friction.

It is important also to reflect on how the project name relates to the project API. Cloudflare quiche exports its name in the API, so any name change has a real impact to upstream projects that use our library both in the Rust ecosystem and C ecosystem (e.g. libcurl and curl).
