### ISSUE TITLE
Failed to build dynamic library on macOS in arm64

### ISSUE THREAD

**Issue by microhardsmith** [cloudflare/quiche#1801]
It seems quiche failed to build dynamic library on macOS in arm64, x64 were not tested by me.

When using `cargo build --release --features ffi` on windows/x64 and linux/x64, the dynamic library works fine, but on macOS/arm64, there seems to be no dynamic symbol table exported:

![921200d5df302a5fbd65a5467703c0d2](https://github.com/cloudflare/quiche/assets/19500634/e8708a97-1f29-4e63-9f73-010238a3c5e3)

**Comment by junhochoi** [comment]
https://stackoverflow.com/questions/60794258/dynamic-symbol-table-in-mac-dynamic-libraries

It works for me:
``nm -gU libquiche.dylib | head
0000000000041d34 T _quiche_accept
0000000000041740 T _quiche_config_discover_pmtu
0000000000041944 T _quiche_config_enable_dgram
0000000000041758 T _quiche_config_enable_early_data
0000000000041928 T _quiche_config_enable_hystart
0000000000041930 T _quiche_config_enable_pacing
00000000000419d4 T _quiche_config_free
0000000000041738 T _quiche_config_grease
00000000000414fc T _quiche_config_load_cert_chain_from_pem_file
0000000000041588 T _quiche_config_load_priv_key_from_pem_file
```

**Comment by microhardsmith** [comment]
> Probably need to use another option? See the following: https://stackoverflow.com/questions/60794258/dynamic-symbol-table-in-mac-dynamic-libraries
> 
> It works for me:
> 
> ```
> nm -gU libquiche.dylib | head
> 0000000000041d34 T _quiche_accept
> 0000000000041740 T _quiche_config_discover_pmtu
> 0000000000041944 T _quiche_config_enable_dgram
> 0000000000041758 T _quiche_config_enable_early_data
> 0000000000041928 T _quiche_config_enable_hystart
> 0000000000041930 T _quiche_config_enable_pacing
> 00000000000419d4 T _quiche_config_free
> 0000000000041738 T _quiche_config_grease
> 00000000000414fc T _quiche_config_load_cert_chain_from_pem_file
> 0000000000041588 T _quiche_config_load_priv_key_from_pem_file
> ```

Thanks for your help, it turns out `nm -gU` should be the right usage on macOS for dynamic library symbol lookup, closing this issue now.
