### ISSUE TITLE
Bug: Bodies longer than 8KB fail to send

### ISSUE THREAD

**Issue by catid** [cloudflare/quiche#1821]
Using the C API I modified the server C example like this:

```
                        const int body_bytes = 16 * 1024;
                        uint8_t* body_data = malloc(body_bytes);
                        for (int i = 0; i < body_bytes; i++) {
                            body_data[i] = (uint8_t)'A';
                        }

                        quiche_h3_send_body(conn_io->http3, conn_io->conn,
                                            s, body_data, body_bytes, true);

                        free(body_data);
```

This adds 16KB of data instead of a simple test provided in the repo.

This reproduces a bug I was seeing in my C++ code based on quiche.  My goal is to use quiche for file transfer but it seems to be non-functional on latest master.

**Comment by catid** [comment]
I tried calling quiche_h3_send_body() twice with 8KB data, and that also fails.  So it seems to be the body length that causes the bug.  Only 8KB works but 16KB does not.

**Comment by catid** [comment]
The same bug also happens with the non-H3 example server/client:

```
                if (fin) {
                    const int body_bytes = 16 * 1024;
                    uint8_t* body_data = malloc(body_bytes);
                    for (int i = 0; i < body_bytes; i++) {
                        body_data[i] = (uint8_t)'A';
                    }

                    uint64_t error_code;
                    quiche_conn_stream_send(conn_io->conn, s, body_data,
                                            body_bytes, true, &error_code);

                    free(body_data);
                }
```

In this part, 8KB works but 16KB fails.

**Comment by catid** [comment]
However, the Rust example appears to work fine, so it is a bug in the FFI C API layer.  I'm able to transfer 9MB files using quiche-server and quiche-client.

**Comment by LPardue** [comment]
The C API doesnt have its own docs, but maps pretty much 1 to 1 withe the Rust API, so see https://docs.quic.tech/quiche/struct.Connection.html#method.stream_send about write limits and how to deal with them.

Effectively you'll need to flush the packets out, then read received packets in ordercto get more capacity.

**Comment by catid** [comment]
Ah got it the API is returning the number of bytes it was able to write, and I need to buffer up the rest for later.  No problem.
