### ISSUE TITLE
Congestion avoidance other than Reno?

### ISSUE THREAD

**Issue by link2xt** [cloudflare/quiche#183]
Line https://github.com/cloudflare/quiche/blob/d646a60b497be4a92046fbd705161164388b73d2/src/recovery.rs#L505 seems to implement Reno congestion avoidance. Are there any plans to implement CUBIC or BBR?

**Comment by junhochoi** [comment]
Currently quiche implements QUIC recovery darft which specifies NewReno equivalent. We have a plan to add more congestion control algorithms.
