### ISSUE TITLE
Macros in src/octet.rs may have unexpected unsafe behavior

### ISSUE THREAD

**Issue by alex** [cloudflare/quiche#184]
https://github.com/cloudflare/quiche/blob/d646a60b497be4a92046fbd705161164388b73d2/src/octets.rs#L69-L73

https://github.com/cloudflare/quiche/blob/d646a60b497be4a92046fbd705161164388b73d2/src/octets.rs#L99-L103

These both evaluate some of their parameters in an `unsafe` block. This allows the callers of these macros to use an unsafe expression there, without needing to specify an `unsafe` block.

This is almost always unintended (and indeed, there's no comments suggesting it was intended). I'd suggest doing `let len = $len;` outside of the `unsafe` block to avoid this.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=578b803a28085939cd5a4791a4fb4dd4 is an example of how this can fail.

**Comment by LPardue** [comment]
Thanks for the report and the example. I've prepared a PR to address this: https://github.com/cloudflare/quiche/pull/185
