### ISSUE TITLE
Error when running on windows

### ISSUE THREAD

**Issue by TimonPost** [cloudflare/quiche#207]
```
--- stderr
CMake Error at C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Perl (missing: PERL_EXECUTABLE)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.15/Modules/FindPerl.cmake:76 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:38 (find_package)
```

When I try to use this library and then run `cargo build` I get this error. Why does it mention Perl? And is it possible to use this only with rust, or do I need extern C libraries?

- I use windows, haven't configured anything yet.

```rust
fn main() {

}

fn client() {
    let mut config = quiche::Config::new(quiche::PROTOCOL_VERSION)?;
    let server_name = "quic.tech";
    let scid = [0xba; 16];
    let mut conn = quiche::connect(Some(&server_name), &scid, &mut config)?;

    loop {
        let mut buf = vec![0;500];

        let write = match conn.send(&mut buf) {
            Ok(v) => v,
            _ => break
        };

        println!("written bytes {:?}", write);
    }
}

fn server() {
    let mut config = quiche::Config::new(quiche::PROTOCOL_VERSION)?;
    let scid = [0xba; 16];
    let mut conn = quiche::accept(&scid, None, &mut config)?;

    loop {
        let read = conn.recv(&mut buf).unwrap();
        let received = &mut buf[..read];
        println!("{:?}", received);
    }
}
```

**Comment by LPardue** [comment]
Hi @TimonPost!

Quiche has some dependencies, the heaviest one is BoringSSL. From our readme:

> Note that BoringSSL, which is used to implement QUIC's cryptographic handshake based on TLS, needs to be built and linked to quiche. This is done automatically when building quiche using cargo, but requires the cmake and go commands to be available during the build process.

So this explains why you see an error when just running `cargo build` - quiche is trying to build BoringSSL and that is failing due to missing prerequisites.

Unfortunately, setting up the environment is a bit harder on Windows than Linux but it is achievable. Here's a checklist of things you need, but I encourage you to check out the [more detailed instructions for building BoringSSL](https://github.com/google/boringssl/blob/master/BUILDING.md): 

- CMake
- Go
- Perl
- [NASM](https://www.nasm.us/)

**Comment by TimonPost** [comment]
Thanks for the 'quic' answer and the instructions ;). Maybe it is asked before, but is there a reason why rustls isn't used for this? It supports TLS 1.3 and it is pure rust.

**Comment by LPardue** [comment]
No problem. I have been meaning to update the docs to aid Windows devs, so I just opened #208. Please let us know when you have successfully built quiche.

As for rustls, please see https://github.com/cloudflare/quiche/issues/129.

**Comment by TimonPost** [comment]
Great, thanks for the help!
