### ISSUE TITLE
Dependence Android minSdkVersion little higher

### ISSUE THREAD

**Issue by chenwq-bjtu** [cloudflare/quiche#215]
Hi gays:
Our app minSdkVersion is 16,  but libquiche depends on minSdkVersion is 21.
I can not compile my App with libquiche. 
Could you please modify it to support minSdkVersion 16? 
 Because some  customers may also use the phone of lower android sdk.
Thank you!

![image](https://user-images.githubusercontent.com/22881484/66700614-11388380-ed25-11e9-818f-37329bfc7d0c.png)

**Comment by junhochoi** [comment]
Current min API 21 is coming from where for aarch64 (arm64) platform we need API 21 or higher. Also `ring` library used in quiche requires API 18 or higher for build in non-aarch64 android. Also note that boringssl is tested on API 21 too.

Previously I tried building quiche with API level 16 but no luck (ring fails to build) I think you may build with API level 18 with arm or armv7, but never well tested.

**Comment by chenwq-bjtu** [comment]
OK， I  know，thank you。I  compiled libquiche for armv7 before，now it seems not impossible with API lower then 18。-------- 原始邮件 --------发件人： Junho Choi <notifications@github.com>日期： 2019年10月13日周日 01:00收件人： cloudflare/quiche <quiche@noreply.github.com>抄送： chenwq-bjtu <cwq0202@163.com>, Author <author@noreply.github.com>主    题： Re: [cloudflare/quiche] Dependence Android minSdkVersion little higher (#215)Current min API 21 is coming from where for aarch64 (arm64) platform we need API 21 or higher. Also ring library used in quiche requires API 18 or higher for build in non-aarch64 android. Also note that boringssl is tested on API 21 too.
Previously I tried building quiche with API level 16 but no luck (ring fails to build) I think you may build with API level 18 with arm or armv7, but never well tested.
