### ISSUE TITLE
win10 Lib.rs exception

### ISSUE THREAD

**Issue by freebufdaolang** [cloudflare/quiche#225]
<img width="935" alt="error" src="https://user-images.githubusercontent.com/30312004/66923955-54179580-f05c-11e9-8405-f0787e6a2265.PNG">

**Comment by ghedo** [comment]
It's not at all clear from the screenshot what the problem is. Please provide more details.

**Comment by freebufdaolang** [comment]
I have solved it.
Code coding problem
your code
`struct conn_io* conn_io =(struct conn_io*) malloc(sizeof(*conn_io));`
but i like
`struct conn_io* conn_io =(struct conn_io*) `malloc(sizeof(conn_io));`
So the memory overflows.
I modify the code
`struct CONN_IO* conn_io =(struct CONN_IO*) malloc(sizeof(*CONN_IO));`
that‘s ok now
