### ISSUE TITLE
Don't suggest enabling TLS <1.2

### ISSUE THREAD

**Issue by sweepyoface** [cloudflare/quiche#226]
As the title says, allowing any TLS version below v1.2 (in the README) is a security risk.

**Comment by junhochoi** [comment]
Thank you for your suggestion. Here we only provide a basic example for enabling http3.
For recommended SSL configuration including cipher configuration and other patches please see https://github.com/cloudflare/sslconfig

**Comment by sweepyoface** [comment]
I don't understand this response. Just because the recommended config is elsewhere doesn't mean this example shouldn't (easily) align with good security practices.
