### ISSUE TITLE
Build fails on Alpine Linux

### ISSUE THREAD

**Issue by githubcdr** [cloudflare/quiche#227]
Hi,

I noticed the following error when building on Alpine Linux;

$ cargo build --examples
~~~
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/ring-0.16.9/src/lib.rs:69:1
   |
69 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ring`.

Is this related to Rust version? Or a bug?


Regards,

**Comment by junhochoi** [comment]
Please make sure you are using `rustc` 1.38 or later. You can check by 

```$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23)
```

**Comment by ghedo** [comment]
This seems like a problem with the Rust version, quiche requires 1.38 to build. Can you please show the output of the `rustc -V` and `cargo -V` commands?

**Comment by githubcdr** [comment]
Thanks for the quick response! Using "testing" repo on Alpine Linux works now!

**Comment by githubcdr** [comment]
Forgot to share my work, I created a Docker image based on Alpine Linux with HTTP3 / QUIC support.

https://github.com/githubcdr/docker-nginx-brotli

**Comment by Vndroid** [comment]
Hey, According to https://github.com/cloudflare/quiche#building. I noticed that the Rust version has been changed to 1.39 or later. So I can not Compile on Alpine. The Alpine edge branch version is 1.38. How to solve this problem?

**Comment by junhochoi** [comment]
You may take a look at our Dockerfile in the repo: https://github.com/cloudflare/quiche/blob/master/examples/Dockerfile. Please open a new issue if this need more discussion.
