### ISSUE TITLE
HTTP/3 patch bugs with h2load HTTP/2 benchmark tests ?

### ISSUE THREAD

**Issue by centminmod** [cloudflare/quiche#228]
I might have found a bug doing h2load HTTP/2 tests 

* Nginx 1.16.1 with Cloudflare HTTP/3 patch with dual RSA 2048bit + ECDSA 256bit SSL certificates configured seems to fail on most RSA cipher tests and only pass when h2load testing against ECDSA ?? [Raw h2load results here](https://gist.github.com/centminmod/7b09a760549e10c971f681cfb370341f/raw/ef50e03356fb8625c5029921434a57d03bfab1f3/nginx-1.16.1-results.md).
* Using normal Nginx 1.17.4 without HTTP/3 patch, both RSA and ECDSA cipher tested h2load HTTP/2 tests pass fine. [Raw h2load results here](https://gist.github.com/centminmod/7b09a760549e10c971f681cfb370341f/raw/ef50e03356fb8625c5029921434a57d03bfab1f3/nginx-1.17.4-results.md)
* Nginx HTTP brolti encoded requests via h2load nearly all fail on Nginx 1.16.1 with CF HTTP/3 patch too using Google's ngx_brotli nginx module.
* Or might be h2load bug as when I specify specific --ciphers fails

```
h2load -t1 --ciphers=ECDHE-RSA-AES128-GCM-SHA256 -H 'Accept-Encoding: gzip' -c100 -n1000 https://http2.domain.com/
starting benchmark...
spawning thread #0: 100 total client(s). 1000 total requests

finished in 6.67ms, 0.00 req/s, 0B/s
requests: 1000 total, 0 started, 0 done, 0 succeeded, 1000 failed, 1000 errored, 0 timeout
status codes: 0 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 0B (0) total, 0B (0) headers (space savings 0.00%), 0B (0) data
                     min         max         mean         sd        +/- sd
time for request:        0us         0us         0us         0us     0.00%
time for connect:        0us         0us         0us         0us     0.00%
time to 1st byte:        0us         0us         0us         0us     0.00%
req/s           :       0.00        0.00        0.00        0.00   100.00%
```
not specifying it passes as it's preferencing ECDSA SSL cert in nginx dual RSA + ECDSA SSL cert config.
```
h2load -t1 -H 'Accept-Encoding: gzip' -c100 -n1000 https://http2.domain.com/                                      
starting benchmark...
spawning thread #0: 100 total client(s). 1000 total requests
TLS Protocol: TLSv1.2
Cipher: ECDHE-ECDSA-AES128-GCM-SHA256
Server Temp Key: ECDH P-256 256 bits
Application protocol: h2
progress: 10% done
progress: 20% done
progress: 30% done
progress: 40% done
progress: 50% done
progress: 60% done
progress: 70% done
progress: 80% done
progress: 90% done
progress: 100% done

finished in 91.50ms, 10929.08 req/s, 25.08MB/s
requests: 1000 total, 1000 started, 1000 done, 1000 succeeded, 0 failed, 0 errored, 0 timeout
status codes: 1000 2xx, 0 3xx, 0 4xx, 0 5xx
traffic: 2.29MB (2405900) total, 274.41KB (281000) headers (space savings 24.05%), 2.00MB (2102000) data
                     min         max         mean         sd        +/- sd
time for request:     1.02ms     19.33ms      3.83ms      3.57ms    94.90%
time for connect:    34.17ms     56.90ms     45.53ms      9.83ms    51.00%
time to 1st byte:    53.50ms     60.16ms     56.97ms      2.20ms    58.00%
req/s           :     111.42      133.51      119.43        6.19    67.00%
```
but don't have problems with unpatched version or maybe Nginx 1.17.4 vs 1.16.1 related?

**Comment by ghedo** [comment]
Have you tried unpatched 1.16.1? Also, what's the NGINX configuration?

**Comment by centminmod** [comment]
Each Nginx configuration is linked in raw h2load results links above. 

But I think I recall now why it is failing. Nginx dual RSA + ECDSA SSL certificated support which was added in Nginx 1.11 only works with OpenSSL. It doesn't work with BoringSSL built Nginx. I totally forgot about this LOL. Silly me 😊 

So it isn't a bug just Nginx doesn't support dual SSL certificates when built against BoringSSL !

**Comment by LPardue** [comment]
Its sounds like this is not an issue with quiche or the H3 patch, so I'm going to close this.

**Comment by centminmod** [comment]
Yeah sorry for the flash alert 😊

**Comment by splitice** [comment]
@centminmod have you thought about applying the pending patches to OpenSSL and trying that?
