### ISSUE TITLE
How to update to new version?

### ISSUE THREAD

**Issue by JWPapi** [cloudflare/quiche#229]
I’m trying to install nginx1.16.1 on a testserver to test http/3. I have already built, compiled and installed it, but my server is still running the old version. How do I change the nginx version it is using?

**Comment by junhochoi** [comment]
Please check `nginx -V` output and it includes `--with-http_v3_module`. Otherwise you need to check if nginx is properly patched and installed in a location you specified.

**Comment by JWPapi** [comment]
I already know that it’s not 1.16.1 but the 1.16.0.4 that came with the bitnami nginx version. So I’m not sure were I shall define which nginx version my system is using. If I just use the conf of the pached version it will error, because it does not have quiche and in general it’s not running the patched version. If I change the path in my ctlscript.sh, that doesn’t change the version I’m using with the nginx command. So I wonder where do I configure the nginx version my server is using...

Currently it is using one in a custom bintami location and not the one in `/usr/local/` which is th default nginx path

**Comment by junhochoi** [comment]
Not sure what bitnami nginx is based on, but please note that you need to build nginx from the source as in our README. If you have any build issue with our nginx+quiche patch please post here again.
