### ISSUE TITLE
Throughput issue at high latency

### ISSUE THREAD

**Issue by royap** [cloudflare/quiche#231]
Quiche via Nginx 1.16.1 does not seem to handle high latency well. Please see the below results using WAN emulation. 

Test HTTPs file: 8GB Linux ISO

Quiche/Nginx
```
100mbps, 0ms, 0% packet loss - 100mbps
100mbps, 200ms, 0% packet loss - 80mbps
100mbps, 200ms, 0.2% packet loss - 1.2Mbps (peak 1.5mbps)
```
LiteSpeed Web Server
```
100mbps, 0ms, 0% packet loss - 100mbps
100mbps, 200ms, 0% packet loss - 100mbps
100mbps, 200ms, 0.2% packet loss - 3.3Mbps (peak 30mbps)
```

Client: Windows 10 - Google Chrome 80.0.3946.0 (Official Build) canary (64-bit)
`chrome.exe --no-proxy-server --enable-quic --quic-version=h3-23 --origin-to-force-quic-on=TLD.net:443 https://TLD.net`

Server: Ubuntu 19.04 - Linux 5.0.0-32-generic
Nginx config 
 ```
server {
        # Enable QUIC and HTTP/3.
        listen 443 quic reuseport;
        # Enable HTTP/2 (optionl).
        listen 443 ssl http2;
        ssl_certificate      /etc/nginx/conf/domain.crt;
        ssl_certificate_key  /etc/nginx/conf/domain.rsa;
        # Enable all TLS versions (TLSv1.3 is required for QUIC).
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        # Add Alt-Svc header to negotiate HTTP/3.
        add_header alt-svc 'h3-23=":443"; ma=86400';
    }
```
LiteSpeed Web Server 5.4.2
```
Enable QUIC: Yes
TLS: 1.3
Congestion Control:BBR
```

**Comment by junhochoi** [comment]
Thanks for testing. I think LiteSpeed is using BBR which can be aggressive with loss and can ramp up more quickly when Reno which quiche implements right now (as specified in the draft), which explains the result. We will continue to optimize our implementation and add more congestion control in the future. We will come back to more perf testing in the future. Thanks.

**Comment by VMatrix1900** [comment]
You can try to increase the UDP buffer.
