### ISSUE TITLE
Uncommon failure of QUIC session when testing with no HTTP/2 fallback

### ISSUE THREAD

**Issue by royap** [cloudflare/quiche#232]
Uncommon failure of QUIC session when testing with no HTTP/2 fallback using Chrome. The issue does not occur often but restarting Nginx solve the issue. 
`Chrome.exe --no-proxy-server --enable-quic --quic-version=h3-23 --origin-to-force-quic-on=TLD.net:44`

Please see the attached QUIC trace logs of a working and failed session for the same nginx server and URL path.
[working.txt](https://github.com/cloudflare/quiche/files/3748999/working.txt)
[failed.txt](https://github.com/cloudflare/quiche/files/3749000/failed.txt)

**Comment by junhochoi** [comment]
failed.txt seems like Chrome sent a quic initial packet but getting no response. (but working.txt it looks fine) How easy is it to reproduce? Also when Chrome is not responding, can you try other client (e.g. http3-client included in quiche, or curl + quiche) to reproduce?

**Comment by ghedo** [comment]
Closing as there was no reply for over a month. We can reopen later if the reporter comes back.
