### ISSUE TITLE
Nginx configures multiple sites to share 443/udp ports

### ISSUE THREAD

**Issue by xmapst** [cloudflare/quiche#236]
```
root@master conf 18:30:35 # pwd
/usr/local/nginx/conf
root@master conf # grep -n quic nginx.conf
177:        listen      443 quic    reuseport;
248:        listen      443 quic    reuseport;
root@master conf # nginx -t               
nginx: [emerg] duplicate listen options for 0.0.0.0:443 in /usr/local/nginx/conf/nginx.conf:248
nginx: configuration file /usr/local/nginx/conf/nginx.conf test failed
```
### **_Is this a bug?_**

**Comment by junhochoi** [comment]
Can you post a full nginx.conf?

**Comment by centminmod** [comment]
AFAIK reuseport option is only to be used once per ip/port pairing in normal circumstances. I'd assume it's same with quic listen directive too.

**Comment by xmapst** [comment]
@junhochoi The configuration file is too long and is not easy to publish

**Comment by xmapst** [comment]
@junhochoi @centminmod 
The key configuration files are as follows
```
  ……..

  server {
        listen      443 ssl     http2;
        # Enable QUIC and HTTP/3.
        listen      443 quic    reuseport;

        server_name www.aaaaa.com;

        ssl_certificate      xxx.crt;
        ssl_certificate_key  xxx.key;
        ssl_dhparam         xxx.dhparam;
        
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
    
        ssl_ciphers  ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers  on;

        # Add Alt-Svc header to negotiate HTTP/3.
        add_header alt-svc 'h3-23=":443"; ma=86400';

        root        /var/www/html;
        index       index.html;
  }

  server {
        listen      443 ssl     http2;
        # Enable QUIC and HTTP/3.
        listen      443 quic    reuseport;

        server_name www.bbbbb.com;

        ssl_certificate      xxx.crt;
        ssl_certificate_key  xxx.key;
        ssl_dhparam         xxx.dhparam;
        
        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;
    
        ssl_ciphers  ECDHE-RSA-AES128-GCM-SHA256:ECDHE:ECDH:AES:HIGH:!NULL:!aNULL:!MD5:!ADH:!RC4;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers  on;

        # Add Alt-Svc header to negotiate HTTP/3.
        add_header alt-svc 'h3-23=":443"; ma=86400';

        root        /var/www/html;
        index       index.html;
  }
………..
```
nginx: [emerg] duplicate listen options for 0.0.0.0:443 in /usr/local/nginx/conf/nginx.conf:248

**Comment by Znuff** [comment]
Leaving out the `reuseport` parameter seems to fix this and `http3-client` reports to be working; not entirely sure about the implications of running without it.

**Comment by xmapst** [comment]
@Znuff Ok, let me test it.

**Comment by junhochoi** [comment]
@xmapst does it work without `quic` listener?
@Znuff omitting `reuseport` may not work with multiple clients.
@ghedo I am not sure our quic patch supports this type of ssl configuration requiring SNI.

**Comment by junhochoi** [comment]
At least I can confirm that IP-based SSL host works, for example
```
listen      IP1:443 quic    reuseport;
...
listen      IP2:443 quic    reuseport;
```

**Comment by xmapst** [comment]
@junhochoi In the case of multiple ips, it can be normal, but it cannot be distinguished by domain name.

**Comment by xmapst** [comment]
I am working on http/3 on curl and will test it later.

**Comment by Znuff** [comment]
@junhochoi negative, that is how I actually encountered the issue, using `listen IP:443 quic reuseport` was my go-to, but it complained about duplicate listen.

In my initial test, I only did it on a single vhost, tought that would somehow matter. I have since added it to all the vhosts but with no results. Still getting `duplicate listen options for ip:port`

**Comment by xmapst** [comment]
The key configuration files are as follows
```
listen      443 quic    reuseport;
server_name www.yfdou.ga;
...
listen      443 quic;
server_name test.yfdou.ga;
```
The test returns the result as follows
```
root@DESKTOP-S1A1347:~/tmp/curl# curl -I --http2 https://www.yfdou.ga
HTTP/2 200
date: Mon, 28 Oct 2019 07:16:33 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d711d39d4ba9cd6955605a98e088a845c1572246993; expires=Tue, 27-Oct-20 07:16:33 GMT; path=/; domain=.yfdou.ga; HttpOnly
last-modified: Thu, 31 May 2018 02:47:06 GMT
vary: Accept-Encoding
cf-cache-status: DYNAMIC
alt-svc: h3-23=":443"; ma=86400
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 52cb1ffdfc947910-LAX

root@DESKTOP-S1A1347:~/tmp/curl# curl -I --http3 https://www.yfdou.ga
HTTP/3 200
date: Mon, 28 Oct 2019 07:16:39 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=db726274e1951b1ff763dfcf6f8a01fa01572246999; expires=Tue, 27-Oct-20 07:16:39 GMT; path=/; domain=.yfdou.ga; HttpOnly
last-modified: Thu, 31 May 2018 02:47:06 GMT
vary: Accept-Encoding
cf-cache-status: DYNAMIC
alt-svc: h3-23=":443"; ma=86400
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 52cb2022fddbe7dd-LAX
root@DESKTOP-S1A1347:~/tmp/curl# curl -I --http2 https://test.yfdou.ga
HTTP/2 200
date: Mon, 28 Oct 2019 07:16:53 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=dfed97524c3e881b2c62db669fdc976a51572247013; expires=Tue, 27-Oct-20 07:16:53 GMT; path=/; domain=.yfdou.ga; HttpOnly
last-modified: Thu, 31 May 2018 02:47:06 GMT
vary: Accept-Encoding
cf-cache-status: DYNAMIC
alt-svc: h3-23=":443"; ma=86400
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 52cb20784defe4ee-LAX

root@DESKTOP-S1A1347:~/tmp/curl# curl -I --http3 https://test.yfdou.ga
HTTP/3 200
date: Mon, 28 Oct 2019 07:16:57 GMT
content-type: text/html; charset=utf-8
set-cookie: __cfduid=d281caae3fa26c8bc85a949153dad2b3c1572247017; expires=Tue, 27-Oct-20 07:16:57 GMT; path=/; domain=.yfdou.ga; HttpOnly
last-modified: Thu, 31 May 2018 02:47:06 GMT
vary: Accept-Encoding
cf-cache-status: DYNAMIC
alt-svc: h3-23=":443"; ma=86400
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 52cb20935c5fead7-LAX
root@DESKTOP-S1A1347:~/tmp/curl#
```

**Comment by centminmod** [comment]
> At least I can confirm that IP-based SSL host works, for example
> 
> ```
> listen      IP1:443 quic    reuseport;
> ...
> listen      IP2:443 quic    reuseport;
> ```

Yes as i mentioned before reuseport is per IP/port pairing and I believe for quic similar.

IIRC, you can check via `ss` output you should have 1 instance for each listener IP/port per nginx worker_process.

on my nginx 1.16.1 + cloudflare http/3 patch with worker_process = 4

```
ss -lnut | egrep -e ':80 |:443 '              
udp    UNCONN     0      0         *:443                   *:*                  
udp    UNCONN     0      0         *:443                   *:*                  
udp    UNCONN     0      0         *:443                   *:*                  
udp    UNCONN     0      0         *:443                   *:*                  
tcp    LISTEN     0      4095      *:443                   *:*                  
tcp    LISTEN     0      4095      *:443                   *:*                  
tcp    LISTEN     0      4095      *:443                   *:*                  
tcp    LISTEN     0      4095      *:443                   *:*                  
tcp    LISTEN     0      4095      *:80                    *:*                  
tcp    LISTEN     0      4095      *:80                    *:*                  
tcp    LISTEN     0      4095      *:80                    *:*                  
tcp    LISTEN     0      4095      *:80                    *:*
```
i have reuseport only listed once for
* https 443 tcp
* http 80 tcp
* https 443 udp for quic

**Comment by centminmod** [comment]
> Leaving out the `reuseport` parameter seems to fix this and `http3-client` reports to be working; not entirely sure about the implications of running without it.

here's more info on what reuseport does at https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/

**Comment by Znuff** [comment]
I eventually got it working, too.

Reading what you said triggered an "Eurika" moment.

It is exactly as mentioned - you can use `reuseport` for _one_ `listen IP:PORT` directive. So if you have multiple vhosts share the same `IP:PORT`, you can only enable it for one.

My issue was a personal one, obviously, but I'm leaving it here maybe some poor soul will stumble upon it and will learn from my mistake:

I have a _generic_ snippet called `ssl_params` that I usually share between alias domains that redirect to my primary domain. For example, I tend to have a `domain.com` block that redirects to `www.domain.com` (which is my primary), or other aliases like `www.alias-domain.com` or `alias-domain.com`. Sometimes I use separate `server {}` blocks to redirect traffic to specific pages instead of the home page.

So to make it easier for me, I usually all my alias domains + primary domain share the same certificate, with multiple SANs. Thus I just include my cert in the snippet, and because the cert makes no sense without a `listen 443` directive, I usually put that line there, too. All to save a few keystrokes, eh?

So, to cut it short: **make sure you are not having multiple `listen 443 reuseport` included in different vhosts that you don't usually think twice about**.
