### ISSUE TITLE
how to post by http3-client

### ISSUE THREAD

**Issue by chenwq-bjtu** [cloudflare/quiche#241]
I want to post request to quic server, but it does not work. Could you give me some suggestion?
I modified the  code in client like below:

quiche_h3_header headers_post[] = {
                 {
                         .name = (const uint8_t *) ":method",
                         .name_len = sizeof(":method") - 1,

                         .value = (const uint8_t *) "POST",
                         .value_len = sizeof("POST")-1,
                 },

                 {
                         .name = (const uint8_t *) ":scheme",
                         .name_len = sizeof(":scheme") - 1,

                         .value = (const uint8_t *) "https",
                         .value_len = sizeof("https") - 1,
                 },

                 {
                         .name = (const uint8_t *) ":authority",
                         .name_len = sizeof(":authority") - 1,

                         .value = (const uint8_t *) conn_io->host,
                         .value_len = strlen(conn_io->host),
                 },

                 {
                         .name = (const uint8_t *) ":path",
                         .name_len = sizeof(":path") - 1,

                         .value = (const uint8_t *) conn_io->path,
                         .value_len = strlen(conn_io->path),
                 },

                 {
                         .name = (const uint8_t *) "user-agent",
                         .name_len = sizeof("user-agent") - 1,

                         .value = (const uint8_t *) "quiche",
                         .value_len = sizeof("quiche") - 1,
                 }

                ,{
                         .name = (const uint8_t *) "content-length",
                         .name_len = strlen("content-length"),
                         .value = (const uint8_t *) body_len_str.c_str(),
                         .value_len = body_len_str.length(),
                 }

        };

        if(with_body){
            headers = headers_post;
        }else{
            headers = headers_get;
        }

        int64_t stream_id = quiche_h3_send_request(conn_io->http3,
                                                   conn_io->conn,
                                                   headers, 5, !with_body);

        PLOGD("sent HTTP request %" PRId64 "\n", stream_id);
        if(with_body){
            ssize_t send_len = quiche_h3_send_body(conn_io->http3, conn_io->conn, stream_id,
                                                   (u_int8_t*)client->_post_body, client->_post_len,
                                                   true);
            PLOGD("sent HTTP body %d \n", send_len);
        }

        conn_io->req_sent = 1;

**Comment by LPardue** [comment]
```
int64_t stream_id = quiche_h3_send_request(conn_io->http3,
                                               conn_io->conn,
                                               headers, 5, !with_body);
```

In this fragment, you pass `5` as the `headers_len`  which is too short for the actual `headers_post[]` object that you are creating, You need pass an appropriate size.
