### ISSUE TITLE
Unexpected http0.9 protocol when using cURL

### ISSUE THREAD

**Issue by SecurityInsanity** [cloudflare/quiche#248]
:wave: Hey There (Thanks for the great library!),

I seem to be running into something unexpected while testing quiche (through the C FFI), and using a locally built cURL. When using cURL I must specify the: `--http0.9` option, but only when using my version (not the rust example).

In my C++ Code I run:

```
 // _config has been initialized with: quiche_config_new(QUICHE_PROTOCOL_VERSION);
quiche_config_set_application_protos(
      _config.get(),
      const_cast<uint8_t *>(
          reinterpret_cast<const uint8_t *>(QUICHE_H3_APPLICATION_PROTOCOL)),
      sizeof(QUICHE_H3_APPLICATION_PROTOCOL) - 1);
```

The definition of: `QUICHE_H3_APPLICATION_PROTOCOL` comes from `quiche.h`, and seems to be properly set to: `#define QUICHE_H3_APPLICATION_PROTOCOL "\x05h3-23"`, which is what I expect.

When I try to use cURL though I get:

```./src/curl -k --verbose --tlsv1.3 --http3 https://localhost:8080/ && echo ""
*   Trying ::1:8080...
* Sent QUIC client Initial, ALPN: h3-23
* quiche: recv() unexpectedly returned -1 (errno: 111, socket 3)
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1:8080...
* Sent QUIC client Initial, ALPN: h3-23
* h3 [:method: GET]
* h3 [:path: /]
* h3 [:scheme: https]
* h3 [:authority: localhost:8080]
* h3 [user-agent: curl/7.67.0-DEV]
* h3 [accept: */*]
* Using HTTP/3 Stream ID: 0 (easy handle 0x55e202f95280)
> GET / HTTP/3
> Host: localhost:8080
> user-agent: curl/7.67.0-DEV
> accept: */*
> 
* Received HTTP/0.9 when not allowed

* Connection #0 to host localhost left intact
curl: (1) quiche: recv() unexpectedly returned -1 (errno: 111, socket 3)
```

This error goes away if I provide the: `--http0.9` flag to cURL, and the request completes successfully.

When running the example http-server written in rust: `./target/debug/examples/http3-server --listen 0.0.0.0:8080` with cURL I am able to successfully query without providing the http0.9 flag:

```
./src/curl -k --tlsv1.3 --http3 https://localhost:8080/ && echo ""
Not Found!
```

(It should be noted while running the C example with: `./examples/http3-server 0.0.0.0 8080`, I get a straight up failure).

I'm curious if this is the only place I call: `quiche_config_set_application_protos`, and it doesn't (to the best of my knowledge) include http0.9, how is curl seeing this 0.9 data? Is there a config option I need to set when using the C API?

**Comment by LPardue** [comment]
What does it look like if you run the rust client against your server? e.g. `RUST_LOG=trace ./target/debug/examples/http3-client --no-verify https://localhost:8080/`

**Comment by SecurityInsanity** [comment]
It completes successfully: https://gist.github.com/SecurityInsanity/aef83a89294b9bde509a78ca8556fd43

**Comment by LPardue** [comment]
Thanks, in that case my suspicion is that there is something up with curl. What is strange is that the response is very simple `:status: 404, server: <SERVER>, content-length: <N>`. 

Perhaps @bagder has some more insight into why the `Received HTTP/0.9 when not allowed` is being generated when a HTTP/3 response is received.

**Comment by bagder** [comment]
It sounds like a (curl) bug. A HTTP/0.9 response would imply that curl thinks it comes without preceding headers...

**Comment by SecurityInsanity** [comment]
Interesting, sounds like I should open up an issue on cURL. Is there specific logs I can get to see what cURL thinks it's receiving? Since it seems: `curl -v` doesn't log the response information.

**Comment by SecurityInsanity** [comment]
Sounds good, Thanks!

I'll work on a reproduction case, and open up an issue.

**Comment by LPardue** [comment]
Thanks @SecurityInsanity, hopefully we can track down the root cause. Feel free to reopen this ticket if there is something in quiche that needs fixing up.

**Comment by SecurityInsanity** [comment]
Okay so I figured it out. This is reproducible by simply not sending the: `:status` header first from quiche. So for example if you apply this diff:

```
diff --git a/examples/http3-server.c b/examples/http3-server.c
index cf1a904..dbc9361 100644
--- a/examples/http3-server.c
+++ b/examples/http3-server.c
@@ -372,6 +372,13 @@ static void recv_cb(EV_P_ ev_io *w, int revents) {
                         }
 
                         quiche_h3_header headers[] = {
+                                                                                                         {
+                                                                                                       
                .name = (const uint8_t *)"content-length",
+                                                                                                       
                .name_len = sizeof("content-length") - 1,
+
+                                                                                                       
                .value = (const uint8_t *)"5",
+                                                                                                       
                .value_len = sizeof("5") - 1,
+                                                                                                       
        },
                             {
                                 .name = (const uint8_t *) ":status",
                                 .name_len = sizeof(":status") - 1,
@@ -387,18 +394,10 @@ static void recv_cb(EV_P_ ev_io *w, int revents) {
                                 .value = (const uint8_t *) "quiche",
                                 .value_len = sizeof("quiche") - 1,
                             },
-
-                            {
-                                .name = (const uint8_t *) "content-length",
-                                .name_len = sizeof("content-length") - 1,
-
-                                .value = (const uint8_t *) "5",
-                                .value_len = sizeof("5") - 1,
-                            },
                         };
 
                         quiche_h3_send_response(conn_io->http3, conn_io->conn,
-                                                s, headers, 3, true);
+                                                s, headers, 3, false);
 
                         quiche_h3_send_body(conn_io->http3, conn_io->conn,
                                             s, (uint8_t *) "byez\n", 5, true);
```

To the example C http3 server in this repository, (and then run `make` inside of the examples directory to build it). cURL will generate this error message.

Is the status field required to come first in HTTP/3? If so I would think we'd want quiche to enforce this header come first in: `quiche_h3_send_response()`. If it isn't required to come first than I think it's a bug for cURL. Unfortunately I'm not sure if it is required or not so I figured I'd ask here. :smile:

**Comment by LPardue** [comment]
> Is the status field required to come first in HTTP/3? If so I would think we'd want quiche to enforce this header come first in: quiche_h3_send_response(). If it isn't required to come first than I think it's a bug for cURL. Unfortunately I'm not sure if it is required or not so I figured I'd ask here. smile

Thanks for asking! HTTP/3 inherits the same requirements from HTTP/2, which says in https://tools.ietf.org/html/rfc7540#section-8.1.2.4 

```
   For HTTP/2 responses, a single ":status" pseudo-header field is
   defined that carries the HTTP status code field (see [RFC7231],
   Section 6).  This pseudo-header field MUST be included in all
   responses; otherwise, the response is malformed (Section 8.1.2.6).
```
and from 

```
   All pseudo-header fields MUST appear in the header block before
   regular header fields. Any request or response that contains a
   pseudo-header field that appears in a header block after a regular
   header field MUST be treated as malformed.
```

This is really interesting, I'm curious how curl behaves with ngtcp2 (for H2 or H3), does that library implement this error checking or does curl do it?

**Comment by SecurityInsanity** [comment]
That's good to know about header fields (does quiche enforce ordering on that currently?) Hoewver is the: `HTTP/3 404` line also included as part of that pseudo-header field? I believe that is why cURL believes it's a http 0.9 request.

As for ngtcp2 I'm also curious but don't have an easy way to test that at the moment.

**Comment by LPardue** [comment]
I meant to say nghttp2 or nghttp3, since this is a problem at that level. 

I appreciate its been annoying to encounter this bug but in considering the class of problem there are two questions that come to mind, 

1. should the library validate the request or response headers before sending? 
2. should the library validate the request or response headers after receiving?

quiche doesn't validate this aspect of `quiche::h3::Headers` because it can be costly to iterate over a long list of headers trying to spot a problem. This really shouldn't be happening for locally generated headers (because and is controlled by the application) and on the receive side is also detectable in the application. 

Perhaps it would be enough to document the current behaviour so that library users know what to expect.

**Comment by LPardue** [comment]
> Hoewver is the: HTTP/3 404 line also included as part of that pseudo-header field? 

There are no request or response lines in HTTP/2 or HTTP/3. Instead the pseudo-headers fill that rols, so "on the wire" requests and responses look like this:
```
:method: GET
:scheme: https
:authority: example.com
:path: /
<other headers>
```

```
:status: 200
<other headers>
``` 

However, applications often convert this back into an older style presentation format because it is what people (and tools) are familiar with. This is true for curl and web browsers.

**Comment by SecurityInsanity** [comment]
Ah okay, so it's just a text presentation. I appreciate that clarification.

I also agree that it may not be ideal to handle it in quiche, and only have documentation around it. I'd be curious what other libraries do here, since it's also costly to iterate through from an application standpoint as well (is it worth it to ask someone to maintain that ordering themselves?, probably worth it if that's what "the norm" is).

Either way I'll move some logic around this into my toy app for now. Would you like another issue specifically around documentation/ordering enforcement (whatever is decided?), or should I perhaps reopen this one?

**Comment by bagder** [comment]
This behavior in curl was inherited into this code simply because nghttp2 works that way and parts of the quiche backend code in curl was pretty much copied-and-pasted from that code.
