### ISSUE TITLE
Using quiche in Android(Calling quiche from Java)

### ISSUE THREAD

**Issue by VMatrix1900** [cloudflare/quiche#25]
I would like to use the quiche library in my Android app. I am able to use the NDK toolchain to cross-compile quiche(including boringSSL) for Android. Now I need to create a Java binding. Based on my research, there are 2 ways to call Rust from Java:
1. JNI (writing it manually or use generation tool)
2. JNA (which hides all complexity of JNI) but may incur some overhead

Which method is preferred? Is there any other option?

**Comment by ghedo** [comment]
I don't really know anything about Android, so I don't have a preference. The quiche C API is pretty small though, so going with JNI might not be that more complicated, and without the added overhead.

**Comment by ghedo** [comment]
I guess this is answered now, so I'll close.

**Comment by ZhihuiYang** [comment]
> I would like to use the quiche library in my Android app. I am able to use the NDK toolchain to cross-compile quiche(including boringSSL) for Android. Now I need to create a Java binding. Based on my research, there are 2 ways to call Rust from Java:
> 
> 1. JNI (writing it manually or use generation tool)
> 2. JNA (which hides all complexity of JNI) but may incur some overhead
> 
> Which method is preferred? Is there any other option?

Hi, would you kindly to share how to use the NDK toolchain to cross-compile quiche? I am trying to do the same things you have done successfully. but the problem I met is built quiche for android failed due to ring!
