### ISSUE TITLE
Bare-metal support

### ISSUE THREAD

**Issue by jonathanpallant** [cloudflare/quiche#252]
I'd like to run quiche as an HTTP/3 client on a bare-metal NB-IoT / LTE-M device I'm working on. I've patched quiche to build as `#![no_std]` (basically swapping `String` for `alloc::string::String` and the like) and that runs fine on my Linux box with the provided examples. The problem is when I compile for the `thumbv8m.main-none-eabi` target, BoringSSL doesn't appear to be set-up to target a bare-metal environment - the compiler tests try and pass the `-rdynamic` argument, and if you work around that it's then looking for `pthread_rwlock_t` and other pthread things.

Is running BoringSSL on bare-metal merely a challenge, or fundamentally impossible? If the latter, how hard would it be to replace the calls to `SSL_xxx` with, say, mbedTLS? Or is it possible to call into `ring` instead of calling BoringSSL directly, as `ring` seems to be compiling (with a few patches) for `thumbv8m.main-none-eabi` just fine?

**Comment by ghedo** [comment]
> I've patched quiche to build as #![no_std]

What did you replace `HashMap` with? AFAICT it doesn't have an `alloc` alternative. In any case if you got this to work withreasonable changes, feel free to open a PR, there were other users interested in no_std support (e.g. https://github.com/cloudflare/quiche/issues/115).

> and if you work around that it's then looking for pthread_rwlock_t and other pthread things

FWIW you can disable threading support in BoringSSL, see e.g. https://github.com/google/boringssl/commit/65a7e9442c

> Is running BoringSSL on bare-metal merely a challenge, or fundamentally impossible?

I don't know, I have never tried (and never needed to). If it's of any helo, once https://github.com/openssl/openssl/pull/8797 is merged it will be possible to build quiche against OpenSSL, though I don't know if it's any easier to build for bare metal.

In any case it's very much unlikely we'll be supporting other TLS libraries (and ring doesn't implement TLS, just crypto algorithms).

**Comment by jonathanpallant** [comment]
> What did you replace HashMap with?

BTreeMap (and BTreeSet for HashSet). Seem to have equivalent APIs.

> FWIW you can disable threading support in BoringSSL

Good to know, thanks.

Looking at mbedtls, it doesn't seem to support QUIC or even TLS 1.3 at this time, so I'll keep working on BoringSSL.

**Comment by ghedo** [comment]
It sounds like you managed to get this running in the end https://twitter.com/therealjpster/status/1217854883962945536 :)

So, closing this now :)

**Comment by jonathanpallant** [comment]
Yes, at https://github.com/42-technology-ltd/v1026-demo-app, but it's over four years out of date at this point and I don't work there any more or any any idea if it still works.

**Comment by theoparis** [comment]
It seems like that requires changes to quiche to use default-features = false  and core/alloc. Maybe [this fork](https://github.com/cloudflare/quiche/compare/master...42-technology-ltd:quiche:no_std_support), could be upstreamed?
