### ISSUE TITLE
Alpine based can not work

### ISSUE THREAD

**Issue by Vndroid** [cloudflare/quiche#259]
Hey, According to #227 and [Quiche](https://github.com/cloudflare/quiche#building). I noticed that the Rust version has been changed to 1.39 or later. So It can not compile on Alpine. The Alpine edge branch version is 1.38. How to solve this problem? 

And Official Dockfile [View it](https://github.com/cloudflare/quiche/blob/master/examples/Dockerfile) is Debian based. Do I have to build it use Multi-Stage Build?

**Comment by junhochoi** [comment]
rust seems to provide images based on Alpine. Does this work?
- https://hub.docker.com/_/rust?tab=tags (search by `alpine`)

**Comment by ghedo** [comment]
Looks like the alpine rust package has been updated now https://pkgs.alpinelinux.org/package/edge/community/x86_64/rust so closing this.
