### ISSUE TITLE
Hit TlsFail while running examples http3-server and http3-client

### ISSUE THREAD

**Issue by thinkhy** [cloudflare/quiche#268]
Running examples http3-server and http3-client by issuing commands on MacOS(Darwin Kernel Version 18.7.0):
 
```shell
    cargo run --example http3-server 
    cargo run --example http3-client https://127.0.0.1:4433 
```

Hit failures from client side like below

```
[2019-11-24T14:02:03.735693000Z ERROR http3_client] recv failed: TlsFail
[2019-11-24T14:02:03.860870000Z ERROR http3_client] connection timed out after 132.499576ms and only completed 0/1 requests
```

Anyone hit the similar problem? Thanks a lot.

**Comment by LPardue** [comment]
the example server(s) by default to run with a serf-signed cert that is not trusted by the client. To solve this you can run with a valid certificate of your own, or run the client with the validation skip flag `--no-verfiy` e.g.

`cargo run --example http3-client -- --no-verify  https://127.0.0.1:4433`

or just skip cargo run altogether and do

`./target/debug/examples/http3-client --no-verify https://12.0.0.1:443`

**Comment by ghedo** [comment]
On top of what @LPardue said, if you enable trace logging you can see additional details, just set `RUST_LOG=trace` environment variable.

Anyway, closing as this was answered. Feel free to reopen if you still have problems.

**Comment by thinkhy** [comment]
@LPardue @ghedo thanks for your replies.  I still hit the issue, seems it's caused by timeout problem:

```
[2019-11-27T09:27:07.299471000Z DEBUG http3_client] written 48
[2019-11-27T09:27:07.299530000Z DEBUG http3_client] done writing
[2019-11-27T09:27:07.824093000Z DEBUG http3_client] timed out
[2019-11-27T09:27:07.824177000Z TRACE quiche] 11f3609530bd0ba68ad74e4882855455005e13dd draining timeout expired
```

The whole client log is put here: https://gist.github.com/thinkhy/f04aa419c4cac09abd620ce2b690d506

**Comment by LPardue** [comment]
From the log you posted, there is no TlsFail and the request succeeds as shown by

`1/1 responses received`

After the client sends APPLICATION_CLOSE there is nothing that happens on the connection and so it naturally time out, this is not an error.
