### ISSUE TITLE
Quic multipath extension support?

### ISSUE THREAD

**Issue by vmolsa** [cloudflare/quiche#278]
Please add support for [quic multipath extension](https://tools.ietf.org/html/draft-deconinck-quic-multipath-03)

The multipath extension is required for p2p connections, when both of the client and server are located behind a NAT. Otherwise we have to use PCP, STUN kind of trick to get this working..

According the draft the multipath extension support could be checked during the quic connection opening / handshake, so changes to quic protocol itself does not affect to rest of the quic connections.

>  A Multipath QUIC connection starts like a regular QUIC connection.  A
   cryptographic handshake takes place with CRYPTO frames and follows
   the classical process [I-D.ietf-quic-transport] [I-D.ietf-quic-tls].
   It is during that process that the multipath capability is negotiated
   between hosts.  This is performed using the max_sending_paths
   transport parameter, where both hosts advertise their support for the
   multipath extension.  Any value different from 0 indicates that the
   host wants to support multipath over the connection.  If one of the
   hosts does not advertise the max_sending_paths transport parameter,
   the negotiated value is 0, meaning that the QUIC connection will not
   use the multipath extensions

There are few changes for quic protocol itself, but most of the changes could be implemented at application side.

**Comment by ghedo** [comment]
We don't have any plan to implement that currently. The draft will at least need to be adopter by the IETF QUIC working group and receive some more review before we can consider implementing it, though this might not be sufficient, at least not in the short-medium term, as we already have a fair amount of other things planned.

**Comment by hronro** [comment]
The draft has been adopted by the QUIC working group: https://datatracker.ietf.org/doc/draft-ietf-quic-multipath/

Would this been reconsidered for now?

**Comment by polatmete** [comment]
Any updates on this?
