### ISSUE TITLE
quiche_h3_conn_poll and quiche_h3_send_response function are thread safety?

### ISSUE THREAD

**Issue by scguoi** [cloudflare/quiche#280]
I want to use HTTP/3 for stream communicate just like HTTP/2 in gRPC. So, I use two thread one for receive which call quiche_h3_conn_poll function. The other is for send which call quiche_h3_send_response. They was doing well at start, but when send and reveive hundreds of times, the program hunged, without any result.

**Comment by ghedo** [comment]
The `quiche_conn` and `quiche_h3_conn` types are not thread safe unfortunately, so they shouldn't be used across threads without some kind of synchronization mechanism.

**Comment by scguoi** [comment]
> The `quiche_conn` and `quiche_h3_conn` types are not thread safe unfortunately, so they shouldn't be used across threads without some kind of synchronization mechanism.

@ghedo Does support thread safe on the schedule?

**Comment by ghedo** [comment]
We don't currently have any plan, though it also wouldn't necessarily fix the issue you are seeing. In alternative to that you can probably use a mutex on the connection object or something along those lines.
