### ISSUE TITLE
Using demo to continuously transfer large files will stop sending

### ISSUE THREAD

**Issue by sfatShady** [cloudflare/quiche#282]
When I modify the demo for testing, I modify the receiving and sending mechanism of the client and the server, and use multithreading to receive and send data for processing. When sending large files, problems such as incomplete sending and stopping sending will occur. Specific troubleshooting is caused by too fast sending speed and too slow packet returning. Is there anyone who has the same problem with me, and how to solve it?

**Comment by junhochoi** [comment]
There is a related issue #280. quiche currently is not thread-safe. Can you explain what is your modification and what is an expected result?

**Comment by ghedo** [comment]
Yeah, sounds like the issue in #280. This is not currently a supported use case.

**Comment by sfatShady** [comment]
Hello, when we stop sending data with demo, we can see in quicdebug printing that when the server receives the last package, the inflight value does not decrease, so the CWnd value is very small, and the new data cannot be sent. The attachment is the test print log I intercepted (different platforms of server and client, time is not synchronized). Would you please help me analyze it? Thanks a lot.
[server.log](https://github.com/cloudflare/quiche/files/3915787/server.log)

**Comment by sfatShady** [comment]
Sorry, my log can't be uploaded normally. I can only intercept some logs and write them directly below.

2019-12-3 15:27:48.663053 [6597] debug_log: quiche::recovery: acked4 cwnd=11417
2019-12-3 15:27:48.663061 [6597] debug_log: quiche::recovery: 850239fe276ccd436b5c3418ec19effd packet newly acked 1769
2019-12-3 15:27:48.663074 [6597] debug_log: quiche::recovery: 850239fe276ccd436b5c3418ec19effd timer=none inflight=0 cwnd=11417 latest_rtt=5.046333ms srtt=Some(2.940735ms) min_rtt=2.038ms rttvar=627.178µs probes=0 
2019-12-3 15:27:48.663091 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd rx frm MAX_DATA max=25686824
2019-12-3 15:27:48.663102 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd rx frm MAX_STREAM_DATA stream=4 max=25686824
2019-12-3 15:27:48.663150 [6597] debug_log: quiche::recovery: usize1 cwnd=11417
2019-12-3 15:27:48.663160 [6597] debug_log: quiche: cwnd=11417 b.cap=16383
2019-12-3 15:27:48.663168 [6597] debug_log: quiche::recovery: usize1 cwnd=11417
2019-12-3 15:27:48.663177 [6597] debug_log: quiche: left=11417
2019-12-3 15:27:48.663185 [6597] debug_log: quiche: left2
2019-12-3 15:27:48.663244 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd tx pkt Short dcid=10000000a0000000e48cac00f0210d01 key_phase=false len=11392 pn=1771
2019-12-3 15:27:48.663258 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd tx frm ACK delay=32 blocks=[1150..1151]
2019-12-3 15:27:48.663267 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd tx frm STREAM id=4 off=15686824 len=11362 fin=false
2019-12-3 15:27:48.663318 [6597] debug_log: quiche::recovery: 850239fe276ccd436b5c3418ec19effd timer=30.286072ms inflight=11411 cwnd=11417 latest_rtt=5.046333ms srtt=Some(2.940735ms) min_rtt=2.038ms rttvar=627.178µs probes=0 
2019-12-3 15:27:48.663435 [6597] debug_log: quiche::recovery: usize1 cwnd=6
2019-12-3 15:27:48.663447 [6597] debug_log: quiche: cwnd=6 b.cap=16383
2019-12-3 15:27:48.663455 [6597] debug_log: quiche::recovery: usize1 cwnd=6
2019-12-3 15:27:48.663463 [6597] debug_log: quiche: left=6
2019-12-3 15:27:48.674420 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd rx pkt Short dcid=850239fe276ccd436b5c3418ec19effd key_phase=false len=27 pn=1152
2019-12-3 15:27:48.674478 [6597] debug_log: quiche: 850239fe276ccd436b5c3418ec19effd rx frm ACK delay=732 blocks=[1755..1755, 1767..1770]
2019-12-3 15:27:48.674523 [6597] debug_log: quiche::recovery: usize1 cwnd=6
2019-12-3 15:27:48.674534 [6597] debug_log: quiche: cwnd=6 b.cap=16383
2019-12-3 15:27:48.674542 [6597] debug_log: quiche::recovery: usize1 cwnd=6

**Comment by sfatShady** [comment]
[server.log](https://github.com/cloudflare/quiche/files/3916142/server.log)
[client.log](https://github.com/cloudflare/quiche/files/3916144/client.log)
This is the log of my server and client. Please check it for me. Thank you.

**Comment by ghedo** [comment]
Without seeing the code it's impossible to understand what's going on by just looking at the logs. In any case as I said above sending and receiving from different threads is not supported.
