### ISSUE TITLE
build   x86 windows failed

### ISSUE THREAD

**Issue by fjyihan** [cloudflare/quiche#293]
use last master code:build x86 windows failed
use commit 7cd2fe0 code: build x86 windows successed.
i find  this commit 817072cd "build: fix 32bit x86 cross-build", are you sure,this is ok?

**Comment by junhochoi** [comment]
@fjyihan our CI has Windows build, looking fine: https://travis-ci.com/cloudflare/quiche/jobs/263835985

Do you mean it start to break your build from 81702c? Can you post build error log here?

**Comment by junhochoi** [comment]
I opened #294 to fix this. @fjyihan please test if this works for you.

**Comment by fjyihan** [comment]
I compiled successfully using win_x86 branch code
