### ISSUE TITLE
Logging CC

### ISSUE THREAD

**Issue by junhochoi** [cloudflare/quiche#303]
#299 use trace!() for logging CC variable changes but probably too expensive and impact actual performance. Better to separate CC logging function and later it can be replaced (or added) to qlog support when we have it.

**Comment by ghedo** [comment]
@junhochoi given https://github.com/cloudflare/quiche/pull/304#issuecomment-605796009, should this issue be closed as well?

**Comment by junhochoi** [comment]
Right.
