### ISSUE TITLE
travis: improving android build support

### ISSUE THREAD

**Issue by junhochoi** [cloudflare/quiche#325]
Currently we only test build with old (gcc) based NDK. However recent NDK switched to clang, so need to test and fix the necessary part.

**Comment by junhochoi** [comment]
Related to #300

**Comment by ghedo** [comment]
This was fixed in https://github.com/cloudflare/quiche/commit/9704e9a2cf3b903693f7ff8bc039d5698ffb7684 (but forgot to mention the issue in the ocmmit message).
