### ISSUE TITLE
Server could not send data through new stream

### ISSUE THREAD

**Issue by Kumius** [cloudflare/quiche#338]
According to current examples. Server will echo "byez" through the same stream (id = 4) initialized by client. Just like this:
`quiche_conn_stream_send(conn_io->conn, s, (uint8_t *) resp, 5, true);`
But when I change the stream id from 's' to 's+1', it won't work. I can not get anything by calling `quiche_conn_send()`.
Do you know how to send data through a new stream from server side? All I know is sending data through stream whose ID is 4N+1.

**Comment by LPardue** [comment]
Quiche respects the QUIC transport rules regarding stream ID behaviour and stream state.

Please see https://tools.ietf.org/html/draft-ietf-quic-transport-25#section-2.1 for more information.

**Comment by Kumius** [comment]
Thanks! It works.
