### ISSUE TITLE
error: could not find native static library `crypto`, perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by bagder** [cloudflare/quiche#36]
I've come back to my quiche dir since a while of absence and now it fails when I build and I could use your help to fix it. It built before, but no longer for some reason.

I build boringssl in a separate directory and I want quiche to pick it up from there. The boringssl dir works fine to build against for other purposes. It only has static libraries built.

~~~
$ QUICHE_BSSL_PATH=$HOME/src/boringssl cargo build
   Compiling quiche v0.1.0-alpha3 (/home/daniel/src/quiche)
error: could not find native static library `crypto`, perhaps an -L flag is missing?

error: aborting due to previous error

error: Could not compile `quiche`.

To learn more, run the command again with --verbose.

**Comment by ghedo** [comment]
The README is not super clear about this, but the quiche build script expects that boringssl is built in a `build/` subdirectory (see e.g. https://github.com/cloudflare/quiche/blob/master/src/build.rs#L15).

So, the `QUICHE_BSSL_PATH` variable is set correctly, but boringssl needs to be built as follows, from its root directory (`$HOME/src/boringssl`):
```
 $ mkdir build && cd build
 $ cmake ..
 $ make
```
Don't know if this is your problem, but I've seen this in the past, so might as well try it.

**Comment by bagder** [comment]
ah, that simple eh? =) For some reason I had created and built in a 'build2' directory now but once I just redid it in 'build' as you explained here it works again. Thanks!

**Comment by wangwanchao** [comment]
I had the same problem. I dont known how do the quiche find boringssl. After building the boringssl, there is problem.Then I run 
```
cd $QUICHE_HOME/deps/boringssl
cmake $BORINGSSL_HOME
```

**Comment by LPardue** [comment]
@wangwanchao you've now commented on 4 closed issues. Please stop doing that and create a new issue documenting your precise problem.

**Comment by wangwanchao** [comment]
I am so sorry for that.But I think you hadnt solve them.Dont closed them,just solve it.
