### ISSUE TITLE
can not establish connection sometimes when the network packet loss rate is a little bit high

### ISSUE THREAD

**Issue by tangdaojun** [cloudflare/quiche#385]
**connection not established.**
![image](https://user-images.githubusercontent.com/4987804/75660227-62cab600-5ca6-11ea-8e08-645717e4a3b5.png)

I captured the udp streams when the connection can not be established, as you can see from the image above which is different from the normal one like this below.

**connection established.**
![image](https://user-images.githubusercontent.com/4987804/75660780-23509980-5ca7-11ea-8091-4014b4b9a98a.png)

how can I solve it? thanks!

**Comment by junhochoi** [comment]
Can you give us more detailed information? such as
- server and client version (do you use quiche for both?)
- is it reproducible? if you use quiche, can you run the client/server with RUST_LOG=trace and run it again?

**Comment by tangdaojun** [comment]
- server and client version (do you use quiche for both?)
yes, I used quiche for both.
protocol version is for both: **#define QUICHE_H3_APPLICATION_PROTOCOL "\x05h3-24\x05h3-23"**
and I used quiche **release version 0.2.0**

- is it reproducible? if you use quiche, can you run the client/server with RUST_LOG=trace and run it again?
yes, it's reproducible. I built and run http3-client.c & http3-server.c from the example directory, and here is the log.

---
**http3-client log**
quiche::tls: a33e38a39521daae09aecb9c0c38c564 tls write message lvl=Initial len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx pkt Initial version=babababa dcid=0159bfb1f804eab5175ceb538d984449 scid=a33e38a39521daae09aecb9c0c38c564 len=1157 pn=0
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm CRYPTO off=0 len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm PADDING len=625
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=998.2068ms inflight=1200 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0]
sent 1200 bytes
done writing
quiche: a33e38a39521daae09aecb9c0c38c564 rx pkt VersionNegotiation version=0 dcid=a33e38a39521daae09aecb9c0c38c564 scid=0159bfb1f804eab5175ceb538d984449 versions=[ff000018, ff000017]
done reading
quiche::tls: a33e38a39521daae09aecb9c0c38c564 tls write message lvl=Initial len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx pkt Initial version=ff000018 dcid=0159bfb1f804eab5175ceb538d984449 scid=a33e38a39521daae09aecb9c0c38c564 len=1157 pn=1
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm CRYPTO off=0 len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm PADDING len=625
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=998.3185ms inflight=1200 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0]
sent 1200 bytes
done writing
quiche: a33e38a39521daae09aecb9c0c38c564 rx pkt Retry version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=0159bfb1f804eab5175ceb538d984449 odcid=0159bfb1f804eab5175ceb538d984449 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449
done reading
quiche::tls: a33e38a39521daae09aecb9c0c38c564 tls write message lvl=Initial len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx pkt Initial version=ff000018 dcid=0159bfb1f804eab5175ceb538d984449 scid=a33e38a39521daae09aecb9c0c38c564 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449 len=1119 pn=2
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm CRYPTO off=0 len=512
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm PADDING len=587
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=998.4221ms inflight=1200 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns loss_time=[None, None, None] loss_probes=[0, 0, 0]
sent 1200 bytes
done writing
quiche: a33e38a39521daae09aecb9c0c38c564 rx pkt Initial version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=fa6cc7545069b7552828c6335c6a89e2 token= len=149 pn=0
quiche: a33e38a39521daae09aecb9c0c38c564 rx frm ACK delay=315 blocks=[2..2]
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 packet newly acked 2
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=none inflight=0 cwnd=15720 latest_rtt=124.4145ms srtt=Some(124.4145ms) min_rtt=124.4145ms rttvar=62.20725ms loss_time=[None, None, None] loss_probes=[0, 0, 0]
quiche: a33e38a39521daae09aecb9c0c38c564 rx frm CRYPTO off=0 len=122
quiche::tls: a33e38a39521daae09aecb9c0c38c564 tls set encryption secret lvl=Handshake
recv 191 bytes
recv would block
quiche: a33e38a39521daae09aecb9c0c38c564 tx pkt Initial version=ff000018 dcid=fa6cc7545069b7552828c6335c6a89e2 scid=a33e38a39521daae09aecb9c0c38c564 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449 len=1119 pn=3
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm ACK delay=417 blocks=[0..0]
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm PADDING len=1097
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=none inflight=0 cwnd=15720 latest_rtt=124.4145ms srtt=Some(124.4145ms) min_rtt=124.4145ms rttvar=62.20725ms loss_time=[None, None, None] loss_probes=[0, 0, 0]
sent 1200 bytes
done writing
quiche: a33e38a39521daae09aecb9c0c38c564 rx pkt Handshake version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=fa6cc7545069b7552828c6335c6a89e2 len=1155 pn=0
quiche: a33e38a39521daae09aecb9c0c38c564 rx frm CRYPTO off=0 len=1134
recv 1196 bytes
recv would block
quiche: a33e38a39521daae09aecb9c0c38c564 tx pkt Handshake version=ff000018 dcid=fa6cc7545069b7552828c6335c6a89e2 scid=a33e38a39521daae09aecb9c0c38c564 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449 len=22 pn=0
quiche: a33e38a39521daae09aecb9c0c38c564 tx frm ACK delay=479 blocks=[0..0]
quiche::recovery: a33e38a39521daae09aecb9c0c38c564 timer=none inflight=0 cwnd=15720 latest_rtt=124.4145ms srtt=Some(124.4145ms) min_rtt=124.4145ms rttvar=62.20725ms loss_time=[None, None, None] loss_probes=[0, 0, 0]
quiche: a33e38a39521daae09aecb9c0c38c564 dropped epoch 0 state
sent 63 bytes
done writing
timeout
done writing
timeout
done writing

**http3-server log**
version negotiation
sent 47 bytes
stateless retry
sent 94 bytes
new connection
quiche: fa6cc7545069b7552828c6335c6a89e2 rx pkt Initial version=ff000018 dcid=0159bfb1f804eab5175ceb538d984449 scid=a33e38a39521daae09aecb9c0c38c564 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449 len=1120 pn=2
quiche: fa6cc7545069b7552828c6335c6a89e2 rx frm CRYPTO off=0 len=512
quiche::tls: checking peer ALPN Ok("h3-24") against Ok("h3-24")
quiche::tls: fa6cc7545069b7552828c6335c6a89e2 tls write message lvl=Initial len=122
quiche::tls: fa6cc7545069b7552828c6335c6a89e2 tls set encryption secret lvl=Handshake
quiche::tls: fa6cc7545069b7552828c6335c6a89e2 tls set encryption secret lvl=OneRTT
quiche::tls: fa6cc7545069b7552828c6335c6a89e2 tls write message lvl=Handshake len=1346
quiche: fa6cc7545069b7552828c6335c6a89e2 rx frm PADDING len=587
recv 1200 bytes
recv would block
done writing
done writing
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 tx pkt Initial version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=fa6cc7545069b7552828c6335c6a89e2 len=148 pn=0
quiche: fa6cc7545069b7552828c6335c6a89e2 tx frm ACK delay=315 blocks=[2..2]
quiche: fa6cc7545069b7552828c6335c6a89e2 tx frm CRYPTO off=0 len=122
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=999.891849ms inflight=191 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns probes=0
sent 191 bytes
quiche: fa6cc7545069b7552828c6335c6a89e2 tx pkt Handshake version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=fa6cc7545069b7552828c6335c6a89e2 len=1154 pn=0
quiche: fa6cc7545069b7552828c6335c6a89e2 tx frm CRYPTO off=0 len=1134
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=999.890456ms inflight=1387 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns probes=0
sent 1196 bytes
quiche: fa6cc7545069b7552828c6335c6a89e2 tx pkt Handshake version=ff000018 dcid=a33e38a39521daae09aecb9c0c38c564 scid=fa6cc7545069b7552828c6335c6a89e2 len=233 pn=1
quiche: fa6cc7545069b7552828c6335c6a89e2 tx frm CRYPTO off=1134 len=212
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=999.910405ms inflight=1662 cwnd=14520 latest_rtt=0ns srtt=None min_rtt=0ns rttvar=0ns probes=0
sent 275 bytes
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 rx pkt Initial version=ff000018 dcid=fa6cc7545069b7552828c6335c6a89e2 scid=a33e38a39521daae09aecb9c0c38c564 token=7175696368651002d046c0a8890100000000000000000159bfb1f804eab5175ceb538d984449 len=1120 pn=3
quiche: fa6cc7545069b7552828c6335c6a89e2 rx frm ACK delay=417 blocks=[0..0]
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 packet newly acked 0
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=273.38199ms inflight=1471 cwnd=14711 latest_rtt=124.135969ms srtt=Some(124.135969ms) min_rtt=124.135969ms rttvar=62.067984ms probes=0
quiche: fa6cc7545069b7552828c6335c6a89e2 rx frm PADDING len=1097
recv 1200 bytes
recv would block
done writing
done writing
done writing
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 rx pkt Handshake version=ff000018 dcid=fa6cc7545069b7552828c6335c6a89e2 scid=a33e38a39521daae09aecb9c0c38c564 len=23 pn=0
quiche: fa6cc7545069b7552828c6335c6a89e2 rx frm ACK delay=479 blocks=[0..0]
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 packet newly acked 0
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=223.583657ms inflight=275 cwnd=15907 latest_rtt=224.601999ms srtt=Some(136.694221ms) min_rtt=124.135969ms rttvar=71.667495ms probes=0
quiche: fa6cc7545069b7552828c6335c6a89e2 dropped epoch 0 state
recv 63 bytes
recv would block
done writing
done writing
done writing
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 loss detection timeout expired
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=446.761126ms inflight=275 cwnd=15907 latest_rtt=224.601999ms srtt=Some(136.694221ms) min_rtt=124.135969ms rttvar=71.667495ms probes=2
timeout
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 loss detection timeout expired
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=892.950212ms inflight=275 cwnd=15907 latest_rtt=224.601999ms srtt=Some(136.694221ms) min_rtt=124.135969ms rttvar=71.667495ms probes=2
timeout
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 loss detection timeout expired
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=1.788356313s inflight=275 cwnd=15907 latest_rtt=224.601999ms srtt=Some(136.694221ms) min_rtt=124.135969ms rttvar=71.667495ms probes=2
timeout
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 loss detection timeout expired
quiche::recovery: fa6cc7545069b7552828c6335c6a89e2 timer=3.581585035s inflight=275 cwnd=15907 latest_rtt=224.601999ms srtt=Some(136.694221ms) min_rtt=124.135969ms rttvar=71.667495ms probes=2
timeout
done writing
quiche: fa6cc7545069b7552828c6335c6a89e2 idle timeout expired
timeout
done writing
connection closed, recv=3 sent=3 lost=0 rtt=136694221ns cwnd=18446744073709551615

---
Thanks!

**Comment by junhochoi** [comment]
h3-24 looks pretty old. Can you try with latest master from quiche repo?
In that case, please use quiche-client/server for testing. See https://github.com/cloudflare/quiche#command-line-apps for details. You can get a debug with with quiche apps using RUST_LOG=trace too.

**Comment by tangdaojun** [comment]
I've checkout the latest master branch from quiche repo, I did steps as you describe, but I got an error from quiche_client: **recv failed: TlsFail**

**client side command:**
cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://127.0.0.1:4433/
    Finished dev [unoptimized + debuginfo] target(s) in 1.28s
     Running `tools/apps/target/debug/quiche-client 'https://127.0.0.1:4433/'`
[2020-03-03T07:22:44.949555600Z ERROR quiche_client] recv failed: TlsFail

**server side command:**
cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-server -- \
      --cert tools/apps/src/bin/cert.crt \
      --key tools/apps/src/bin/cert.key

**Comment by junhochoi** [comment]
Common case of TlsFail error is when you connect to QUIC servers with self-signed TLS sites.
Please add `--no-verify` to `quiche_client`.

**Comment by tangdaojun** [comment]
thanks @junhochoi , My issue was fixed.

**Comment by mivuDing** [comment]
> **connection not established.**
> ![image](https://user-images.githubusercontent.com/4987804/75660227-62cab600-5ca6-11ea-8e08-645717e4a3b5.png)
> 
> I captured the udp streams when the connection can not be established, as you can see from the image above which is different from the normal one like this below.
> 
> **connection established.**
> ![image](https://user-images.githubusercontent.com/4987804/75660780-23509980-5ca7-11ea-8091-4014b4b9a98a.png)
> 
> how can I solve it? thanks!
Hello，had you solve the problem? I use the newest master code , and still got the issue. Is there anything need I to set?Thanks!
