### ISSUE TITLE
duplicate listen options for 0.0.0.0:443 when multiple servers enable http3

### ISSUE THREAD

**Issue by haohetao** [cloudflare/quiche#389]
server {
        listen  80;
        # Enable QUIC and HTTP/3.
        listen 443 quic reuseport;
        # Enable HTTP/2 (optional).
        listen 443 ssl http2;
.......
}
server {
        listen  80;
        # Enable QUIC and HTTP/3.
        listen 443 quic reuseport;
        # Enable HTTP/2 (optional).
        listen 443 ssl http2;
......
}
the nginx show duplicate listen options for 0.0.0.0:443

**Comment by junhochoi** [comment]
Please see #236 for possible workaround. Thanks.

**Comment by haohetao** [comment]
@junhochoi 
Thanks
The reuseport can only be used once.

**Comment by junhochoi** [comment]
Thanks! I'll close this ticket. Feel free to ask a new question if you encountered a new issue.
