### ISSUE TITLE
i got some wrong when i build the nginx

### ISSUE THREAD

**Issue by Yancongyu** [cloudflare/quiche#394]
CentOS Linux release 7.3.1611 (Core)
cmake version 3.15.4
rustc 1.41.1 (f3e1a954d 2020-02-24)
cargo 1.41.0 (626f0f40e 2019-12-03)
 
and i got the wrong like this

[ 62%] Building CXX object crypto/CMakeFiles/crypto_test.dir/fipsmodule/ec/p256-x86_64_test.cc.o
cd /tmp/quiche/deps/boringssl/build/crypto && /usr/bin/c++  -DBORINGSSL_DISPATCH_TEST -DBORINGSSL_IMPLEMENTATION -I/tmp/quiche/deps/boringssl/third_party/googletest/include -I/tmp/quiche/deps/boringssl/crypto/../include  -Werror -Wformat=2 -Wsign-compare -Wmissing-field-initializers -Wwrite-strings -Wvla -ggdb -Wall -fvisibility=hidden -fno-common -Wno-free-nonheap-object -Wmissing-declarations -std=c++11 -fno-exceptions -fno-rtti -Wshadow   -o CMakeFiles/crypto_test.dir/fipsmodule/ec/p256-x86_64_test.cc.o -c /tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc
In file included from /tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc:22:0:
/tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc: In function ‘std::string FieldElementToString(const uint64_t*)’:
/tmp/quiche/deps/boringssl/crypto/../include/openssl/bn.h:156:28: error: expected ‘)’ before ‘PRIx64’
 #define BN_HEX_FMT2 "%016" PRIx64
                            ^
/tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc:195:36: note: in expansion of macro ‘BN_HEX_FMT2’
     BIO_snprintf(buf, sizeof(buf), BN_HEX_FMT2, a[i]);
                                    ^
/tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc:195:53: error: conversion lacks type at end of format [-Werror=format=]
     BIO_snprintf(buf, sizeof(buf), BN_HEX_FMT2, a[i]);
                                                     ^
/tmp/quiche/deps/boringssl/crypto/fipsmodule/ec/p256-x86_64_test.cc:195:53: error: too many arguments for format [-Werror=format-extra-args]
cc1plus: all warnings being treated as errors
make[4]: *** [crypto/CMakeFiles/crypto_test.dir/fipsmodule/ec/p256-x86_64_test.cc.o] Error 1
make[4]: Leaving directory `/tmp/quiche/deps/boringssl/build'
make[3]: *** [crypto/CMakeFiles/crypto_test.dir/all] Error 2
make[3]: Leaving directory `/tmp/quiche/deps/boringssl/build'
make[2]: *** [all] Error 2
make[2]: Leaving directory `/tmp/quiche/deps/boringssl/build'
make[1]: *** [../quiche/deps/boringssl/.openssl/include/openssl/ssl.h] Error 2
make[1]: Leaving directory `/tmp/nginx-1.16.1'
make: *** [build] Error 2

**Comment by ghedo** [comment]
What C/C++ compiler are you using and which version? It looks like it can't build BoringSSL for whatever reason, so it might be too old, though this is not really a quiche issue and there's not much we can do about it as BoringSSL is just one of our dependencies.

**Comment by Yancongyu** [comment]
thx for reply.
