### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by candrews** [cloudflare/quiche#396]
Curl 7.69.0 has been released: https://github.com/curl/curl/releases/tag/curl-7_69_0
It includes this change: https://github.com/curl/curl/commit/7fc63d72333a36225d39c5b5624df29217136c12 and that requires a version of quiche with https://github.com/cloudflare/quiche/pull/340 - and no such release of quiche has been made yet.

Can you please release quiche 0.3.0 so there is a released version of quiche that works with the latest version of curl?

**Comment by haohetao** [comment]
handclap

**Comment by haohetao** [comment]
However, the latest version is draft-27

**Comment by ghedo** [comment]
I just published https://github.com/cloudflare/quiche/releases/tag/0.3.0 :tada:

**Comment by candrews** [comment]
@ghedo 0.3.0 is not available on crates.io: https://crates.io/crates/quiche/0.3.0

Did you publish it?

I also noticed that one of the builds failed: https://github.com/cloudflare/quiche/runs/505575333

**Comment by ghedo** [comment]
Ah, sorry I got distracted. It's published now.

The build failure is due to a new clippy releases that added new warnings, it's innocuous, but https://github.com/cloudflare/quiche/pull/415 should fix the problem.
