### ISSUE TITLE
Can this connection take another h3 stream?

### ISSUE THREAD

**Issue by bagder** [cloudflare/quiche#397]
libcurl's internals try to "fill up" existing connections with streams before it creates a new one for the next new transfer.

Assuming we have N current h3 streams going over a single QUIC connection, is there a way I can ask quiche if there's room for another h3 request over that connection?

**Comment by ghedo** [comment]
The only way currently would be to try sending the request and then checking for the `TransportError(StreamLimit)` error in Rust, or `QUICHE_H3_ERR_TRANSPORT_ERROR` in C.
