### ISSUE TITLE
the different between quiche-client, client and http3-client in use scenarios

### ISSUE THREAD

**Issue by ktxu1224** [cloudflare/quiche#412]
Hi, thx for the codes, it works pretty good. 
I just started using this project, but I encountered some puzzles, as follows:
(1) what's the difference between the built executable target, the quiche-client which is built from the file quiche/tools/apps/src/bin/,  client and http3-client, which is built from the source files in dir quiche/examples/? In other word,  what are they used for?

**Comment by junhochoi** [comment]
examples/* contains a simple client & server written in C and Rust. This is very minimal so not much features. This is for your reference when you start to use quiche.

quiche-{client-server} provides more features and options, so recommended for any testing purposes.

**Comment by ghedo** [comment]
Closing nthis ow as it's been answered. Feel free to reopen if more information is needed.
