### ISSUE TITLE
Custom Roots of Trust?

### ISSUE THREAD

**Issue by ctiller** [cloudflare/quiche#418]
I'm currently putting together something that needs to have a set of certs trusted that are not the OS defaults. Any chance of adding some call path to `quiche::Context` to call through to `SSL_CTX_load_verify_locations` instead of `SSL_CTX_set_default_verify_paths`?

I'm happy to type the code after checking the design.

I'd be thinking about adding to Context:

```
pub fn load_verify_locations_from_file(&mut self, file: &str);
```

**Comment by LPardue** [comment]
would your use case be satisfied by setting `SSL_CERT_DIR` or `SSL_CERT_FILE` env vars?

**Comment by ctiller** [comment]
Short term, probably yes. Long term - it's unlikely.
Right now we could force it at application startup with a
std::env::set_var, but longer term it's unclear that process-wide is the
right thing to do.

**Comment by ghedo** [comment]
@ctiller yeah, that sounds good to me, though might want to have both `_from_file()` and `_from_directory()` variants.

**Comment by ctiller** [comment]
The environment variable approach hasn't worked out well in the past few
days - we end up in situations in unit tests where we want >1 option set.

I'm going to put something together and send a PR.
