### ISSUE TITLE
unable to build client for android below is error report, please suggest

### ISSUE THREAD

**Issue by mohanbright** [cloudflare/quiche#425]
Pavans-Air-2:StudioWorkspace pavankumar$ cargo ndk --target aarch64-linux-android --android-platform 21 -- build
   Compiling quiche v0.3.0 (/Users/pavankumar)
error: failed to run custom build command for `quiche v0.3.0 (/Users/pavankumar)`

Caused by:
  process didn't exit successfully: `/Users/pavankumar/target/debug/build/quiche-c1f13e1e392ed89a/build-script-build` (exit code: 101)
--- stdout
Info: default compiler flags are disabled
Info: default compiler flags are disabled
running: "cmake" "/Users/pavankumar/deps/boringssl" "-DANDROID_ABI=arm64-v8a" "-DCMAKE_TOOLCHAIN_FILE=/Users/pavankumar/Library/Android/sdk/ndk/21.0.6113669/build/cmake/android.toolchain.cmake" "-DANDROID_NATIVE_API_LEVEL=21" "-DANDROID_STL=c++_shared" "-DCMAKE_INSTALL_PREFIX=/Users/pavankumar/target/aarch64-linux-android/debug/build/quiche-68cc921a1531ece1/out" "-DCMAKE_C_FLAGS=" "-DCMAKE_CXX_FLAGS=" "-DCMAKE_BUILD_TYPE=Debug"
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/pavankumar/target/aarch64-linux-android/debug/build/quiche-68cc921a1531ece1/out/build
running: "cmake" "--build" "." "--target" "bssl" "--config" "Debug" "--"
[  0%] Built target global_target
[  6%] Built target fipsmodule
[  8%] Generating err_data.c

--- stderr
android arch=aarch64 add ANDROID_ABI=arm64-v8a
android toolchain=/Users/pavankumar/Library/Android/sdk/ndk/21.0.6113669/build/cmake/android.toolchain.cmake
/bin/sh: go: command not found
make[3]: *** [crypto/err_data.c] Error 127
make[3]: *** Deleting file `crypto/err_data.c'
make[2]: *** [crypto/CMakeFiles/crypto.dir/all] Error 2
make[1]: *** [tool/CMakeFiles/bssl.dir/rule] Error 2
make: *** [bssl] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

build script failed, must exit now', /Users/pavankumar/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.42/src/lib.rs:861:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by junhochoi** [comment]
```
/bin/sh: go: command not found
```
I think you need to install golang (boringssl need it to build)

**Comment by piavan7** [comment]
I installer golang as well still same error and set path in environment variable too

**Comment by junhochoi** [comment]
Do you still have same error message `go: command not found` after golang installed? Can you show what is your output of `go` in your shell?

**Comment by piavan7** [comment]
issue was with go its fixed thank you
