### ISSUE TITLE
QUIC datagram extensions

### ISSUE THREAD

**Issue by xanathar** [cloudflare/quiche#430]
Hi,
Is there any intention/plan of supporting the current draft of datagram extensions as defined by https://tools.ietf.org/html/draft-ietf-quic-datagram-00 ?

In case this is not in the plans, would such a contribution be welcome or is it considered out of scope ?

**Comment by ctiller** [comment]
I'd be interested in being able to use this.

**Comment by LPardue** [comment]
I have a separate fork of quiche with rough DATAGRAM support.

The implementation is pretty straightforward, the trickier part is getting the API correct.

Now that the DATAGRAM extension has been adopted by the QUIC WG there is a stronger case for looking at this more seriously. Having people interested in using it makes a better case for getting feedback and coverage of the code.

**Comment by ctiller** [comment]
Happy to help iterate on the API.

**Comment by xanathar** [comment]
I did a quick rebase of LPardue's forked branch on top of master (https://github.com/xanathar/quiche/commits/datagrams-0.3.0).

This is the current API I extracted diffing the files (as currently implemented, of course):

```
    // In lib.rs:
    pub fn Config::set_max_datagram_frame_size(&mut self, v: u64)
    pub fn Connection::dgram_send(&mut self, buf: &[u8]) -> Result<()> 
    pub fn Connection::dgram_recv(&mut self) -> Result<Vec<u8>>

    // In webtransport/mod.rs:
    pub enum Error
    pub const QUICTRANSPORT_ALPN: &[u8]
    pub type Result<T>
    pub fn QuicTransport::with_transport(conn: &mut super::Connection, origin: &str, path: &str) -> Result<QuicTransport>
    pub fn QuicTransport::dgram_send(&mut self, conn: &mut super::Connection, buf: &[u8]) -> Result<()>

    // In h3/ffi.rs:
    #[no_mangle] pub extern fn quiche_h3_datagram_event_type(ev: &h3::DatagramEvent) -> u32
    pub enum DatagramEvent
    pub fn dgram_send(&mut self, conn: &mut super::Connection, flow_id: u64, buf: &[u8]) -> Result<()>
    pub fn poll_dgram(&mut self, conn: &mut super::Connection) -> Result<(u64, DatagramEvent)>
    pub fn process_dgram(&mut self, conn: &mut super::Connection) -> Result<(u64, DatagramEvent)>
```

I'm currently focusing on the quic part (i.e. no http3 things).

The `Connection::dgram_recv` API has a signature which is radically different from `Connection::stream_recv`, but something like `pub fn dgram_recv(&mut self, out: &mut [u8]) -> Result<(usize, bool)>` would require an extra copy of the buffer (but maybe it would allow an easier interop with C).

As far as C interop is concerned, I drafted a commit with a working C interface to the datagram API: https://github.com/xanathar/quiche/commit/1dbb0b0a3e3c043fe403ae636fa65516b1262ed6 ; feedbacks are welcome (specially around `quiche_conn_dgram_free`).

One question on the functional aspect: in theory the datagram extension draft says datagrams must be subject to the flow control which in quiche is represented by the send api limits (or whatever is returned by `stream_capacity`). Does this mean that `dgram_send` should be limited by the application ? if so, should we expose something more ?

**Comment by LPardue** [comment]
Thanks for looking at this. Ideally the datagram work should be broken into three pieces that reflect the maturity of the standards process: QUIC datagram, H3 datagram and WebTransport. WebTransport is different enough that I should spin it off into a separate PR and we can ignore it for now.

stream_recv allows the caller to read as much or as little as they want. IIRC I decided to make the dgram_recv signature different because it doesn't make sense to read a partial datagram. Given the pains you've had to go through to get this working with the C API I'm not opposed to changing dgram_recv, it would just need some checks to ensure the output buffer is large enough for the received datagram. Providing a large enough buffer is pretty easy because the receiving endpoint set's its own max_datagram_frame_size TP.

**Comment by xanathar** [comment]
I don't know. On one side it would allow for cleaner interop, on the other if one is using datagrams is probably for performance sensitive stuff, and saving a copy could be worth, specially considering that, with datagrams coming out of order, duplicated etc. it's likely that the application cannot specify the final location but needs yet another copy to reassemble the message in any case. I'm seriously on the fence on this.

As an aside, I added some datagram calls to a C++ application I had which is also using a stream and sometimes it stops working; I'm debugging it right now. 99% is some mistake on my side, but it seems it's spinning in `while let Some(len) = self.dgram_queue.peek_writable()`. Will keep you updated.

**Comment by xanathar** [comment]
I've reasoned a while on the interface which datagrams extensions could have to the application code, and this are a couple of my proposals, please provide feedback.

### Scope

This proposal works only around the QUIC part. I have not considered (yet) the H3 part of the problem, nor the WebTransport, to start from the foundations.
Also, I tried to do an effort towards having an API which most closely matches the other APIs in quiche, if no real drawback comes from this (there are trade-offs to be considered).

### Rationales

I took into account three points of rationale from days of testing this in (private) real-world prototypes.

First is having some control on the outgoing queue (that is the queue of packets to be sent). This is to handle several scenarios where datagrams which were meant to be sent asap, now have lost their "value"; for example a typical case is an application discarding old stale datagrams when a new datagram of the same type is appended to the queue, or prioritizing datagrams.
Typical cases here are previous video frames after too much time has passed, videogame state snapshots, audio packets after a given delta of time has passed (if no speed-modulation is done) or really any data which is either cumulative and idempotent or has a maximum useful age.

Second, a topic raised in this issue and https://github.com/LPardue/quiche/pull/1 was whether it was best to keep the `dgram_recv` interface as it was in LPardue's branch (`dgram_recv(&mut self) -> Result<Vec<u8>>`) or it was better to have it in a form more similar to `stream_recv` which also allows for an easier to use interface to C at the expense of an extra memory copy (though not allocation) at every call (`dgram_recv(&mut self, out: &mut [u8])`). Details can be found at https://github.com/LPardue/quiche/pull/1, but the long story short is that there seems to be no or negligible advantages in having one less copy of data, and the cleaner interface is a winner; if what found in that issue proves to be incorrect, it’s a matter of amending `dgram_recv`.

Third - minor - for naming uniformity with `Config::set_max_datagram_frame_size`, which cannot be renamed to `..dgram..` because it refers to a specific QUIC transport parameter, I renamed all the methods from `dgram_something` to `datagram_something`. 

### Proposal 1

This proposal is the one with the simplest interface. Everything stays the same as in LPardue's branch, except for minor details:

* The ability to configure the size of the datagram queues (i.e. 2 config calls)
* A `datagram_purge_outgoing` to allow applications to remove datagrams waiting to be sent, which are outdated for some reason.

The drawback of this approach, which is far cleaner than my second proposal, is that applications can easily purge outdated packets in the sending queue, but not reprioritize them (other then purging the queue temporarily, and re-adding them in the desired order). Still this can be extended, for example with a `datagram_send_urgent` or similar, in a second time, **when and if** it proves to be needed.

```rust
/// Sets the maximum size of the datagram sende queue 
pub fn Config::set_datagram_send_queue_size(&mut self, size: u64) -> Result<()>;
/// Sets the maximum size of the datagram received queue 
pub fn Config::set_datagram_recv_queue_size(&mut self, size: u64) -> Result<()>;
/// Sets the transport's max_datagram_frame_size
pub fn Config::set_max_datagram_frame_size(&mut self, v: u64);

/// Sends a datagram on a connection
pub fn Connection::datagram_send(&mut self, buf: &[u8]) -> Result<()>;
/// Receives a datagram from the connection
pub fn Connection::datagram_recv(&mut self, out: &mut [u8]) -> Result<usize>;
/// Iterates over the outgoing queue and purges datagrams matching the filter
pub fn Connection::datagram_purge_outgoing<F>(&mut self, filter: F) -> Result<()> 
    where F: FnMut(&[u8]) -> bool;
```


### Proposal 2

This proposal is the one with the most control over the sending queue. An object with the `DatagramsOutgoingQueue` trait can be passed by the application to customize the behavior of the sending queue to its preference.

```rust
/// An implementation may be passed by the application, otherwise the default one
/// will be used. 
pub trait DatagramsOutgoingQueue
where
    Self: std::fmt::Debug,
{
    /// Adds a datagram to the outgoing queue
    pub fn push_datagram(&mut self, data: &[u8]) -> Result<()> ;
    /// Returns the size of the next outgoing datagram to be sent, or None.
    pub fn peek_datagram(&self) -> Option<usize>;
    /// Returns the next buffer to be sent (or None). 
    pub fn pop_datagram(&mut self) -> Result<&[u8]>;
}

/// Sets the outgoing datagram queue to be used, the default one is used otherwise
pub fn Config::set_datagram_send_queue(&mut self, &queue: DatagramsOutgoingQueue);
/// Sets the maximum size of the datagram received queue 
pub fn Config::set_datagram_recv_queue_size(&mut self, size: u64) -> Result<()>;
/// Sets the transport's max_datagram_frame_size
pub fn Config::set_max_datagram_frame_size(&mut self, v: u64);

/// Sends a datagram on a connection, queuing it to the current DatagramsOutgoingQueue
pub fn Connection::datagram_send(&mut self, buf: &[u8]) -> Result<()>;
/// Receives a datagram from the connection
pub fn Connection::datagram_recv(&mut self, out: &mut [u8]) -> Result<usize>;
```

As said, feedback is very welcome, as is any alternative, etc.

**Comment by LPardue** [comment]
@xanathar proposal 2 is an interesting alternative. How do you see an application loop working with this? Something like:

1. conn.datagram_send("foo");
2. conn.datagram_send("bar");
3. conn.datagram_send("baz");
4. conn.send(...) which internally will get around to calling self.DatagramsOutgoingQueue.pop()

Do you imagine an ability to purge items in DatagramsOutgoingQueue, which may be public or private depending on need?

**Comment by xanathar** [comment]
yes, proposal 2 is exactly how you described; the ability to purge items in DatagramsOutgoingQueue would be there, since the object with the DatagramsOutgoingQueue trait would be provided by the application itself (with a default implementation which doesn't allow it, for those who don't need that level of control).
