### ISSUE TITLE
Disable early-data in nginx patch

### ISSUE THREAD

**Issue by PethrusG** [cloudflare/quiche#440]
Hi,
First, thanks for providing nginx with a patch for your quiche QUIC implementation!

I'm using your implementation for my Master's Thesis and have a question regarding Early-Data (0-RTT). I want it to be disabled in nginx when using your quiche implementation. 

As far as I can see, it is disabled because quiche_config_enable_early_data() in quiche/src/ffi.rs is never called in the nginx file src/http/v3/ngx_http_v3_module.c

Am I right that early data is disabled by default in your nginx patch?

Thanks in advance!

**Comment by ghedo** [comment]
In order to enable early data (including for QUIC) in NGINX, you'd need to explicitily set `ssl_early_data` to `on`.

So yes, early data is disabled for QUIC by default so you don't need to do anything to disable it.
