### ISSUE TITLE
qlog: HandshakeDone frame type

### ISSUE THREAD

**Issue by agrover** [cloudflare/quiche#441]
Recent drafts added a new HandshakeDone frame type, please support it in qlog crate. Or does this need to wait for qlog spec to be updated? Thanks.

**Comment by LPardue** [comment]
Lol, see https://github.com/cloudflare/quiche/pull/437

**Comment by agrover** [comment]
dupe, thanks y'all.

**Comment by ghedo** [comment]
It's ok, we can close this when the PR is merged.
