### ISSUE TITLE
TlsFail on running client against local server.

### ISSUE THREAD

**Issue by piano-man** [cloudflare/quiche#444]
When I run the command - 
cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://127.0.0.1:4433/  against a server running locally, it returns with - 
[2020-04-04T17:21:20.293355000Z ERROR quiche_client] recv failed: TlsFail.

I'm running Ubuntu 19.10

**Comment by LPardue** [comment]
If you're testing with the a self-signed cert it will be untrested and cause a failure. You'll need to run the client with `--no-verify`  in order to avoid the certificate check

**Comment by piano-man** [comment]
On running with - 
cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://127.0.0.1:4433/ --no-verify
it just prints Not Found!
Is that the expected response ?

**Comment by LPardue** [comment]
Yes. You asked for the path "/" and no content was found. Try putting some resources in your server root and requesting them (description for that is found in quiche-server help)

**Comment by piano-man** [comment]
Oh, I see. Thanks !
