### ISSUE TITLE
Quiche use in windows and relevant  errors

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#450]
I built quiche as following steps:
 1- install rust language
2- install perl 
3-install go
4-install NASM
5- git clone --recursive https://github.com/cloudflare/quiche
6-cargo build
and I got quiche.lib, quiche.dll.lib and quiche.dll.
But when I used quiche in my project in visual studio 2019 I got these errors:
![Capture11](https://user-images.githubusercontent.com/51900859/78747951-9d67e400-791f-11ea-9d96-f3503656df24.PNG)

**Comment by foroughmajidi** [comment]
Could I add these lines  to solve errors in quiche.h?
#if SIZE_MAX == ULONG_MAX
    typedef long ssize_t;       /* linux 64 bits */
#elif SIZE_MAX == ULLONG_MAX
    typedef long long ssize_t;  /* windows 64 bits */
#endif

**Comment by ghedo** [comment]
I _think_ a better solution would be to do something like:
```c
#ifdef _MSC_VER
#include <BaseTsd.h>
#define ssize_t SSIZE_T
#endif
```
though I don't have a Windows machine to try this on.

**Comment by foroughmajidi** [comment]
> I _think_ a better solution would be to do something like:
> 
> ```c
> #ifdef _MSC_VER
> #include <BaseTsd.h>
> #define ssize_t SSIZE_T
> #endif
> ```
> 
> though I don't have a Windows machine to try this on.

Thanks it was ok.
