### ISSUE TITLE
thread 'main' panicked at 'initial send failed: TlsFail', src/libcore/result.rs:1188:5 

### ISSUE THREAD

**Issue by piano-man** [cloudflare/quiche#451]
System :- Ubuntu 18.04

On pulling the latest version of the repo, my client runs into the following error :- 

thread 'main' panicked at 'initial send failed: TlsFail', src/libcore/result.rs:1188:5                                                                                      
stack backtrace:                                                                                                                                                               
0:     0x55e6254db924 - backtrace::backtrace::libunwind::trace::heb43798aede8bd30                                                                                                                       
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-
0.3.40/src/backtrace/libunwind.rs:88                                               1:     0x55e6254db924 - 
backtrace::backtrace::trace_unsynchronized::had2ba7dec4bd2732                                                                                                                   
at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66                                                     
2:     0x55e6254db924 - std::sys_common::backtrace::_print_fmt::hda61f46e822731b2                                                                                                                       
at src/libstd/sys_common/backtrace.rs:84                                                                                                        
3:     0x55e6254db924 - <std::sys_common::backtrace::_print::DisplayBacktrace as 
core::fmt::Display>::fmt::hfe37fa5de6572965                                                                            at 
src/libstd/sys_common/backtrace.rs:61                                                                                                        
4:     0x55e6254f70ac - core::fmt::write::h74887d18db27282c                                                                                                                                             
at src/libcore/fmt/mod.rs:1025                                                                                                                  
5:     0x55e6254d76a7 - std::io::Write::write_fmt::h6808f3d5eceed5e5                                                                                                                                    
at src/libstd/io/mod.rs:1426                                                                                                                    
6:     0x55e6254dd9ae - std::sys_common::backtrace::_print::hcc0fd4b3552039ef                                                                                                                           
at src/libstd/sys_common/backtrace.rs:65                                                                                                        
7:     0x55e6254dd9ae - std::sys_common::backtrace::print::h1c9c5c1c0505592d                                                                                                                            
at src/libstd/sys_common/backtrace.rs:50                                                                                                        
8:     0x55e6254dd9ae - std::panicking::default_hook::{{closure}}::hefb6085c1ab83a59                                                                                                                    
at src/libstd/panicking.rs:193                                                                                                                  
9:     0x55e6254dd6a1 - std::panicking::default_hook::h1b037d2bf0657ab3                                                                                                                                 
at src/libstd/panicking.rs:210                                                                                                                 
10:     0x55e6254de02b - std::panicking::rust_panic_with_hook::h787d7f532b084b9a                                                                                                                         
at src/libstd/panicking.rs:471                                                                                                                 
11:     0x55e6254ddbde - rust_begin_unwind                                                                                                                                                               
at src/libstd/panicking.rs:375                                                                                                                 
12:     0x55e6254f473e - core::panicking::panic_fmt::h76b979c035808e69                                                                                                                                   
at src/libcore/panicking.rs:84                                                                                                                 
13:     0x55e6254f4837 - core::result::unwrap_failed::hca6a012bfa3eb903                                                                                                                                  
at src/libcore/result.rs:1188                                                                                                                  
14:     0x55e624ed4def - core::result::Result<T,E>::expect::h7793fe319a108d7e                                                                                                                            
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libcore/result.rs:983                                                                   
15:     0x55e624edc212 - quiche_client::main::h89431a411b5c3fde                                                                                                                                          
at src/bin/quiche-client.rs:164                                                                                                                
16:     0x55e624edb0b0 - std::rt::lang_start::{{closure}}::h93cc05a4786a9865                                                                                                                             
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
17:     0x55e6254dda73 - std::rt::lang_start_internal::{{closure}}::h0760fb8bd9f1a4c7                                                                                                                    
at src/libstd/rt.rs:52                                                                                                                         18:     
0x55e6254dda73 - std::panicking::try::do_call::hccaa7cebf2335ab2                                                                                                                                 
at src/libstd/panicking.rs:292                                                                                                                 
19:     0x55e6254e0faa - __rust_maybe_catch_panic                                                                                                                                                        
at src/libpanic_unwind/lib.rs:78                                                                                                               
20:     0x55e6254de4c0 - std::panicking::try::h3ce8e2e4440720f0                                                                                                                                          
at src/libstd/panicking.rs:270                                                                                                                 
21:     0x55e6254de4c0 - std::panic::catch_unwind::h2a767bac361346af                                                                                                                                     
at src/libstd/panic.rs:394                                                                                                                     
22:     0x55e6254de4c0 - std::rt::lang_start_internal::h14e7168ba039f170                                                                                                                                 
at src/libstd/rt.rs:51                                                                                                                        
 23:     0x55e624edb089 - std::rt::lang_start::hbd39d689285f8764                                                                                                                                          
at /rustc/5e1a799842ba6ed4a57e91f7ab9435947482f7d8/src/libstd/rt.rs:67                                                                         
24:     0x55e624edf79a - main                                                                                                                                               
25:     0x7fe8d9b05b97 - __libc_start_main                                                                                                                                  
26:     0x55e624ed02aa - _start                                                                                                                                             
27:                0x0 - <unknown>

Note :- It works fine with an earlier version of the repo.

**Comment by junhochoi** [comment]
If you are able to reproduce, can you provide a whole command line option with RUST_LOG=trace? Also which server are you connecting to?

Also if you already tried older repo, make sure you also sync submodules (boringssl) when update. Make a fresh checkout, or `git submodule update --init --recursive` will do.

**Comment by piano-man** [comment]
Oh,` git submodule update --init --recursive` fixes this. Thanks !
