### ISSUE TITLE
What is the /dev/urandom equivalent on Windows

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#457]
I used server.c and client.c examples but I couldn't find anything instead of /dev/urandom on windows.
Please inform me if there is a solution .
thanks.

**Comment by foroughmajidi** [comment]
I tested client and server.c with a sample file of /dev/urandom on windows but even though  I got this error:

![Capture15](https://user-images.githubusercontent.com/51900859/79191048-8cfdb080-7dda-11ea-9826-e680e58bd97e.PNG)

This is a code on client.c:

int main(int argc, char* argv[]) {
    
    const struct addrinfo hints = {
        .ai_family = PF_UNSPEC,
        .ai_socktype = SOCK_DGRAM,
        .ai_protocol = IPPROTO_UDP
    };

    quiche_enable_debug_logging(debug_log, NULL);
    int iResult;
    WSADATA wsaData;
    iResult = WSAStartup(MAKEWORD(2, 2), &wsaData);
   
    struct addrinfo* peer;
  if (getaddrinfo("localhost", "5555", &hints, &peer) != 0) {
        perror("failed to resolve host");
        return -1;
    }

    int sock = socket(peer->ai_family, SOCK_DGRAM, 0);
    if (sock < 0) {
        perror("failed to create socket");
        return -1;
    }
    u_long nonblocking_enabled = TRUE;

    if (ioctlsocket(sock, FIONBIO, &nonblocking_enabled) != 0) {
        perror("failed to make socket non-blocking");
        return -1;
    }

    if (connect(sock, peer->ai_addr, peer->ai_addrlen) < 0) {
        perror("failed to connect socket");
        return -1;
    }

    quiche_config* config = quiche_config_new(0xbabababa);
    if (config == NULL) {
        fprintf(stderr, "failed to create config\n");
        return -1;
    }

    quiche_config_set_application_protos(config,
        (uint8_t*)"\x05hq-27\x05hq-25\x05hq-24\x05hq-23\x08http/0.9", 15);

    quiche_config_set_max_idle_timeout(config, 5000);
    quiche_config_set_max_packet_size(config, MAX_DATAGRAM_SIZE);
    quiche_config_set_initial_max_data(config, 10000000);
    quiche_config_set_initial_max_stream_data_bidi_local(config, 1000000);
    quiche_config_set_initial_max_stream_data_uni(config, 1000000);
    quiche_config_set_initial_max_streams_bidi(config, 100);
    quiche_config_set_initial_max_streams_uni(config, 100);
    quiche_config_set_disable_active_migration(config, true);

    if (getenv("SSLKEYLOGFILE")) {
        quiche_config_log_keys(config);
    }

    uint8_t scid[LOCAL_CONN_ID_LEN];
    

    BOOL bTest = FALSE;
    DWORD dwBytesRead;
    DWORD dwNumRead = 0;
    HANDLE hFile = CreateFile(L"E:\\urandom.txt", GENERIC_READ, 0, NULL, OPEN_EXISTING, FILE_ATTRIBUTE_NORMAL, NULL);
    
    if (hFile == INVALID_HANDLE_VALUE) {
        printf("Source file not opened. Error %u\n", GetLastError());
        return EXIT_FAILURE;
    }
   
    bool ok = true;
        if (!ReadFile(hFile, &scid, sizeof(scid), &dwBytesRead, NULL)) {
            printf("Source file not read from. Error %u\n", GetLastError());
            ok = false;
            return -1;
        }
  

    quiche_conn* conn = quiche_connect(host, (const uint8_t*)scid,
        sizeof(scid), config);
    if (conn == NULL) {
        fprintf(stderr, "failed to create connection\n");
        return -1;
    }

    struct conn_io* tmp = (conn_io*) malloc(sizeof(conn_io ));
    if (tmp == NULL) {
        fprintf(stderr, "failed to allocate connection IO\n");
        return -1;
    }

    tmp->sock = sock;
    tmp->conn = conn;

    ev_io watcher;

    struct ev_loop* loop = ev_default_loop(0);

    ev_io_init(&watcher, recv_cb, tmp->sock, EV_READ);
    ev_io_start(loop, &watcher);
    watcher.data = tmp;

    ev_init(&tmp->timer, timeout_cb);
    tmp->timer.data = tmp;

    flush_egress(loop, tmp);

    ev_loop(loop, 0);

    freeaddrinfo(peer);

    quiche_conn_free(conn);

    quiche_config_free(config);

    return 0;
}

**Comment by ghedo** [comment]
Windows ahs [`RtlGenRandom`](https://docs.microsoft.com/en-us/windows/win32/api/ntsecapi/nf-ntsecapi-rtlgenrandom) for generating random data.

**Comment by foroughmajidi** [comment]
Thanks for your favor. 
Would you please help me about libev's  error?
