### ISSUE TITLE
quiche_conn_recv() == -10 on windows

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#467]
I run client.c and server.c on windows  but I got this error:
failed to process packet: -10 returned from the quiche_conn_recv() function

I set port:5555  and host="localhost"

I can't understand why this error occurred?
 Can I get more debug info or logging somehow to better understand the details of this failure?

![Capture20](https://user-images.githubusercontent.com/51900859/79686461-5fa76d00-81f5-11ea-8b6d-1ad1a0f81e69.PNG)
![Capture21](https://user-images.githubusercontent.com/51900859/79686462-62a25d80-81f5-11ea-9eaa-c81cfe383675.PNG)

**Comment by LPardue** [comment]
think this will be fixed by https://github.com/cloudflare/quiche/pull/454

**Comment by foroughmajidi** [comment]
Based on what I've got from your words.I have done this before.

![Capture22](https://user-images.githubusercontent.com/51900859/79719470-7ef4d780-8293-11ea-92ce-9cddca482286.PNG)

Is my understanding true? or shall I test another way?

**Comment by foroughmajidi** [comment]
I downloaded the new version of example including new changes like:
   quiche_config_load_cert_chain_from_pem_file(config, "./cert.crt");
    quiche_config_load_priv_key_from_pem_file(config, "./cert.key");
but I got the same error. 
I run client.c and server.c in visual studio and I copy cert.crt and key.crt in my project directory .
Please help me if there is any more corrections needed ?

**Comment by foroughmajidi** [comment]
Please help me for my problem ,shall I test another way?
I run client.c and server.c in visual studio and I copy cert.crt and key.crt in my project directory .
Is this way correct?

**Comment by LPardue** [comment]
In order to help diagnose if there are any issues we need a full trace log and the context of what you are trying to do. Please don't paste screenshots of the log output.

**Comment by foroughmajidi** [comment]
Thanks for your recommendation.
In the following  server.c and client.c examples on windows can be seen:

**server.c**
   `    
    #define WIN32_LEAN_AND_MEAN
    #include <Windows.h>
    #include <WinSock2.h>
    #include <WS2tcpip.h> /* socklen_t */
   
    #pragma comment(lib, "ws2_32.lib")
   
    #include <io.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include <stdint.h>
    #include <string.h>
    #include <errno.h>
    #include <stdint.h>
    #include <stdbool.h>
    #include <fcntl.h>
    #include<corecrt_io.h>
    #include <inttypes.h>
    #include<wincrypt.h>
    #include<quiche.h>
    
    
    #include"uthash.h"
    
    
     /* Libev. */
    #include "libev.h"
    
    /* Port to listen on. */
    
    #define LOCAL_CONN_ID_LEN 16
    
    #define MAX_DATAGRAM_SIZE 1350
    
    #define MAX_TOKEN_LEN \
        sizeof("quiche") - 1 + \
        sizeof(struct sockaddr_storage) + \
        QUICHE_MAX_CONN_ID_LEN
    
    struct connections {
        int sock;
    
        struct conn_io* h;
    };
    
    struct conn_io {
        ev_timer timer;
    
        int sock;
    
        uint8_t cid[LOCAL_CONN_ID_LEN];
    
        quiche_conn* conn;
    
        struct sockaddr_storage peer_addr;
        socklen_t peer_addr_len;
    
        UT_hash_handle hh;
    };
    
    static quiche_config* config = NULL;
    
    static struct connections* conns = NULL;
    
    static void timeout_cb(EV_P_ ev_timer* w, int revents);
    
    static void debug_log(const char* line, void* argp) {
        fprintf(stderr, "%s\n", line);
    }
    
    static void flush_egress(struct ev_loop* loop, struct conn_io* conn_io) {
        static uint8_t out[MAX_DATAGRAM_SIZE];
    
        while (1) {
            ssize_t written = quiche_conn_send(conn_io->conn, out, sizeof(out));
    
            if (written == QUICHE_ERR_DONE) {
                fprintf(stderr, "done writing\n");
                break;
            }
    
            if (written < 0) {
                fprintf(stderr, "failed to create packet: %zd\n", written);
                return;
            }
    
            ssize_t sent = sendto(conn_io->sock, out, written, 0,
                (struct sockaddr*) & conn_io->peer_addr,
                conn_io->peer_addr_len);
            if (sent != written) {
                perror("failed to send");
                return;
            }
    
            fprintf(stderr, "sent %zd bytes\n", sent);
        }
    
        double t = quiche_conn_timeout_as_nanos(conn_io->conn) / 1e9f;
        conn_io->timer.repeat = t;
        ev_timer_again(loop, &conn_io->timer);
    }
    
    static void mint_token(const uint8_t* dcid, size_t dcid_len,
        struct sockaddr_storage* addr, socklen_t addr_len,
        uint8_t* token, size_t* token_len) {
        memcpy(token, "quiche", sizeof("quiche") - 1);
        memcpy(token + sizeof("quiche") - 1, addr, addr_len);
        memcpy(token + sizeof("quiche") - 1 + addr_len, dcid, dcid_len);
    
        *token_len = sizeof("quiche") - 1 + addr_len + dcid_len;
    }
    
    static bool validate_token(const uint8_t* token, size_t token_len,
        struct sockaddr_storage* addr, socklen_t addr_len,
        uint8_t* odcid, size_t* odcid_len) {
        if ((token_len < sizeof("quiche") - 1) ||
            memcmp(token, "quiche", sizeof("quiche") - 1)) {
            return false;
        }
    
        token += sizeof("quiche") - 1;
        token_len -= sizeof("quiche") - 1;
    
        if ((token_len < addr_len) || memcmp(token, addr, addr_len)) {
            return false;
        }
    
        token += addr_len;
        token_len -= addr_len;
    
        if (*odcid_len < token_len) {
            return false;
        }
    
        memcpy(odcid, token, token_len);
        *odcid_len = token_len;
    
        return true;
    }
    
    static struct conn_io* create_conn(uint8_t* odcid, size_t odcid_len) {
        struct conn_io* conn_io = malloc(sizeof(*conn_io));
        if (conn_io == NULL) {
            fprintf(stderr, "failed to allocate connection IO\n");
            return NULL;
        }
    
        HCRYPTPROV p;
        ULONG     i;
    
        if (CryptAcquireContext(&p, NULL, NULL, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT) == FALSE) {
            perror("RandBtyes(): CryptAcquireContext failed.");
            return NULL;
        }
    
        if (CryptGenRandom(p, LOCAL_CONN_ID_LEN, (BYTE*)conn_io->cid) == FALSE) {
            perror("RandBytes(): CryptGenRandom failed.");
            return NULL;
    
        }
    
        quiche_conn* conn = quiche_accept(conn_io->cid, LOCAL_CONN_ID_LEN,
            odcid, odcid_len, config);
        if (conn == NULL) {
            fprintf(stderr, "failed to create connection\n");
            return NULL;
        }
    
        conn_io->sock = conns->sock;
        conn_io->conn = conn;
    
        ev_init(&conn_io->timer, timeout_cb);
        conn_io->timer.data = conn_io;
    
        HASH_ADD(hh, conns->h, cid, LOCAL_CONN_ID_LEN, conn_io);
    
        fprintf(stderr, "new connection\n");
    
        return conn_io;
    }
    
    static void recv_cb(EV_P_ ev_io* w, int revents) {
        struct conn_io* tmp, * conn_io = NULL;
    
        static uint8_t buf[65535];
        static uint8_t out[MAX_DATAGRAM_SIZE];
    
        while (1) {
            struct sockaddr_storage peer_addr;
            socklen_t peer_addr_len = sizeof(peer_addr);
            memset(&peer_addr, 0, peer_addr_len);
    
            ssize_t read = recvfrom(conns->sock, buf, sizeof(buf), 0,
                (struct sockaddr*) & peer_addr,
                &peer_addr_len);
    
            if (read < 0) {
                if ((errno == EWOULDBLOCK) || (errno == EAGAIN)) {
                    fprintf(stderr, "recv would block\n");
                    break;
                }
    
                perror("failed to read");
                return;
            }
    
            uint8_t type;
            uint32_t version;
    
            uint8_t scid[QUICHE_MAX_CONN_ID_LEN];
            size_t scid_len = sizeof(scid);
    
            uint8_t dcid[QUICHE_MAX_CONN_ID_LEN];
            size_t dcid_len = sizeof(dcid);
    
            uint8_t odcid[QUICHE_MAX_CONN_ID_LEN];
            size_t odcid_len = sizeof(odcid);
    
            uint8_t token[MAX_TOKEN_LEN];
            size_t token_len = sizeof(token);
    
            int rc = quiche_header_info(buf, read, LOCAL_CONN_ID_LEN, &version,
                &type, scid, &scid_len, dcid, &dcid_len,
                token, &token_len);
            if (rc < 0) {
                fprintf(stderr, "failed to parse header: %d\n", rc);
                continue;
            }
    
            HASH_FIND(hh, conns->h, dcid, dcid_len, conn_io);
    
            if (conn_io == NULL) {
                if (!quiche_version_is_supported(version)) {
                    fprintf(stderr, "version negotiation\n");
    
                    ssize_t written = quiche_negotiate_version(scid, scid_len,
                        dcid, dcid_len,
                        out, sizeof(out));
    
                    if (written < 0) {
                        fprintf(stderr, "failed to create vneg packet: %zd\n",
                            written);
                        continue;
                    }
    
                    ssize_t sent = sendto(conns->sock, out, written, 0,
                        (struct sockaddr*) & peer_addr,
                        peer_addr_len);
                    if (sent != written) {
                        perror("failed to send");
                        continue;
                    }
    
                    fprintf(stderr, "sent %zd bytes\n", sent);
                    continue;
                }
    
                if (token_len == 0) {
                    fprintf(stderr, "stateless retry\n");
    
                    mint_token(dcid, dcid_len, &peer_addr, peer_addr_len,
                        token, &token_len);
    
                    ssize_t written = quiche_retry(scid, scid_len,
                        dcid, dcid_len,
                        dcid, dcid_len,
                        token, token_len,
                        out, sizeof(out));
    
                    if (written < 0) {
                        fprintf(stderr, "failed to create retry packet: %zd\n",
                            written);
                        continue;
                    }
    
                    ssize_t sent = sendto(conns->sock, out, written, 0,
                        (struct sockaddr*) & peer_addr,
                        peer_addr_len);
                    if (sent != written) {
                        perror("failed to send");
                        continue;
                    }
    
                    fprintf(stderr, "sent %zd bytes\n", sent);
                    continue;
                }
    
    
                if (!validate_token(token, token_len, &peer_addr, peer_addr_len,
                    odcid, &odcid_len)) {
                    fprintf(stderr, "invalid address validation token\n");
                    continue;
                }
    
                conn_io = create_conn(odcid, odcid_len);
                if (conn_io == NULL) {
                    continue;
                }
    
                memcpy(&conn_io->peer_addr, &peer_addr, peer_addr_len);
                conn_io->peer_addr_len = peer_addr_len;
            }
    
            ssize_t done = quiche_conn_recv(conn_io->conn, buf, read);
    
            if (done < 0) {
                fprintf(stderr, "failed to process packet: %zd\n", done);
                continue;
            }
    
            fprintf(stderr, "recv %zd bytes\n", done);
    
            if (quiche_conn_is_established(conn_io->conn)) {
                uint64_t s = 0;
    
                quiche_stream_iter* readable = quiche_conn_readable(conn_io->conn);
    
                while (quiche_stream_iter_next(readable, &s)) {
                    fprintf(stderr, "stream %" PRIu64 " is readable\n", s);
    
                    bool fin = false;
                    ssize_t recv_len = quiche_conn_stream_recv(conn_io->conn, s,
                        buf, sizeof(buf),
                        &fin);
                    if (recv_len < 0) {
                        break;
                    }
    
                    if (fin) {
                        static const char* resp = "byez\n";
                        quiche_conn_stream_send(conn_io->conn, s, (uint8_t*)resp,
                            5, true);
                    }
                }
    
                quiche_stream_iter_free(readable);
            }
        }
    
        HASH_ITER(hh, conns->h, conn_io, tmp) {
            flush_egress(loop, conn_io);
    
            if (quiche_conn_is_closed(conn_io->conn)) {
                quiche_stats stats;
    
                quiche_conn_stats(conn_io->conn, &stats);
                fprintf(stderr, "connection closed, recv=%zu sent=%zu lost=%zu rtt=%" PRIu64 "ns cwnd=%zu\n",
                    stats.recv, stats.sent, stats.lost, stats.rtt, stats.cwnd);
    
                HASH_DELETE(hh, conns->h, conn_io);
    
                ev_timer_stop(loop, &conn_io->timer);
                quiche_conn_free(conn_io->conn);
                free(conn_io);
            }
        }
    }
    
    static void timeout_cb(EV_P_ ev_timer* w, int revents) {
        struct conn_io* conn_io = w->data;
        quiche_conn_on_timeout(conn_io->conn);
    
        fprintf(stderr, "timeout\n");
    
        flush_egress(loop, conn_io);
    
        if (quiche_conn_is_closed(conn_io->conn)) {
            quiche_stats stats;
    
            quiche_conn_stats(conn_io->conn, &stats);
            fprintf(stderr, "connection closed, recv=%zu sent=%zu lost=%zu rtt=%" PRIu64 "ns cwnd=%zu\n",
                stats.recv, stats.sent, stats.lost, stats.rtt, stats.cwnd);
    
            HASH_DELETE(hh, conns->h, conn_io);
    
            ev_timer_stop(loop, &conn_io->timer);
            quiche_conn_free(conn_io->conn);
            free(conn_io);
    
            return;
        }
    }
    
    int main(int argc, char* argv[]) {
        const char* host = argv[1];
        const char* port = argv[2];
    
        const struct addrinfo hints = {
            .ai_family = PF_UNSPEC,
            .ai_socktype = SOCK_DGRAM,
            .ai_protocol = IPPROTO_UDP
        };
    
        quiche_enable_debug_logging(debug_log, NULL);
    
        struct addrinfo* local;
        int iResult;
        WSADATA wsaData;
        WORD wVersionRequested;
        wVersionRequested = MAKEWORD(2, 2);
        iResult = WSAStartup(wVersionRequested, &wsaData);
        if (getaddrinfo("localhost", "5555", &hints, &local) != 0) {
            perror("failed to resolve host");
            return -1;
        }
    
        int sock = socket(local->ai_family, SOCK_DGRAM, 0);
        if (sock < 0) {
            perror("failed to create socket");
            return -1;
        }
    
        u_long nonblocking_enabled = TRUE;
        if (ioctlsocket(sock, FIONBIO, &nonblocking_enabled) != 0) {
            perror("failed to make socket non-blocking");
            return -1;
        }
    
        if (bind(sock, local->ai_addr, local->ai_addrlen) < 0) {
            perror("failed to connect socket");
            return -1;
        }
    
        config = quiche_config_new(QUICHE_PROTOCOL_VERSION);
        if (config == NULL) {
            fprintf(stderr, "failed to create config\n");
            return -1;
        }
        
        quiche_config_load_cert_chain_from_pem_file(config, "./cert.crt");
        quiche_config_load_priv_key_from_pem_file(config, "./cert.key");
    
        quiche_config_set_application_protos(config,
            (uint8_t*)"\x05hq-27\x05hq-25\x05hq-24\x05hq-23\x08http/0.9", 21);
    
        quiche_config_set_max_idle_timeout(config, 5000);
        quiche_config_set_max_packet_size(config, MAX_DATAGRAM_SIZE);
        quiche_config_set_initial_max_data(config, 10000000);
        quiche_config_set_initial_max_stream_data_bidi_local(config, 1000000);
        quiche_config_set_initial_max_stream_data_bidi_remote(config, 1000000);
        quiche_config_set_initial_max_streams_bidi(config, 100);
        quiche_config_set_cc_algorithm(config, QUICHE_CC_RENO);
    
        struct connections c;
        int fd = _open_osfhandle(sock, 0);
        c.sock = sock;
        c.h = NULL;
    
        conns = &c;
    
        ev_io watcher;
    
        struct ev_loop* loop = ev_default_loop(0);
        
        ev_io_init(&watcher, recv_cb, fd, EV_READ);
        ev_io_start(loop, &watcher);
        watcher.data = &c;
    
        ev_loop(loop, 0);
    
        freeaddrinfo(local);
    
        quiche_config_free(config);
    
        return 0;
    }`

 **client.c**
  `    
    #define WIN32_LEAN_AND_MEAN
    #include <Windows.h>
    #include <WinSock2.h>
    #include <WS2tcpip.h> /* socklen_t */
    /* Need to link with Ws2_32.lib */
    #pragma comment(lib, "ws2_32.lib")
    #pragma comment(lib, "quiche.lib")
    
    
    #include <io.h>
    #include <stdlib.h>
    #include <stdio.h>
    #include <stdint.h>
    #include <string.h>
    #include <errno.h>
    #include <stdint.h>
    #include <stdbool.h>
    #include <fcntl.h>
    #include<corecrt_io.h>
    #include <inttypes.h>
    #include<wincrypt.h>
    #include<quiche.h>
    
    
    
    #include"uthash.h"
    
    
     /* Libev. */
    #include "libev.h"
    
    
    #define LOCAL_CONN_ID_LEN 16
    
    #define MAX_DATAGRAM_SIZE 1350
    
    struct conn_io {
        ev_timer timer;
    
        int sock;
    
        quiche_conn* conn;
    };
    
    static void debug_log(const char* line, void* argp) {
        fprintf(stderr, "%s\n", line);
    }
    
    static void flush_egress(struct ev_loop* loop, struct conn_io* conn_io) {
        static uint8_t out[MAX_DATAGRAM_SIZE];
    
        while (1) {
            ssize_t written = quiche_conn_send(conn_io->conn, out, sizeof(out));
    
            if (written == QUICHE_ERR_DONE) {
                fprintf(stderr, "done writing\n");
                break;
            }
    
            if (written < 0) {
                fprintf(stderr, "failed to create packet: %zd\n", written);
                return;
            }
    
            ssize_t sent = send(conn_io->sock,(const char *) out, written, 0);
            if (sent != written) {
                perror("failed to send");
                return;
            }
    
            fprintf(stderr, "sent %zd bytes\n", sent);
        }
    
        double t = quiche_conn_timeout_as_nanos(conn_io->conn) / 1e9f;
        conn_io->timer.repeat = t;
        ev_timer_again(loop, &conn_io->timer);
    }
    
    static void recv_cb(EV_P_ ev_io* w, int revents) {
        static bool req_sent = false;
    
        struct conn_io* tmp =(conn_io*) w->data;
    
        static uint8_t buf[65535];
    
        while (1) {
            ssize_t read = recv(tmp->sock,(char *) buf, sizeof(buf), 0);
            fprintf(stderr, "recv =%s\n",buf);
    
            if (read < 0) {
                if ((errno == EWOULDBLOCK) || (errno == EAGAIN)) {
                    fprintf(stderr, "recv would block\n");
                    break;
                }
    
                perror("failed to read");
                return;
            }
    
            ssize_t done = quiche_conn_recv(tmp->conn, buf, read);
    
            if (done < 0) {
              fprintf(stderr, "failed to process packet\n");
                continue;
            }
    
            fprintf(stderr, "recv %zd bytes\n", done);
        }
    
        fprintf(stderr, "done reading\n");
    
        if (quiche_conn_is_closed(tmp->conn)) {
            fprintf(stderr, "connection closed\n");
    
            ev_break(EV_A_ EVBREAK_ONE);
            return;
        }
    
        if (quiche_conn_is_established(tmp->conn) && !req_sent) {
            const uint8_t* app_proto;
            size_t app_proto_len;
    
            quiche_conn_application_proto(tmp->conn, &app_proto, &app_proto_len);
    
            fprintf(stderr, "connection established: %.*s\n",
                (int)app_proto_len, app_proto);
    
            const static uint8_t r[] = "GET /index.html\r\n";
            if (quiche_conn_stream_send(tmp->conn, 4, r, sizeof(r), true) < 0) {
                fprintf(stderr, "failed to send HTTP request\n");
                return;
            }
    
            fprintf(stderr, "sent HTTP request\n");
    
            req_sent = true;
        }
    
        if (quiche_conn_is_established(tmp->conn)) {
            uint64_t s = 0;
    
            quiche_stream_iter* readable = quiche_conn_readable(tmp->conn);
    
            while (quiche_stream_iter_next(readable, &s)) {
                fprintf(stderr, "stream %" PRIu64 " is readable\n", s);
    
                bool fin = false;
                ssize_t recv_len = quiche_conn_stream_recv(tmp->conn, s,
                    buf, sizeof(buf),
                    &fin);
                if (recv_len < 0) {
                    break;
                }
    
                printf("%.*s", (int)recv_len, buf);
    
                if (fin) {
                    if (quiche_conn_close(tmp->conn, true, 0, NULL, 0) < 0) {
                        fprintf(stderr, "failed to close connection\n");
                    }
                }
            }
    
            quiche_stream_iter_free(readable);
        }
    
        flush_egress(loop, tmp);
    }
    
    static void timeout_cb(EV_P_ ev_timer* w, int revents) {
        struct conn_io* tmp = (conn_io*)w->data;
        quiche_conn_on_timeout(tmp->conn);
    
        fprintf(stderr, "timeout\n");
    
        flush_egress(loop, tmp);
    
        if (quiche_conn_is_closed(tmp->conn)) {
            quiche_stats stats;
    
            quiche_conn_stats(tmp->conn, &stats);
    
            fprintf(stderr, "connection closed, recv=%zu sent=%zu lost=%zu rtt=%" PRIu64 "ns\n",
                stats.recv, stats.sent, stats.lost, stats.rtt);
    
            ev_break(EV_A_ EVBREAK_ONE);
            return;
        }
    }
    
    int main(int argc, char* argv[]) {
        const char* host = argv[1];
        const char* port = argv[2];
    
        const struct addrinfo hints = {
            .ai_family = PF_UNSPEC,
            .ai_socktype = SOCK_DGRAM,
            .ai_protocol = IPPROTO_UDP
        };
    
        quiche_enable_debug_logging(debug_log, NULL);
    
        struct addrinfo* peer;
        int iResult;
        WSADATA wsaData;
        WORD wVersionRequested;
        wVersionRequested = MAKEWORD(2, 2);
        iResult = WSAStartup(wVersionRequested, &wsaData);
        if (getaddrinfo("localhost", "5555", &hints, &peer) != 0) {
            perror("failed to resolve host");
            return -1;
        }
    
        int sock = socket(peer->ai_family, SOCK_DGRAM, 0);
        if (sock < 0) {
            perror("failed to create socket");
            return -1;
        }
    
        u_long nonblocking_enabled = TRUE;
        if (ioctlsocket(sock, FIONBIO, &nonblocking_enabled) != 0) {
            perror("failed to make socket non-blocking");
            return -1;
        }
    
        if (connect(sock, peer->ai_addr, peer->ai_addrlen) < 0) {
            perror("failed to connect socket");
            return -1;
        }
    
        quiche_config* config = quiche_config_new(0xbabababa);
        if (config == NULL) {
            fprintf(stderr, "failed to create config\n");
            return -1;
        }
    
        quiche_config_set_application_protos(config,
            (uint8_t*)"\x05hq-27\x05hq-25\x05hq-24\x05hq-23\x08http/0.9", 15);
    
        quiche_config_set_max_idle_timeout(config, 5000);
        quiche_config_set_max_packet_size(config, MAX_DATAGRAM_SIZE);
        quiche_config_set_initial_max_data(config, 10000000);
        quiche_config_set_initial_max_stream_data_bidi_local(config, 1000000);
        quiche_config_set_initial_max_stream_data_uni(config, 1000000);
        quiche_config_set_initial_max_streams_bidi(config, 100);
        quiche_config_set_initial_max_streams_uni(config, 100);
        quiche_config_set_disable_active_migration(config, true);
    
        if (getenv("SSLKEYLOGFILE")) {
            quiche_config_log_keys(config);
        }
    
        uint8_t scid[LOCAL_CONN_ID_LEN];
        HCRYPTPROV p;
        ULONG     i;
    
        if (CryptAcquireContext(&p, NULL, NULL, PROV_RSA_FULL, CRYPT_VERIFYCONTEXT) == FALSE) {
            perror("RandBtyes(): CryptAcquireContext failed.");
            return -1;
        }
    
        if (CryptGenRandom(p, sizeof(scid), (BYTE*)scid) == FALSE) {
            perror("RandBytes(): CryptGenRandom failed.");
    
        }
    
    
        quiche_conn* conn = quiche_connect(host, (const uint8_t*)scid,
            sizeof(scid), config);
        if (conn == NULL) {
            fprintf(stderr, "failed to create connection\n");
            return -1;
        }
    
        struct conn_io* tmp =(conn_io*) malloc(sizeof(*tmp));
        if (tmp == NULL) {
            fprintf(stderr, "failed to allocate connection IO\n");
            return -1;
        }
        int fd = _open_osfhandle(sock, 0);
        tmp->sock = sock;
        tmp->conn = conn;
    
        ev_io watcher;
    
        struct ev_loop* loop = ev_default_loop(0);
       
        ev_io_init(&watcher, recv_cb, fd, EV_READ);
        ev_io_start(loop, &watcher);
        watcher.data = tmp;
    
        ev_init(&tmp->timer, timeout_cb);
        tmp->timer.data = tmp;
    
        flush_egress(loop, tmp);
    
        ev_loop(loop, 0);
    
        freeaddrinfo(peer);
    
        quiche_conn_free(conn);
    
        quiche_config_free(config);
    
        return 0;
    }`
The mentioned errors ( "failed to process packet" and "failed to read: No error" in client.c) are the conclusions of above codes.

**Comment by LPardue** [comment]
These message are benign.

Do you client and server fail to connect and exchange an HTTP request/response?

**Comment by foroughmajidi** [comment]
Yes, when I run client and server the recv ( recv(tmp->sock,(char *) buf, sizeof(buf), 0) function 
in my project (client and server) returns -1 and the server creates new connection but it returns (-1=failed to read) . This process repeats but doesn't lead to right result.

I don't know how to solve it and what items do I need to check.

 Client.c and server.c  are in example directory  but I made some changes for windows.
host ="localhost" and port="5555"

**Comment by LPardue** [comment]
If recv() is failing, you should start with investigating that. That doesn't belong to the quiche API so there's not much we can help you with.

**Comment by foroughmajidi** [comment]
At first quiche_conn_recv() function returns -1(failed to process packet) after that recv() function returns -1 (failed to read) and the error of recv() is 10035: WSAEWOULDBLOCK.
My question is : why  does quiche_conn_recv() returns -1?
Thanks.

**Comment by foroughmajidi** [comment]
I bring an example to make my mean clear:
At first client sent 1200 bytes and server received them.
Then server sent 51 bytes and client received ,
 At this time  in client.c, quiche_conn_recv() function returns -1 (failed to process packet), so it leads that recv() function return -1.

**Comment by junhochoi** [comment]
> then recv() function returns (-1=failed to read).
> the error of recv() is 10035: WSAEWOULDBLOCK.

https://stackoverflow.com/questions/14546362/how-to-resolve-wsaewouldblock-error

WSAEWOULDBLOCK should be considered as same as Unix's EWOULDBLOCK.
So you can add the condition when recv() returns < 0 : (-1 = SOCKET_ERROR)

        ssize_t read = recv(tmp->sock,(char *) buf, sizeof(buf), 0);
        ....

        if (read < 0) {
            if ((errno == EWOULDBLOCK) || (errno == EAGAIN) || (WSAGetLastError() == WSAEWOULDBLOCK) {
                fprintf(stderr, "recv would block\n");
                break;
            }

I don't have a windows dev machine so can't check on my end.

**Comment by foroughmajidi** [comment]
Thanks for your answer when I did it ,quiche_conn_recv() function returned -1  twice  and I got repeatedly "recv would block".
Do you have any other suggestion to solve the problem?

**Comment by junhochoi** [comment]
@foroughmajidi thanks and good to see your windows app is working!
