### ISSUE TITLE
BoringSSL faliure when building with Clang

### ISSUE THREAD

**Issue by lazerl0rd** [cloudflare/quiche#481]
The bug was fixed upstream as of https://github.com/google/boringssl/commit/577eadc424359fc316ce7d099f9962dddb544e71. Please checkout https://github.com/google/boringssl/commit/577eadc424359fc316ce7d099f9962dddb544e71 or pick the commit.

**Comment by janev94** [comment]
Which Clang? on what OS? With which boring-ssl revision? I have compiled the current master without issues using FreeBSD clang version 8.0.0 (tags/RELEASE_800/final 356365) (based on LLVM 8.0.0).

**Comment by lazerl0rd** [comment]
@janev94 I have tested Clang 10 and Clang 11 (mainline) (Clang 8 is quite old, BTW) on Linux 5.6.

The build fails anywhere between https://github.com/google/boringssl/commit/1e859054c31ec7b974e998373e85fadea56d93ad and https://github.com/google/boringssl/commit/577eadc424359fc316ce7d099f9962dddb544e71 - which is the upstream fix that I stated in the first message.

There doesn't seem to be any repercussions of the patch, as of https://boringssl-review.googlesource.com/c/boringssl/+/40471 and it's just a linting issue so there should be no harm in picking it.

**Comment by ghedo** [comment]
Thanks for reporting! I made https://github.com/cloudflare/quiche/pull/499 to update BoringSSL to the latest version, please check if it works for you.

**Comment by lazerl0rd** [comment]
Yupp, @ghedo that's all good.

**Comment by lazerl0rd** [comment]
I noticed this wasn't merged into master, so until then I'll leave this open.
