### ISSUE TITLE
Regarding behaviour of "quiche_conn_stream_recv" C API

### ISSUE THREAD

**Issue by piano-man** [cloudflare/quiche#495]
I'm having a little trouble understanding the behaviour of the "quiche_conn_stream_recv" API.

Suppose I'm sending the data "TestStream" over Stream 0 from my client.
Now, I put "Test" in one stream frame with {stream offset: 0, fin bit: false} and "Stream" in another stream frame with {stream offset: 4, fin bit: true}.

I now send these frames in two different Protected Packets(lets call them packet 0 and packet 1).
If I send packet 0 followed by packet 1, "quiche_conn_stream_recv" first returns 4 and then returns 6, whereas if I send packet 1 followed by packet 0, "quiche_conn_stream_recv" processes both the packets and returns 10.

What's more surprising is that if I'm sending multiple packets, lets say packet 0(starting packet for the stream), packet 1, and packet 2 with packet 2 having the finbit set to true. If I send packet 2, followed by packet 1 and then packet 0, "quiche_conn_stream_recv" will return the collective length of the stream data but if I change the order to packet 2 -> packet 0 -> packet 1, "quiche_conn_stream_recv" will return the length of packet 0 separately and that of packet 1 and packet 2 collectively. 

Is this supposed to happen ?

**Comment by LPardue** [comment]
What is the timing between calling send + flushing UDP, and reading UDP + quiche_conn_stream_recv?

quiche_conn_stream_recv will attempt to consume unread contiguous byte from the start of the stream. In your first case (0 then 1), calling quiche_conn_stream_recv after packet 0 has been processed but before packet 1 means that the first 4 bytes of the stream are available. In your second case (1 then 0), calling quiche_conn_stream_recv after packet 1 has been processed but before packet 0 means that there are no bytes available; calling quiche_conn_stream_recv after packet 1 is processed with then yield all 10 bytes.

**Comment by piano-man** [comment]
Oh, I see.
Thanks !
