### ISSUE TITLE
Echo Server Example

### ISSUE THREAD

**Issue by piano-man** [cloudflare/quiche#496]
Could an echo server example be added to the examples directory perhaps ?
Echo servers are usually a big help when trying to understand the data exchange and reassembly phase of the protocol.

Thanks :)

**Comment by LPardue** [comment]
It depends on what you want to echo. 

The simplest option here is to run the patched nginx as a reverse proxy in front of a web server that can echo HTTP requests. That is something which is deployable and doesn't need any effort on quiche itself.

I'd review a PR that adds a HTTP request echo capability to quiche-server. 

If you want to echo anything else, then you end up having to define how the echoing works and will probably mean defining a new application mapping and ALPN. That is a lot of additional effort to develop and maintain.

**Comment by piano-man** [comment]
I was thinking something basic that reassembles the stream level data that a client sends and just sends that back.(I guess this is essentially what would echo a HTTP request as well ?)

**Comment by LPardue** [comment]
It sounds basic but requires too much administrative overhead IMO.

**Comment by piano-man** [comment]
Ah, alright!
