### ISSUE TITLE
H3 config new()

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#501]
I'm curious, why is the following `new()` returning `Result<Config>`?

https://github.com/cloudflare/quiche/blob/85ca070f1a8b479463060cbb914f9b959fe270b1/src/h3/mod.rs#L394

IMO, it's simpler and easier to use if it returns `Config`.  Wondering what's the reason? Is there a plan to return some error in future?

**Comment by junhochoi** [comment]
My understanding is that this is to align with other Config API
https://github.com/cloudflare/quiche/blob/85ca070f1a8b479463060cbb914f9b959fe270b1/src/lib.rs#L434

But I think @LPardue can tell in more detail.

**Comment by LPardue** [comment]
The quiche API has a lot of functions that return a `Result`. Making this one method special case seems odd, and changing it now would impact all applications that use HTTP/3.

I recommend coding to the possibility of receiving an error for this in the future.

**Comment by keepsimple1** [comment]
Thanks for the responses. Understood changing it is difficult. Closing the issue now.
