### ISSUE TITLE
Support BBR congestion control

### ISSUE THREAD

**Issue by VMatrix1900** [cloudflare/quiche#514]
I use configurable congestion control to implement BBR congestion control. It is doable with some caveats.

1. Need an accurate pacing implementation. I tried to implement a pacing module on the C part using libev/libuv timer but the accuracy of the timer is not good enough. I also tried to use `set_socket_opt` to leverage kernel pacing but it can not support multiple pacing rates on same socket. I read your [blog](https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/). Is there any update on the pacing implementation?
2. I implemented the BBR congestion control by porting the BBR implementation in [lsquic](https://github.com/litespeedtech/lsquic) into the Rust part. However, their data structure is different from QUICHE's. It involves a lot of structs translation and duplicate. I notice that some parts of the BBR code such as delivery rate estimation(#375) and windowed min-max filter over (#398) is ported. Are you actively working on the BBR implementation?

**Comment by junhochoi** [comment]
@VMatrix1900 as mentioned [in our blog post](https://blog.cloudflare.com/cubic-and-hystart-support-in-quiche/) we plan to work on pacing/BBR. rate estimation and minmax filter is one of the requirements.

**Comment by VMatrix1900** [comment]
> @VMatrix1900 as mentioned [in our blog post](https://blog.cloudflare.com/cubic-and-hystart-support-in-quiche/) we plan to work on pacing/BBR. rate estimation and minmax filter are one of the requirements.

Any thoughts on the pacing module?

And the minmax filter is supposed to be used both for max bandwidth and min RTT. But current implementation can only works for min RTT. It should be changed into generic types for max bandwidth. I can create a pull request for that if you need.

**Comment by VMatrix1900** [comment]
I already port the BBR state machine using the old configurable congestion control API before #421. I can rebase it based on the vtable API for a start point to port BBR if such a pull request is welcomed.

**Comment by junhochoi** [comment]
@VMatrix1900 we are working on those new features (pacing, BBR, etc) but we don't have a date yet. External contribution is generally welcomed. Also,
- pacing: It will be implemented in quiche library but may depend on the OS support described in the [blog post](https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/).
- minmax: Current minmax filter (src/minmax.rs) supports min and max both. @lohith-bellad can clarify if needed.

**Comment by VMatrix1900** [comment]
> * pacing: It will be implemented in quiche library but may depend on the OS support described in the [blog post](https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/).
In my point of view, the QUICHE library only provides a QUIC state machine. The IO is done by other parts. The pacing is related to the I/O. The best QUICHE library can do is providing a pacing rate for an external pacing module to execute. 

> * minmax: Current minmax filter (src/minmax.rs) supports min and max both. @lohith-bellad can clarify if needed.
It is a data type issue. The current minmax filter using `Duration` as the value type so it can be used to track minimal RTT but not max bandwidth.

**Comment by lohith-bellad** [comment]
minmax filter implementation is more generic now.

**Comment by xanathar** [comment]
@VMatrix1900 is there a public branch where I can take a peek at your BBR implementation?

**Comment by ibis85** [comment]
I'd also be interested in any WIP BBR branch.

**Comment by rafibaum** [comment]
Hi, I was wondering if there's been any progress on this issue internally? I'm considering using QUICHE as part of a research project which requires using congestion control algorithms with pacing (BBR/Copa). If there isn't work progressing on this, I was planning on authoring potentially authoring a PR myself but I didn't want to reinvent the wheel.

**Comment by junhochoi** [comment]
Now we have bbr (v1) via #1180.
