### ISSUE TITLE
compile with target x86_64-apple-ios failed

### ISSUE THREAD

**Issue by ggjjlldd** [cloudflare/quiche#515]
i am use quiche guide to compile ios library but failed. error message is above:
[ 98%] Building CXX object tool/CMakeFiles/bssl.dir/tool.cc.o
[100%] Building CXX object tool/CMakeFiles/bssl.dir/transport_common.cc.o
[100%] Linking CXX executable bssl

--- stderr
ios arch=x86_64 add CMAKE_OSX_ARCHITECTURES=x86_64
ios arch=x86_64 add CMAKE_OSX_SYSROOT=iphonesimulator
/Users/aeris/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: **file: libcrypto.a(poly_rq_mul.S.o) has no symbols**
/Users/aeris/Downloads/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: **file: libcrypto.a(poly_rq_mul.S.o) has no symbols**
ld: warning: -headerpad_max_install_names is ignored when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES)
ld: in ../crypto/libcrypto.a(rdrand-x86_64.S.o), building for iOS Simulator, but linking in object file built for iOS, for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
what should I do?

**Comment by junhochoi** [comment]
What is your OS/Xcode version and how did you run the build?
We have CI build for iOS and it's based on Xcode 11.2 + MacOS 10.14.6 (https://docs.travis-ci.com/user/reference/osx/)

**Comment by ggjjlldd** [comment]
my xcode version is 10.1, my mac os is 10.14.2

**Comment by junhochoi** [comment]
Ok I can reproduce the same error on xcode 10.1 but may take some to understand what's the problem.
You can try xcode 11.2 it would be great.

**Comment by junhochoi** [comment]
Note that this is an error in BoringSSL build, not the quiche itself.

**Comment by junhochoi** [comment]
@ggjjlldd I have a fix #520 and it works on my xcode 10.1. Can you confirm on your side?

**Comment by ggjjlldd** [comment]
> @ggjjlldd I have a fix #520 and it works on my xcode 10.1. Can you confirm on your side?

@junhochoi thanks very much. I already pass compile.
