### ISSUE TITLE
Document how to build quiche-client and quiche-server

### ISSUE THREAD

**Issue by agrover** [cloudflare/quiche#522]
Looks like more than one person (I was one of them) had trouble with the steps to build these tools. (I saw examples/ and thought that might be it! What can I say I was in a hurry) It would be nice to have some text in the toplevel readme (or at least a link to elsewhere) that describes how to build them, and maybe some basic usage, if there are any things to be aware of.

**Comment by ghedo** [comment]
We have some instructions at https://github.com/cloudflare/quiche#command-line-apps though ideas on how to improve it are welcome.

**Comment by agrover** [comment]
Ok, guess I really should slow down. No immediate ideas for improvement, I'm just going to close this issue.
