### ISSUE TITLE
HTTP/3 Patch for Nginx 1.18.0 stable ?

### ISSUE THREAD

**Issue by centminmod** [cloudflare/quiche#528]
Curious if there's any plans to bump up or release a HTTP/3 patch for latest Nginx stable which moved from 1.16.1 to 1.18.0 http://nginx.org/en/download.html ?

**Comment by haohetao** [comment]
good idea

**Comment by Wsget** [comment]
And now 1.19.0.

**Comment by whalehub** [comment]
@Wsget Nginx 1.19.0 is the mainline version, but I'd also like to see support for it.

**Comment by RanadeepPolavarapu** [comment]
Thanks @ghedo. Your comment gave me confidence to test it out.

We tested the patch against *nginx* `1.19.2` version and it seemed to work. We released an [*edge* docker image](https://github.com/RanadeepPolavarapu/docker-nginx-http3) containing latest nginx with quiche (`ranadeeppolavarapu/nginx-http3:edge`). Please feel free to test and play around with it to your liking.

![image](https://user-images.githubusercontent.com/7084995/90455291-b9e10d80-e0c3-11ea-92b4-b84c40e34d0c.png)

**Comment by ghedo** [comment]
Looks like we can close this.

**Comment by marinelli** [comment]
The current patch file does not work anymore due to the removal of `post_accept_timeout` in the core, https://github.com/nginx/nginx/commit/2ec8fac2d6b8e5023c9894d10bc50d78e63f242c.

**Comment by marinelli** [comment]
A sketch for nginx >= 1.19.7 (that has not been released yet) is here [1] and the derived patch is contained here [2].

[1] https://github.com/marinelli/nginx/tree/quiche-nginx-1.19.7
[2] https://github.com/marinelli/quiche/tree/quiche-nginx-1.19.7

**Comment by ajs124** [comment]
1.19.7 is released now

**Comment by kn007** [comment]
compiled failed with 1.19.7

**Comment by lazerl0rd** [comment]
A preliminary patch is available in Zestginx but needs a follow-up as per the comment on line 364.

https://github.com/ZestProjects/zestginx/commit/977f2a9ec71053108aa4271f613c63704f00a3b5
