### ISSUE TITLE
could not find native static library 'crypto', perhaps an -L flag is missing?

### ISSUE THREAD

**Issue by gunroot** [cloudflare/quiche#539]
This error I'm receving when I tried to compile quiche tool given in the link https://github.com/cloudflare/quiche
The full error I'm getting is given below
Caused by:
  process didn't exit successfully: `rustc --crate-name quiche --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C debuginfo=2 --cfg 'feature="boringssl-vendored"' --cfg 'feature="default"' -C metadata=ec649e4481e8d95d --out-dir /root/quiche/target/debug/deps -C incremental=/root/quiche/target/debug/incremental -L dependency=/root/quiche/target/debug/deps --extern lazy_static=/root/quiche/target/debug/deps/liblazy_static-3e523cea53aa78b2.rlib --extern libc=/root/quiche/target/debug/deps/liblibc-3d02aff0893bcd1d.rlib --extern libm=/root/quiche/target/debug/deps/liblibm-770d78106c2380e5.rlib --extern log=/root/quiche/target/debug/deps/liblog-29d81ded01531039.rlib --extern ring=/root/quiche/target/debug/deps/libring-45d6332ced1f3119.rlib -L native=/root/quiche/deps/boringssl/build/crypto -L native=/root/quiche/deps/boringssl/build/ssl -l static=crypto -l static=ssl -L native=/root/quiche/target/debug/build/ring-cf06706f198ab4f5/out` (exit code: 1)

I used cargo to build, I don't why it fails to fetch borginssl in /deps folder. Can anyone help me to diagonize it?

**Comment by wangwanchao** [comment]
why did you closed this issue? Had you solved this problem?How to do it?
