### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by LuciferJun1227** [cloudflare/quiche#540]
./configure                                 \
       --prefix=$PWD                           \
       --build="quiche-$(git --git-dir=../quiche/.git rev-parse --short HEAD)" \
       --with-http_ssl_module                  \
       --with-http_v2_module                   \
       --with-http_v3_module                   \
       --with-openssl=../quiche/deps/boringssl \
       --with-quiche=../quiche \
       --with-zlib=../zlib-1.2.11 \
       --with-pcre=../pcre-8.43 

Error：
mkdir -p ../quiche/deps/boringssl/build ../quiche/deps/boringssl/.openssl/lib ../quiche/deps/boringssl/.openssl/include/openssl \
&& cd ../quiche/deps/boringssl/build \
&& cmake -DCMAKE_C_FLAGS="" -DCMAKE_CXX_FLAGS="" .. \
&& make VERBOSE=1 \
&& cd .. \
&& cp -r include/openssl/*.h .openssl/include/openssl \
&& cp build/ssl/libssl.a build/crypto/libcrypto.a .openssl/lib
/bin/sh:行2: cmake: 未找到命令
make[1]: *** [../quiche/deps/boringssl/.openssl/include/openssl/ssl.h] 错误 127
make[1]: 离开目录“/root/http3/nginx-1.16.1”
make: *** [build] 错误 2

**Comment by junhochoi** [comment]
> /bin/sh:行2: cmake: 未找到命令

I think you are missing one of the build dependency, `cmake`. Please install cmake before build.

**Comment by LuciferJun1227** [comment]
> > /bin/sh:行2: cmake: 未找到命令
> 
> I think you are missing one of the build dependency, `cmake`. Please install cmake before build.

**Comment by wangwanchao** [comment]
I have this same problem. The key resulting in this problem is there isnt boringssl under deps package. There is many problems in branch master. But you choose to ignore them.

**Comment by LPardue** [comment]
If you have the same problem, then you'll notice that the issue author found the source of their problem and closed the issue.

If you have a different problem, please open a new issue with information, which should include: the commit ID, you system details, the exact steps you followed including installation of all prerequisites, and so on.

**Comment by wangwanchao** [comment]
> If you have the same problem, then you'll notice that the issue author found the source of their problem and closed the issue.
> 
> If you have a different problem, please open a new issue with information, which should include: the commit ID, you system details, the exact steps you followed including installation of all prerequisites, and so on.

Sorry,so thank you for your reply.I just be very confused about that there is no any file in the boringssl.
