### ISSUE TITLE
Curl + Quiche not working 

### ISSUE THREAD

**Issue by gengjiawen** [cloudflare/quiche#543]
I am following https://developers.cloudflare.com/http3/intro/curl-brew.

Run `curl --http3 https://cloudflare-quic.com` will output like: 

```
dyld: lazy symbol binding failed: Symbol not found: _quiche_config_set_idle_timeout
  Referenced from: /usr/local/Cellar/curl/7.67.0/lib/libcurl.4.dylib
  Expected in: flat namespace

dyld: Symbol not found: _quiche_config_set_idle_timeout
  Referenced from: /usr/local/Cellar/curl/7.67.0/lib/libcurl.4.dylib
  Expected in: flat namespace

fish: 'curl --http3 https://api.gengji…' terminated by signal SIGABRT (Abort)
```

I am on macOS 10.15.4.

**Comment by junhochoi** [comment]
Can you try the following?

```brew install --HEAD -s https://raw.githubusercontent.com/cloudflare/homebrew-cloudflare/master/curl.rb```

**Comment by gengjiawen** [comment]
> Can you try the following?
> 
> ```
> brew install --HEAD -s https://raw.githubusercontent.com/cloudflare/homebrew-cloudflare/master/curl.rb
> ```

```console
curl: (7) quiche: recv() unexpectedly returned -1 (errno: 61, socket 5)
```

**Comment by gengjiawen** [comment]
Not sure why sometimes it failed. I opened a new terminal, it worked, thanks.

**Comment by evandrix** [comment]
@ https://developers.cloudflare.com/http3/intro/curl-brew
verify:
$ `curl --http3 https://cloudflare-quic.com`
$ `curl --http3 https://blog.cloudflare.com`

`brew pin curl` to make sure it doesn't get upgraded
