### ISSUE TITLE
qlog: client serializes transport parameters too soon

### ISSUE THREAD

**Issue by rmarx** [cloudflare/quiche#556]
Hey there @LPardue,

I got an error report from Song Zhu (not sure he's on github) via email that the quiche client seems to be setting its initial FC TPs to 0 in qlog (see attached file). 
[client_quiche_quiche_2_3_5.zip](https://github.com/cloudflare/quiche/files/4763900/client_quiche_quiche_2_3_5.zip)

Looking at the code, you do seem to pass it correctly to qlog.
https://github.com/cloudflare/quiche/blob/acaecb589579101a3bb2bdd5e4b0c851bca9176a/src/lib.rs#L4038-L4060

However, the default value is indeed 0 and IIUC, the actual value is set in the examples/, depending on the type of client that is used. So I assume you just pass the TPs to qlog too early before this update from the application-layer has been completed. 

That is, I do assume the non-zero value is actually in the TPs and that you don't just update the FC allowance using MAX_DATA (if that -is- the case, then there is another qlog bug, because I don't see that MAX_DATA frame being sent).

**Comment by ghedo** [comment]
It looks like we are logging the TPs at the start of the connection, fixed by https://github.com/cloudflare/quiche/pull/557.
