### ISSUE TITLE
Quiche drops the packet with OOB stream id instead of sending CONNECTION_CLOSE

### ISSUE THREAD

**Issue by goelvidhi** [cloudflare/quiche#565]
When we inject a MAX_STREAMS frame with a value greater than 2^60 . The QUIC library must close the connection immediately with a connection error STREAM_LIMIT_ERROR.

Example,
MAX_STREAMS_BIDI[id=1152921504606846977]

Similar test for injecting OOB STREAMS_BLOCKED has same result, i.e. the packet is dropped without connection close.

**Comment by LPardue** [comment]
https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-19.11-5 says

> Maximum Streams:  A count of the cumulative number of streams of the
      corresponding type that can be opened over the lifetime of the
      connection.  This value cannot exceed 2^60, as it is not possible
      to encode stream IDs larger than 2^62-1.  Receipt of a frame that
      permits opening of a stream larger than this limit MUST be treated
      as a FRAME_ENCODING_ERROR.

So I think this needs to be FRAME_ENCODING_ERROR, not STREAM_LIMIT_ERROR.

**Comment by goelvidhi** [comment]
The draft specifies both the error codes for this scenario

For example, below is from section 4.5
https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-4.5
> If a max_streams transport parameter or MAX_STREAMS frame is received
   with a value greater than 2^60, this would allow a maximum stream ID
   that cannot be expressed as a variable-length integer; see
   Section 16.  If either is received, the connection MUST be closed
   immediately with a connection error of type STREAM_LIMIT_ERROR

Either should be fine, I think.

**Comment by LPardue** [comment]
Good point, I tend to agree either seems fine. I opened an issue on the QUIC specs to suggest it clarifies the text on this matter but I don't think the outcome affects the quiche PR; I'd be happy with either.
