### ISSUE TITLE
Make new release compatible with curl 7.71.0

### ISSUE THREAD

**Issue by candrews** [cloudflare/quiche#575]
curl 7.71.0 has been released.

curl now uses quiche's new `quiche_conn_set_keylog_path` function. This function was added to quiche in https://github.com/cloudflare/quiche/commit/8f4eb8d623df4615929ce36549d9c0bb9b165f86 and its usage was added to curl in https://github.com/curl/curl/commit/52777754623628f91ee2316acee52e68831f3e02#diff-9f5f2ae632274e9410c9ab668632cc97

Can you please make a new release of quiche which is compatible with curl 7.71.0?

Thank you!

**Comment by ghedo** [comment]
Based on the previous releases, the next one will be done in 2-3 weeks. We can probably anticipate a bit, but there are some changes that we need to land first.

**Comment by ghedo** [comment]
I just created `v0.5.0` https://github.com/cloudflare/quiche/releases/tag/0.5.0
