### ISSUE TITLE
quiche ffi for java

### ISSUE THREAD

**Issue by artemMartynenko** [cloudflare/quiche#578]
Hello!
My interest is to use a quiche library for QUIC implementation in Java. From your documentation, I got that ffi interface for C/C++ is already done. To be honest I`m no very familiar with Rust. So my question is, what is the better way to get rust ffi for Java and make appropriate mapping between Java classes and Rust structures used in quiche for API calls like Config, Connection etc.
Thank you for your time.

**Comment by ghedo** [comment]
You should be able to use the C API in Java by wrapping it with JNI I think, though I haven't tried myself as I don't really use Java.

**Comment by artemMartynenko** [comment]
Ok, thank you! 
I have one more question. I recognized that in C API you have typedefs structures for Connection and Config, but their definitions are empty. But in C client/server examples you use those structures with fields defined in the same structures in Rust. How does it work?

**Comment by ghedo** [comment]
Sorry for the delay. Those are forward declarations of types. C allows you to declare a type without actually defining it. In our case we only expose these types as opaque pointers via the C API, so we don't need to define them (or their size) anywhere. It's somewhat similar to typedeffing something to `void`.
