### ISSUE TITLE
[Question] Cloudflare's future plans for the Nginx patch

### ISSUE THREAD

**Issue by whalehub** [cloudflare/quiche#580]
The Nginx team recently announced a technology preview for QUIC+HTTP/3 support on their blog: https://www.nginx.com/blog/introducing-technology-preview-nginx-support-for-quic-http-3/

In light of this news and the recent announcement of a Working Group Last Call for QUIC+HTTP/3 by the IETF, I'm wondering what the future plans for the Nginx patch variant of Quiche are.

Will development on the Nginx patch be suspended once official support for QUIC+HTTP/3 lands in the next stable version of Nginx or are there plans to continue developing it as an alternative to the soon-to-be-built-in implementation?

**Comment by ghedo** [comment]
Hello,

We are not going to switch to the QUIC support from upstream NGINX on our infrastructure, and development of quiche will continue independently of that. As for the patch to integrate quiche into NGINX, we will continue to maintain it for as long as it is useful, and for as long as we continue to use NGINX, though we will need to figure out how to make it co-exist with the upstream code when the time comes.
