### ISSUE TITLE
STOP_SENDING frame

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#585]
Currently quiche seems not really processing STOP_SENDING frame [except the error case](https://github.com/cloudflare/quiche/blob/c25a59543b2778afe70a467b22b34b10a0d60021/src/lib.rs#L3387-L3394
).   Is there existing or planned work to bubble up this as a H3 event or something like that? I might missed that.

One use case is to let server stop streaming data earlier based on a client request (i.e. STOP_SENDING).

**Comment by LPardue** [comment]
This is still a TODO item but implementing it is low on the priority list at the moment.
