### ISSUE TITLE
How to add soname into libquiche.so

### ISSUE THREAD

**Issue by coolcih** [cloudflare/quiche#598]
Hello,
     I am new for RUST and quic. Hope it is a proper way to raise the question I met. I managed to compile the quiche on Android platform. For static build(libquiche.a), my app can use quic protocol perfectly through quiche. Now I am working on a dynamic lib(libquiche.so) version.  I notice the libquiche.so compile out with below commands line lack "soname" filed.

cargo ndk --target aarch64-linux-android --android-platform 21 -- build

$readelf -a target/aarch64-linux-android/debug/libquiche.so |grep soname
## Output nothing, libquiche.so didn't contain "soname" field.

The "soname" field can be set by "Wl,soname libquiche.so". My question is how to set this "Wl,soname libquiche.so" compile option into the RUST cross compile system?

**Comment by VMatrix1900** [comment]
I am also working on Quiche on Android. Can you share some details on how you use Quiche in your Android app?

**Comment by junhochoi** [comment]
@coolcih is this work for you? https://github.com/rust-lang/rust/issues/43190
or you can patch to add soname later: https://stackoverflow.com/questions/45392319/set-soname-after-linkage

**Comment by coolcih** [comment]
@junhochoi , thanks for the info! You are the best. It works after I add below line in src/build.rs - main function:
println!("cargo:rustc-cdylib-link-arg=-Wl,-soname,libquiche.so");

I suggest add similar line in official release. From what I met, if without soname in the so lib, android build system will hardcode the native dir path into the bin file which use the libquiche.so. For example:
1. Built libquiche.so for Android.
2. Use  libquiche.so as a prebuilt lib i.e. write a prebuilt Android.mk or Android.bp.
3. In app, let's say "myapp",  in myapp's android.mk reference "libquiche" as a shared libaray.
4. After compile myapp, readelf myapp, below result show:

$readelf -a myapp|grep NEEDED
shared lib: [out/target/product/delta/obj/SHARED_LIBRARIES/libquiche_intermediates/libquiche.so]

You can see a native build path hardcode into the myapp bin file. This can't work on Android device.
After I set "cargo:rustc-cdylib-link-arg=-Wl,-soname,libquiche.so", readelf output as below:

$readelf -a myapp|grep NEEDED
shared lib: [libquiche.so]

In this way myapp can find libquiche.so during runtime base on the android system configuration.

**Comment by coolcih** [comment]
@VMatrix1900 , it is not a proper thread to share for what I did. Briefly:
1. Built libquiche.so for Android base on official readme https://github.com/cloudflare/quiche
2. Use libquiche.so as a prebuilt lib i.e. write a prebuilt Android.mk or Android.bp.
3. In you app, use the api provided in quiche.h, you may need study the example in the source codes first. I tried the example in "tool/apps" on Android device, it works. This is a good beginning from studying the examples.

**Comment by VMatrix1900** [comment]
> In you app, use the api provided in quiche.h, you may need study the example in the source codes first. I tried the example in "tool/apps" on Android device, it works. This is a good beginning from studying the examples.

The app is written in Java and call API in quiche.h through JNI or just cross-compile example in "tool/apps"?

**Comment by junhochoi** [comment]
@coolcih I opened PR #599. PTAL

**Comment by coolcih** [comment]
@VMatrix1900 Our apps is a deamon for now which write with C.

**Comment by VMatrix1900** [comment]
> @VMatrix1900 Our apps is a deamon for now which write with C. 

Got it. Thanks a lot for sharing.

**Comment by ghedo** [comment]
Closing this, but leaving #165 open as they are about the same thing.
