### ISSUE TITLE
udp recv-q accumulate when udp send systemcall return `EAGAIN`

### ISSUE THREAD

**Issue by chenyuezhou** [cloudflare/quiche#604]
hello,

there is a problem when i do benchmark test with quiche patched nginx. 

my nginx conf.

```
http {
    server {
        listen 9443 quic reuseport;

        ssl_certificate      cert.crt;
        ssl_certificate_key  cert.key;

        ssl_protocols TLSv1.3;

        proxy_request_buffering off;

        add_header alt-svc 'h3-29=":9443"; ma=86400';

        ....

        proxy_pass 127.0.0.1:9999;
    }
}
```

before benchmark test.

![start_udp_status](https://user-images.githubusercontent.com/45252179/88158343-80d98880-cc3e-11ea-88c5-50e1cf3bb834.png)

udp fd is 9, and the fd event data is as follow.

![start_fd](https://user-images.githubusercontent.com/45252179/88158446-a23a7480-cc3e-11ea-9d48-592658f449c9.png)

![start_fdinfo](https://user-images.githubusercontent.com/45252179/88158471-a9fa1900-cc3e-11ea-9ea9-f1577cc2e960.png)

do benchmark test.

`seq 1000 | parallel -j 250 'curl --http3 'https://domain' --resolve domain:9443:ip -o /dev/null 2>1'`

a few moments later.

udp recv-q start accumulate, event i stop benchmark test, the recv-q will not decrease.

![end_udp_status](https://user-images.githubusercontent.com/45252179/88158914-31e02300-cc3f-11ea-8e56-3120f7238aab.png)

then i find udp event handler was changed.

![end_fdinfo](https://user-images.githubusercontent.com/45252179/88158992-4b816a80-cc3f-11ea-935a-ddf41b4fa512.png)

i use systemtap to find out what wrong with the code. 

then i lock in follow code.

https://github.com/cloudflare/quiche/blob/72cc60534fe1e2cb75e46c9138ee5cc185bdd4ea/extras/nginx/nginx-1.16.patch#L696

generally, `ngx_handle_write_event` will not change the fd event data. because `c->write->active == 0` and  `c->write->ready == 1`, but when we call `ngx_quic_send_udp_packet` (`ngx_quic_send_udp_packet`->`ngx_udp_unix_sendmsg_chain`->`ngx_sendmsg`), and it return `EAGAIN` c->write->ready will set to 0. then `ngx_handle_write_event` will change the fd event data to current connection, but current connection read handler is not `ngx_event_recvmsg` any more. so when read event come in, it will not call recvmsg to recv udp packet.

Is it so, or is it something I misunderstood?

**Comment by ghedo** [comment]
I'm not sure I understand what the problem you are describing is, do you have a suggestion on what needs to be fixed and how?

> but current connection read handler is not ngx_event_recvmsg any more. so when read event come in, it will not call recvmsg to recv udp packet

`ngx_event_recvmsg` is the handler for the listener connection. Each QUIC connection will have their own read connection handler (`ngx_quic_read_handler`), but the read handler on the listening connection shouldn't change, so if this happens then it's a bug I think.

Would you be able to figure out why/where this happens?

**Comment by ghedo** [comment]
In any case thanks for reporting the issue @chenyuezhou!

**Comment by chenyuezhou** [comment]
> I'm not sure I understand what the problem you are describing is, do you have a suggestion on what needs to be fixed and how?
> 
> > but current connection read handler is not ngx_event_recvmsg any more. so when read event come in, it will not call recvmsg to recv udp packet
> 
> `ngx_event_recvmsg` is the handler for the listener connection. Each QUIC connection will have their own read connection handler (`ngx_quic_read_handler`), but the read handler on the listening connection shouldn't change, so if this happens then it's a bug I think.
> 
> Would you be able to figure out why/where this happens?

thanks.

every time we call `ngx_quic_write_handler(current_connection->write)` function, we will send some thing or not to client, and then we will call `ngx_handle_write_event(current_connection->write, 0)`. 

![image](https://user-images.githubusercontent.com/45252179/88168267-c1d89980-cc4c-11ea-8afc-4407c8712d79.png)

`ngx_handle_write_event` will call `ngx_epoll_add_event` (when use epoll)  and set `current_connection->fd` event data to `current_connection` (but `current_connection->read` is  not `ngx_event_recvmsg`) , when `current_connection->write->ready == 0` and `current_connection->write->active == 0` 

becase of `sendmsg` systemcall return `EAGAIN` then `current_connection->write->ready` will be 0. (`current_connection->write->active` always be 0). 

`os/unix/ngx_udp_sendmsg_chain.c`

![image](https://user-images.githubusercontent.com/45252179/88168625-462b1c80-cc4d-11ea-9c99-968043ae44d5.png)

**Comment by ghedo** [comment]
Oh, I see what you mean now. I guess we should probably call `ngx_handle_write_event` and `ngx_handle_read_event` with the listening connection event handler instead. I'll look into preparing a patch to see if this fixes the problem for you.

**Comment by chenyuezhou** [comment]
> Oh, I see what you mean now. I guess we should probably call `ngx_handle_write_event` and `ngx_handle_read_event` with the listening connection event handler instead. I'll look into preparing a patch to see if this fixes the problem for you.

thanks.

**Comment by ghedo** [comment]
Hello, sorry for the delay. In the end I think we don't even need to call these "handle read" and "handle write" functions, so I just removed the calls in https://github.com/cloudflare/quiche/pull/642, would you be able to test if this fixes the problem for you please?

**Comment by chenyuezhou** [comment]
> Hello, sorry for the delay. In the end I think we don't even need to call these "handle read" and "handle write" functions, so I just removed the calls in #642, would you be able to test if this fixes the problem for you please?

Hello, sorry for the late reply. 

After applying your patch, the above problem no longer occurs.

**Comment by ghedo** [comment]
Great, thank you for reporting and testing the patch @chenyuezhou!
