### ISSUE TITLE
Issue install curl last version on Mac

### ISSUE THREAD

**Issue by ionutz89** [cloudflare/quiche#605]
I am trying to update curl to the latest version but I am getting this error:

> brew install --HEAD -s https://raw.githubusercontent.com/cloudflare/homebrew-cloudflare/master/curl.rb
> Warning: Calling Non-checksummed download of curl formula file from an arbitrary URL is deprecated! Use 'brew extract' or 'brew create' and 'brew tap-new' to create a formula file in a tap on GitHub instead.
> ######################################################################## 100.0%
> ==> Cloning https://github.com/curl/curl.git
> Updating /Users/ionut/Library/Caches/Homebrew/curl--git
> ==> Checking out branch master
> Already on 'master'
> Your branch is up to date with 'origin/master'.
> HEAD is now at 13030d0 CMake: fix test for warning suppressions
> ==> ./buildconf
> ==> git clone --recursive https://github.com/cloudflare/quiche
> Error: An exception occurred within a child process:
>   Errno::EEXIST: File exists @ dir_s_mkdir - quiche/deps/boringssl/build
> Please create pull requests instead of asking for help on Homebrew's GitHub,
> Discourse, Twitter or IRC.

Can someone help me with this error `Errno::EEXIST: File exists @ dir_s_mkdir - quiche/deps/boringssl/build`?

**Comment by ionutz89** [comment]
Deleted and reinstall the curl... now I am getting another issue:

```
❯ curl -V
curl 7.71.1 (x86_64-apple-darwin19.5.0) libcurl/7.71.1 SecureTransport zlib/1.2.11
Release-Date: 2020-07-01
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile libz NTLM NTLM_WB SSL UnixSockets
❯ curl-config --version
libcurl 7.71.1
❯ curl --http3 https://cloudflare-quic.com
curl: option --http3: the installed libcurl version doesn't support this
curl: try 'curl --help' or 'curl --manual' for more information
```

Is it anything else that I can do ?

**Comment by junhochoi** [comment]
I updated homebrew formula to match with current build process.
Can you try https://github.com/cloudflare/homebrew-cloudflare/pull/18 ?

**Comment by ionutz89** [comment]
```
❯ curl --http3 https://cloudflare-quic.com -I
HTTP/3 200
date: Fri, 24 Jul 2020 08:10:24 GMT
content-type: text/html
content-length: 106072
set-cookie: __cfduid=d8647a359d68a89c060bde4f373e18cc61595578224; expires=Sun, 23-Aug-20 08:10:24 GMT; path=/; domain=.cloudflare-quic.com; HttpOnly; SameSite=Lax; Secure
cf-request-id: 042178a64b0000188b7b1d9200000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
server: cloudflare
cf-ray: 5b7c2a1d4eb5188b-MAN
alt-svc: h3-27=":443"; ma=86400, h3-28=":443"; ma=86400, h3-29=":443"; ma=86400
```
It works with your help. Many thanks.
