### ISSUE TITLE
quiche should not close connection when Handshake packet is corrupted into an Initial

### ISSUE THREAD

**Issue by agrover** [cloudflare/quiche#614]
[quiche-neqo2.zip](https://github.com/cloudflare/quiche/files/5024526/quiche-neqo2.zip)

see server/log.txt line 16470. Quiche thinks it receives an initial packet, it's invalid, and the server sends ConnectionClose.

see output.txt line 17327. This was actually a sent as Handshake packet but then byte 0 was corrupted (see line 17339).

Instead of closing the connection, maybe drop such packets.

**Comment by ghedo** [comment]
Thanks for reporting @agrover! I was able to reproduce this in a test case, need to figure out why the error is returned instead of ignoring the packet.

**Comment by ghedo** [comment]
https://github.com/cloudflare/quiche/pull/615 should fix the problem.
