### ISSUE TITLE
stream_recv Read Exhaustion 

### ISSUE THREAD

**Issue by victorstewart** [cloudflare/quiche#618]
getting my bearings with QUIC and Quiche.

say a message gets broken up into 5 packets.

when you read on the ready stream with `stream_recv`, I assume it is not aware of how many packets need to be read to fully exhaust the message it's working on, so just like a regular TCP socket you have to keep reading on `stream_recv` in a loop until you've read all your bytes?

**Comment by LPardue** [comment]
Yes pretty much. Quiche handles all of the stream data reassembly from packets back into contiguous byte stream, this is done as you read data from a UDP socket and pass the QUIC packets into quiche. Streams become readable once data has arrived and remain so until it is read, see https://docs.quic.tech/quiche/struct.Connection.html#method.readable 

```
// Iterate over readable streams.
for stream_id in conn.readable() {
    // Stream is readable, read until there's no more data.
    while let Ok((read, fin)) = conn.stream_recv(stream_id, &mut buf) {
        println!("Got {} bytes on stream {}", read, stream_id);
    }
}
```

**Comment by victorstewart** [comment]
haha whoops sorry i missed the...

> "Stream is readable, read until there's no more data."

Is there a trivial way to handle the readiness yourself? Integrating quiche into an existing server library with it's own io_uring event loop.

**Comment by LPardue** [comment]
I'm not sure I follow your question. For reading, we only know if there's stream data once we consume a packet (conn.recv()) and run all the frame processing. Readiness to read from the UDP socket can be done by whatever means you like though.

**Comment by victorstewart** [comment]
oh okay I mistakenly thought from that snippet you included that there was some kind of blocking and polling going on behind the scenes in `conn.readable()`.

So after the connection has been established and the socket informs it has bytes to read, I call `quiche_conn_recv` instead of a regular `recv`, and that's how the bytes "get into quiche"?

And then after `quiche_conn_recv` i must also call `quiche_conn_stream_recv`?
