### ISSUE TITLE
building quiche for android was failed

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#620]
I want to build quiche for android but I get this error:
![Untitled](https://user-images.githubusercontent.com/51900859/90952440-db057d80-e478-11ea-975b-61fa2ddfc666.png)
Please tell me where is the problem.

**Comment by ghedo** [comment]
Haven't received a reply for a while, so closing. Feel free to re-open if you can provide more information.

**Comment by chiwangnvp** [comment]
Have you figure it out yet ? I got the same error here
