### ISSUE TITLE
vs TCP Performance Benchmarks

### ISSUE THREAD

**Issue by victorstewart** [cloudflare/quiche#621]
Have you all run any performance benchmarks in-house of your Quiche Quic implementation vs the TCP stack in a bleeding edge Linux kernel? 

I know this is heavily dependent on if you use `sendmmsg` vs `sendmsg` and whether you do UDP GSO, and that tweaking the maximum packet size and how many acks per received packets etc can push QUIC performance up to TCP performance today.

(some links and graphs below for anyone who has this same question and find him or herself here).

But I'm wondering, without doing these tricks, what is the baseline cpu cycle multiplier loss of Quiche vs TCP in the kernel? Is it still 2x ballpark as Google (I know Quiche isn't the Google implementation) reported last year?

I guess it still isn't a fair question though since the linux kernel automatically conducts a software segmentation for TCP, and if you disable that UDP and TCP are equally (non)efficient.

[https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency](https://www.fastly.com/blog/measuring-quic-vs-tcp-computational-efficiency)
![image](https://user-images.githubusercontent.com/17534897/91214979-d55ea080-e6e1-11ea-96dd-0ce39b3685d5.png)

[https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/](https://blog.cloudflare.com/accelerating-udp-packet-transmission-for-quic/)
![image](https://user-images.githubusercontent.com/17534897/91215002-dbed1800-e6e1-11ea-9730-e710e9b639a3.png)

**Comment by junhochoi** [comment]
We don't have similar testing result yet. But you may find some interesting research and reports on sigcomm epiq 2020:
https://conferences.sigcomm.org/sigcomm/2020/workshop-epiq.html

**Comment by victorstewart** [comment]
thanks so much junho. 

here's a link to some of those talks as well:

https://www.youtube.com/playlist?list=PLCqnh80gJ8UZ9I__LCptmTf_07Jb1Ag5y

**Comment by LPardue** [comment]
Ian Swett's keynote at EPIQ contains some good insight into CPU usage from non-quiche implementations. I think the video will become available soon.

**Comment by victorstewart** [comment]
@LPardue 

do you have any idea where Quiche falls in this mix?

![image](https://user-images.githubusercontent.com/17534897/91333309-6cd3fa00-e79b-11ea-9ef9-8162b2f92a8c.png)

**Comment by LPardue** [comment]
I'm not at liberty to comment about that. But we encourage the community to perform their own tests using quiche, while noting that the example applications are designed to demo the API, not maximise performance. For performance-related testing, we recommend the nginx integration. The paper authors from the screenshot you provided, have indicated their future work could include an analysis of quiche using the same framework.

Finally, we love to hear from people that are planning experiments with quiche or have some results to share.

**Comment by victorstewart** [comment]
@LPardue I understand, thanks!

There are further slides on performance stability as # of connections grows, as well as packet loss and reordering rates.

Are you able to comment on these in regards to Quiche? Even if generally so.

And is it possible to maintain 50,000 - 100,000 simultaneous mostly quiet connections per logical core without extreme degradation?

**Comment by LPardue** [comment]
I cannot comment on these details.

**Comment by victorstewart** [comment]
@LPardue fyi [https://github.com/Winters123/QUIC-measurement-kit/issues/4](https://github.com/Winters123/QUIC-measurement-kit/issues/4)
