### ISSUE TITLE
Max Crypto Overhead - Unexpected value

### ISSUE THREAD

**Issue by BiagioFesta** [cloudflare/quiche#623]
Hi,
Using `quiche`, I am trying to pre-compute the the maximum payload admissible in a single packet (for some scenarios).
In order to compute this value I was planning to use all maximum values of all the overheads inside a packet (*header*, *packet number*, and *crypto*, etc...).
On this matter, I saw the constant value for crypto overhead here: [frame.rs:35](https://github.com/cloudflare/quiche/blob/master/src/frame.rs#L35). Note this value is fixed to `8`.

However, during my implementation, I found out that, during the construction of the packet, the `send` function computes this crypto overhead with the following expression: [lib.rs:2027](https://github.com/cloudflare/quiche/blob/master/src/lib.rs#L2027). Note the value of this expression ends up to be `16` (from `ring` crate here https://docs.rs/ring/0.16.15/ring/aead/constant.MAX_TAG_LEN.html).

I was expecting `MAX_CRYPTO_OVERHEAD` being greater or equal to that value.

Probably those two expressions are not referring the same "crypto part of overhead" and I am mistaken, but I wanted to be sure of that not being a bug.

Thanks

**Comment by LPardue** [comment]
I think this is just some unfortunate naming collision.

frame::MAX_CRYPTO_OVERHEAD is quiche's measure of framing overhead of the QUIC [Crypto](https://tools.ietf.org/html/draft-ietf-quic-transport-29#section-19.6) frame. This helps us count the size in bytes of fields that must be present in a Frame, or else the frame would be malformed. We use this in combination with packet packing and flow control. Crypto frames are only sent as part of the handshake.

`crypto_overhead()` represents the AEAD overhead in a QUIC packet at any given encryption level. The packet could contain many types or number of frames, depending on the state of the connection.

**Comment by BiagioFesta** [comment]
Indeed, as I suspected. Thank you for the clarification.
I close this ticket.
