### ISSUE TITLE
Keep Alive + Ping 

### ISSUE THREAD

**Issue by victorstewart** [cloudflare/quiche#635]
can we add a function to generate PING frames? specifically to the C api.

i need a way to send keep alives on idle connections, and drive the timeouts in my IO event loop.

i can submit a PR if you're all amenable to this.

**Comment by ghedo** [comment]
Yeah, that seems like something that could be useful, thanks.

**Comment by normanmaurer** [comment]
@ghedo is there any work planed on this ? If not I would like volunteer for adding support for PING. WDYT ?

**Comment by normanmaurer** [comment]
talked with @ghedo offline ... I will work on a PR soonish..

**Comment by lilongyan-huawei** [comment]
> talked with @ghedo offline ... I will work on a PR soonish..

@normanmaurer At your convenience, would you please tell me when you will submit the PR ？
I‘m also planning to implement this feature.

**Comment by normanmaurer** [comment]
@lilongyan-huawei I didn't start yet... so if you want to work on this please do so. I think I will have no time for the next 2 weeks anyway.

**Comment by normanmaurer** [comment]
@lilongyan-huawei I guess this was never started at your end ?

**Comment by lilongyan-huawei** [comment]
> @lilongyan-huawei I guess this was never started at your end ?

have done. doing tests

**Comment by normanmaurer** [comment]
@lilongyan-huawei thanks a lot... Looking forward to the PR

**Comment by lilongyan-huawei** [comment]
您好,您的邮件我已收到，谢谢.

**Comment by normanmaurer** [comment]
@ehaydenr I think you worked on this one ?

**Comment by CMCDragonkai** [comment]
So currently there's no way to keep an idle QUIC connection alive?

I suppose we can just use the unreliable datagram extension to do this. But the QUIC protocol does specify the usage of PING frame to do this.

**Comment by lilongyan-huawei** [comment]
您好,您的邮件我已收到，谢谢.

**Comment by LPardue** [comment]
This is possible via send_ack_eliciting or send_ack_eliciting_on_path; see

https://docs.quic.tech/quiche/struct.Connection.html#method.send_ack_eliciting

Add in #1361 and should have closed this issue as resolved.
