### ISSUE TITLE
Use android demo to run quiche tlsFailed error occurs

### ISSUE THREAD

**Issue by linxhome** [cloudflare/quiche#636]
Hi，when I compile the quiche for android demo, tlsFailed error always occured. The code branch I used was master. Other Platform like MacOs and Linux is OK. 

was it a bug ? or something else wrong ?

**Comment by linxhome** [comment]
bug fixed when i update the OPENSSLDIR  path to "/system/etc/security"

**Comment by chiwangnvp** [comment]
@linxhome How do you update that?
