### ISSUE TITLE
TlsFail

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#638]
Hi, I tried to run ./server in target/debug/examples on Mac platform, but got error of thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TlsFail', examples/server.rs:87:10. I saw the previous issue says can attach --no-verify with http3-client to solve this problem. But seems not working with ./server

**Comment by danielblignaut** [comment]
Hi, I'm getting the same issue. Did you ever resolve this?
