### ISSUE TITLE
request http3 draft 30 support

### ISSUE THREAD

**Issue by haohetao** [cloudflare/quiche#639]

**Comment by moderation** [comment]
Draft 31 is already out - https://tools.ietf.org/html/draft-ietf-quic-http-31. I know it has been summer holidays in Europe but it looks like development here has stalled

**Comment by LPardue** [comment]
What features of draft 30 and 31 are important to you?

Neither of these drafts make interoperability changes over draft 29.

**Comment by moderation** [comment]
More a case of staying current with the drafts. As there have been a couple of last calls it feels like finalization is close and I know that you follow this very closely https://twitter.com/SimmerVigor/status/1309272293621760000. Chrome and Firefox Nightly have moved relatively in line with the drafts too. So not urgent and if the plan is to skip from 29 to final, great.

**Comment by LPardue** [comment]
I'd like to reassure people that we are actively involved in the working group and standards development. Disclaimer: I'm the QUIC WG co-chair, so I have very close understanding of the WG last call and IETG last call process.

The original request for updating to a newer draft is entirely reasonable. But draft 29 is a solid interoperability target, so its a matter of prioiritzation. If people find draft 30/31 important then we'll happily review contributions.

Making suggestions about a project's status is unhelpful and unconstructive.

**Comment by trevyn** [comment]
Thank you for the clarification of the project's status and the interoperability considerations! I found this information helpful.

**Comment by moderation** [comment]
Interesting update from the Chrome team where they state that they are recommending servers keep support for `h3-29` versus the subsequent 30, 31 - https://blog.chromium.org/2020/10/chrome-is-deploying-http3-and-ietf-quic.html

> Since the subsequent IETF drafts 30 and 31 do not have compatibility-breaking changes, we currently are not planning to change the over-the-wire identifier. What this means is that while we'll keep tracking changes in the IETF specification, we will be deploying them under the h3-29/0xff00001d name. We therefore recommend that servers keep support for h3-29 until the final RFCs are complete if they wish to interoperate with Chrome. However, if the IETF were to make compatibility-breaking changes in a future draft, Chrome will revisit this decision.

So I'd suggest that @LPardue could close this issue. Thanks for the conversation @LPardue

**Comment by moderation** [comment]
Draft 32 is out - https://tools.ietf.org/html/draft-ietf-quic-http-32
