### ISSUE TITLE
Requests with body to NGINX hang when request buffering is enabled

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#640]
[
![1](https://user-images.githubusercontent.com/46128592/94358728-943d2000-00d5-11eb-9793-eea665ee947b.png)
](url)
when the size of request body > 8192(2*page size) , buf->last will identically equal to buf->end.

[
![2](https://user-images.githubusercontent.com/46128592/94358814-21807480-00d6-11eb-97d4-12b7f856ea41.png)
](url)

**Comment by ghedo** [comment]
You really need to provide more information on what the problem you are reporting is, because from what you posted it's really not clear. Like, what is the expected behavior, and what is the behavior you are seeing instead? Describing a way to reproduce the problem would also be helpful, thanks.

**Comment by lilongyan-huawei** [comment]
the bug's description:
 use quiche-nginx as server.  
when I send a request ( the body > 8192(2*page size) bytes),  it will be failed. 


I figured out the reason:
firstly, the length of request body is  greater than client_body_buffer_size(default value is 8192 bytes), nginx will create a buffer that has no real space.  buf->last will identically equal to buf->end , because both of them are 0 .

<img width="848" alt="3" src="https://user-images.githubusercontent.com/46128592/95180771-00660500-07f5-11eb-8e21-494bb12a4048.png">

when the fuction (ngx_http_v3_process_request_body) process the request body,  buf->last will identically equal to buf->end, so this fuction will return  NGX_AGAIN and reading 0 bytes 

![1](https://user-images.githubusercontent.com/46128592/95181188-8da95980-07f5-11eb-96ec-a4be804b9912.png)

**Comment by lilongyan-huawei** [comment]
> You really need to provide more information on what the problem you are reporting is, because from what you posted it's really not clear. Like, what is the expected behavior, and what is the behavior you are seeing instead? Describing a way to reproduce the problem would also be helpful, thanks.




the bug's description:
use quiche-nginx as server.
when I send a request ( the body > 8192(2*page size) bytes), it will be failed.

I figured out the reason:
firstly, the length of request body is greater than client_body_buffer_size(default value is 8192 bytes), nginx will create a buffer that has no real space. buf->last will identically equal to buf->end , because both of them are 0 .

<img width="848" alt="3" src="https://user-images.githubusercontent.com/46128592/95182361-1379d480-07f7-11eb-9e37-3df651a4f30e.png">


when the fuction (ngx_http_v3_process_request_body) process the request body, buf->last will identically equal to buf->end, so this fuction will return NGX_AGAIN and reading 0 bytes

![1](https://user-images.githubusercontent.com/46128592/95182380-1b397900-07f7-11eb-9bf2-eb222f60a04b.png)

**Comment by lilongyan-huawei** [comment]
> You really need to provide more information on what the problem you are reporting is, because from what you posted it's really not clear. Like, what is the expected behavior, and what is the behavior you are seeing instead? Describing a way to reproduce the problem would also be helpful, thanks.



You can test by following this procedure:
1. Quic server:  Deploy Quiche on Nginx, the version of Nginx is nginx 1.16.1,  use the patch that quiche suppot. 
2. Configure a backend server use proxy_pass in conf/nginx.conf
3. Quic Client: Any one client that support http3. for example:     curl --http3 
4. send a post request from client. and the body's length is greater than client_body_buffer_size(default value is 8192 bytes, it can be configured in nginx.conf),  you will send failed.  because the patch(quiche support) of nginx1.16.1  has bug: you can't post a request whose body length is greater than client_body_buffer_size.

**Comment by lilongyan-huawei** [comment]
> You really need to provide more information on what the problem you are reporting is, because from what you posted it's really not clear. Like, what is the expected behavior, and what is the behavior you are seeing instead? Describing a way to reproduce the problem would also be helpful, thanks.

**Comment by ghedo** [comment]
Ok, thanks. Just to double check, did you disable request buffering in NGINX (`proxy_request_buffering off;`)? I can reproduce the problem now but only when request buffering is enabled.

This is actually a known problem as we don't fully support request buffering for HTTP/3 right now, so we recommend disabling it for now.

**Comment by lilongyan-huawei** [comment]
> Ok, thanks. Just to double check, did you disable request buffering in NGINX (`proxy_request_buffering off;`)? I can reproduce the problem now but only when request buffering is enabled.
> 
> This is actually a known problem as we don't fully support request buffering for HTTP/3 right now, so we recommend disabling it for now.

the value of proxy_request_buffering is default (on ?);  
 Since it is not supported, are there plans to support this feature? and When will it be supported ? many thanks.

**Comment by ghedo** [comment]
It's definitely something we should fix at some point, though we don't really have an estimate right now as it's not very high priority (we don't use this option ourselves in production). Would definitely welcome patches though, so I'll leave this ticket open if anyone wants to work on this before we get to it.

**Comment by lilongyan-huawei** [comment]
> It's definitely something we should fix at some point, though we don't really have an estimate right now as it's not very high priority (we don't use this option ourselves in production). Would definitely welcome patches though, so I'll leave this ticket open if anyone wants to work on this before we get to it.

Ok, thanks.
but how do you solve the following problem?
With buffering disabled, the request body is sent to the proxy server as soon as the request is received.In this case, if Nginx has already started sending the request body, the request cannot be passed to the Next Server.

**Comment by lilongyan-huawei** [comment]
> It's definitely something we should fix at some point, though we don't really have an estimate right now as it's not very high priority (we don't use this option ourselves in production). Would definitely welcome patches though, so I'll leave this ticket open if anyone wants to work on this before we get to it.

I disable request buffering in NGINX (proxy_request_buffering off;), but it would not work. Open the logs/error.log, found something wrong. Could you help me to see what's wrong i did ? thank you.

`2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 loss detection timeout expired
2020/10/09 09:49:11 [debug] 315069#0: quiche::recovery: 7277cbfd285ec7253cc7079426edc715ab52f853 timer=13.555556107s latest_rtt=377.679µs srtt=Some(477.323µs) min_rtt=377.679µs rttvar=204.332µs loss_time=[None, None, None] loss_probes=[0, 0, 2] cwnd=14687 ssthresh=18446744073709551615 bytes_in_flight=3785 app_limited=true congestion_recovery_start_time=None delivered=3949 delivered_time=18.063579844s recent_delivered_packet_sent_time=18.063958185s app_limited_at_pkt=3949
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx pkt Short dcid=b599672d23ac05e1d7a9d26cbe1f5daf1b06fb70 key_phase=false len=533 pn=29
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm ACK delay=2257053 blocks=[0..16]
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm HANDSHAKE_DONE
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm CRYPTO off=0 len=476
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm STREAM id=3 off=0 len=24 fin=false
2020/10/09 09:49:11 [debug] 315069#0: quiche::recovery: 7277cbfd285ec7253cc7079426edc715ab52f853 timer=18.080919394s latest_rtt=377.679µs srtt=Some(477.323µs) min_rtt=377.679µs rttvar=204.332µs loss_time=[None, None, None] loss_probes=[0, 0, 1] cwnd=14687 ssthresh=18446744073709551615 bytes_in_flight=4340 app_limited=true congestion_recovery_start_time=None delivered=3949 delivered_time=18.063792811s recent_delivered_packet_sent_time=18.064170914s app_limited_at_pkt=3949
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx pkt Short dcid=b599672d23ac05e1d7a9d26cbe1f5daf1b06fb70 key_phase=false len=29 pn=30
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm ACK delay=2257079 blocks=[0..16]
2020/10/09 09:49:11 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm STREAM id=7 off=0 len=1 fin=false
2020/10/09 09:49:11 [debug] 315069#0: quiche::recovery: 7277cbfd285ec7253cc7079426edc715ab52f853 timer=18.080791815s latest_rtt=377.679µs srtt=Some(477.323µs) min_rtt=377.679µs rttvar=204.332µs loss_time=[None, None, None] loss_probes=[0, 0, 0] cwnd=14687 ssthresh=18446744073709551615 bytes_in_flight=4391 app_limited=true congestion_recovery_start_time=None delivered=3949 delivered_time=18.063920132s recent_delivered_packet_sent_time=18.064298259s app_limited_at_pkt=3949
2020/10/09 09:49:30 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 loss detection timeout expired
2020/10/09 09:49:30 [debug] 315069#0: quiche::recovery: 7277cbfd285ec7253cc7079426edc715ab52f853 timer=27.111814384s latest_rtt=377.679µs srtt=Some(477.323µs) min_rtt=377.679µs rttvar=204.332µs loss_time=[None, None, None] loss_probes=[0, 2, 0] cwnd=14687 ssthresh=18446744073709551615 bytes_in_flight=4391 app_limited=true congestion_recovery_start_time=None delivered=3949 delivered_time=36.145697791s recent_delivered_packet_sent_time=36.146076521s app_limited_at_pkt=3949
2020/10/09 09:49:30 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx pkt Handshake version=ff00001d dcid=b599672d23ac05e1d7a9d26cbe1f5daf1b06fb70 scid=7277cbfd285ec7253cc7079426edc715ab52f853 len=25 pn=14
2020/10/09 09:49:30 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm ACK delay=4518217 blocks=[0..2]
2020/10/09 09:49:30 [debug] 315069#0: quiche: 7277cbfd285ec7253cc7079426edc715ab52f853 tx frm PING
`
