### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#641]
Hi,

I run up both server and client on the same machine, and tried to use the server to transer file to client. But on the client side, it always print "Not found". I believe I've put the file in the right directory, maybe I was wrong.

 I run cargo run --manifest-path=tools/atoml --bin quiche-client -- https://127.0.0.1:4433/file.txt --no-verify on the client side. 
And run cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-server --       --cert tools/apps/src/bin/cert.crt       --key tools/apps/src/bin/cert.key on server side. 

And only "Not found" got print on the client side.

**Comment by junhochoi** [comment]
Please try to set --root <dir> option in quiche-server to point the right directory.

**Comment by yc1997427** [comment]
Thank you very much, it is solved now. Really appreciate!
