### ISSUE TITLE
quiche build is failing on MacOS

### ISSUE THREAD

**Issue by tiwariashish86** [cloudflare/quiche#644]
I am building quiche on MacOs with "cargo build" but getting following error:

--- stderr
clang: error: unsupported argument '-g' to option 'Wa,'
make[3]: *** [CMakeFiles/crypto.dir/mac-x86_64/crypto/chacha/chacha-x86_64.S.o] Error 1
make[2]: *** [CMakeFiles/crypto.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/bssl.dir/rule] Error 2
make: *** [bssl] Error 2
thread 'main' panicked at '
command did not execute successfully, got: exit code: 2

**Comment by junhochoi** [comment]
Can you share some your detail on your build environment?
- quiche version (`git describe`)
- OS version (MacOS version and `uname -a`)
- Xcode version
- Did you run `git submodule update` before build?

**Comment by tiwariashish86** [comment]
1. quiche version : 0.5.1-10-g1746615
2. OS Version : Catalina 10.15.6
3. Xcode 12
4. yes

**Comment by tiwariashish86** [comment]
Please let me know if you need anymore info.

**Comment by inikulin** [comment]
Has the same issue compiling as a dependency on Mac.

**Comment by inikulin** [comment]
Seems like cmake can't determine Clang's asm compiler
```
  -- The ASM compiler identification is unknown
```
 otherwise it should hit this line: https://github.com/google/boringssl/blob/49e9f67d8b7cbeb3953b5548ad1009d15947a523/crypto/CMakeLists.txt#L36

**Comment by inikulin** [comment]
Upgrading cmake to `3.18.3` resolves the issue

**Comment by junhochoi** [comment]
@tiwariashish86 I am using Catalina 10.15.6 and it builds successfully with cmake 3.18.0:

```
% cargo build
    Updating crates.io index
  Downloaded cc v1.0.60
  Downloaded libc v0.2.78
  Downloaded 2 crates (561.8 KB) in 0.68s
   Compiling cc v1.0.60
   Compiling libc v0.2.78
   Compiling log v0.4.11
   Compiling libm v0.2.1
   Compiling untrusted v0.7.1
   Compiling cfg-if v0.1.10
   Compiling spin v0.5.2
   Compiling lazy_static v1.4.0
   Compiling cmake v0.1.44
   Compiling ring v0.16.15
   Compiling quiche v0.5.1 (...)
    Finished dev [unoptimized + debuginfo] target(s) in 1m 43s
% cmake --version
cmake version 3.18.0
```

**Comment by tiwariashish86** [comment]
yeah it resolved my issue. thanks!!
