### ISSUE TITLE
Fix server timeout caused by a packet loss at Handshake

### ISSUE THREAD

**Issue by junhochoi** [cloudflare/quiche#65]
When some of Handshake packet (especially ack of client) is missing, server still received h3 request and prepare to send response, it's not sent to the client. Also in this situation client sent ack to ack from server of Handshake packet which is not allowed.

**Comment by junhochoi** [comment]
pr #66 created.

**Comment by LPardue** [comment]
> When some of Handshake packet is missing

The client or the server Handshake packet?

I'm not too familiar with this area of the code. It seems odd the server would receive request before the handshake completed properly. Am I missing something obvious?

**Comment by junhochoi** [comment]
> > When some of Handshake packet is missing
> 
> The client or the server Handshake packet?
> 
> I'm not too familiar with this area of the code. It seems odd the server would receive request before the handshake completed properly. Am I missing something obvious?

Commit (log and source) has more detailed scenario.

**Comment by LPardue** [comment]
Thanks, I have a better understanding of the problem and the fix. Ileft some code comments on your PR.
