### ISSUE TITLE
Nitpick: possible unnecessary use of &mut Config in connect/accept

### ISSUE THREAD

**Issue by xanathar** [cloudflare/quiche#651]
Checking the code, it seems that `connect` and `accept` both take a `&mut Config` instead of a `&Config` ultimately because `tls::Context::new_handshake` takes a `&mut self` in order to provide a mut pointer to `OPENSSL_EXPORT SSL *SSL_new(SSL_CTX *ctx);` which, incidentally, doesn't seem to change `ctx` at all.

`tls::Context::as_ptr()` is defined as 

```rust
    fn as_ptr(&self) -> *mut SSL_CTX {
        self.0
    }
```

This means that it would be possible to remove all those `mut` everywhere; however this is a change to the public interface which may cause warnings emitted on calling code which previously weren't (plus, it would not reflect the state of `SSL_new` which has no `const` qualifier for the pointer, even if no changes seem to be made to the contents).

If you think such a change would be welcome, I can work a PR; if for compatibility or other reasons you think it's not, feel free to move this issue to the recycle bin :)

**Comment by ghedo** [comment]
This is on purpose actually, in the sense that while using raw pointers allows us to work-around Rust's mutability restrictions, we shouldn't abuse it, so reflecting the fact that we will end up modifying the underlying structures seems to be the correct thing to do here.

**Comment by xanathar** [comment]
> we will end up modifying the underlying structures

Is the code modifying the underlying structures of `Config` though? As far as I can see it doesn't (`SSL_new(SSL_CTX *ctx)` doesnt change `ctx`) but I might be missing some change.

The main reason for the doubt is that at a code review stage it feels very weird to reuse a `&mut` over several connections; the expectation being that either a connection takes a read-only ref to the configuration, or takes ownership of a copy/clone of the configuration.

**Comment by ghedo** [comment]
`SSL_CTX` is reference counted, so `SSL_new()` updates the count. In quiche basically we are just following the convention from the BoringSSL and requiring `&mut` when BoringSSL requires a non-const pointer (though we are not very consistent about this in the internal APIs...).

I mean, it's not a big deal or anything, it just seemed the most logical thing to do at the time.

**Comment by xanathar** [comment]
Makes totally sense now, I didn't see the refcounting.

Thanks for the clarifications!

Closing this.

**Comment by taikulawo** [comment]
rust-openssl Ssl::new take `&self` but convert to `*mut T`,the discussion still can't decide whether is ub or not.

https://github.com/sfackler/rust-openssl/blob/538a5cb737e8d83085553cac01643820dc7ff205/openssl/src/ssl/mod.rs#L2311

https://github.com/sfackler/foreign-types/issues/24

yes, &mut Config can solve this, but has less flexibility, we may consider use UnsafeCell<T> so that we can use &Config instead
