### ISSUE TITLE
Flame graph of quiche 

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#664]
Hi, I'm using perf to make a flame graph meaure the cpu usage of quiche. 
But the output flame graph of running quiche server and client look pretty werid, doesn't show the cpu usage of the quiche.
They seem to be covered by cargo...here is the screen shot of the flame graph. 

![image](https://user-images.githubusercontent.com/43573044/95668552-7e1b6f00-0b6d-11eb-930d-ece6b69f29ba.png)

**Comment by LPardue** [comment]
What is the command line that you used to run the applications?

**Comment by ghedo** [comment]
It appears that you are running perf on the `cargo run` command, which will obviously show you information about that command. You need to run whatever it is you are running without cargo. This is not a quiche issue so closing.
