### ISSUE TITLE
PSK / 0-RTT supported ?

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#683]
Hi there,

I am currently investigate in using quiche within [netty](https://netty.io) by using the C API via JNI. Once thing I was wondering while looking at this was if PSK / 0-RTT is supported at all. I couldn't spot it in the C API. So I was wondering if it is not supported at all or maybe just not exposed yet via C. I tried to check the rust source but my rust skills are still very weak unfortunately so I may have missed it :/

**Comment by ghedo** [comment]
Hello. We currently support receiving 0-RTT data on the server side (with resumption being automatically enabled by BoringSSL). We don't yet support _sending_ 0-RTT data from the client though.

**Comment by normanmaurer** [comment]
Thanks a lot... is this something you are looking into in the near future ? I know its an OSS project so PRs are welcome but I was wondering if this is already on the "to-do-list".

**Comment by ghedo** [comment]
It's definitely something we want to support in the future, but we don't have any plans to implement it right now.
