### ISSUE TITLE
error through make 

### ISSUE THREAD

**Issue by S5h4D3S** [cloudflare/quiche#692]
Ubuntu 18 system
 stable-x86_64-unknown-linux-gnu unchanged - rustc 1.47.0 (18bf6b4f0 2020-10-07)

 Compiling quiche v0.6.0 (/quiche)
error[E0277]: can't compare `&[u8]` with `std::vec::Vec<u8>`
    --> src/lib.rs:1479:34
     |
1479 |             if hdr.dcid.as_ref() != self.scid {
     |                                  ^^ no implementation for `&[u8] == std::vec::Vec<u8>`
     |
     = help: the trait `std::cmp::PartialEq<std::vec::Vec<u8>>` is not implemented for `&[u8]`

error[E0277]: can't compare `&[u8]` with `std::vec::Vec<u8>`
    --> src/lib.rs:1483:34
     |
1483 |             if hdr.scid.as_ref() != self.dcid {
     |                                  ^^ no implementation for `&[u8] == std::vec::Vec<u8>`
     |
     = help: the trait `std::cmp::PartialEq<std::vec::Vec<u8>>` is not implemented for `&[u8]`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
error: could not compile `quiche`.

objs/Makefile:1361: recipe for target '../quiche/target/release/libquiche.a' failed
make[1]: *** [../quiche/target/release/libquiche.a] Error 101

**Comment by morkrispil** [comment]
Confirming that on Ubuntu 18 with either builtin cmake and 3.18.4

**Comment by S5h4D3S** [comment]
Ubuntu 20  make went through, but I can't install it.

**Comment by ghedo** [comment]
This is weird, our CI environment also uses Ubuntu 18.04, and quiche builds fine there. See e.g. https://github.com/cloudflare/quiche/runs/1347708180

Are you sure you are actually using rustc 1.47 (latest stable), rather than the version shipped by the operating system?

**Comment by S5h4D3S** [comment]
yes I did at 18 rustc 1.47 (latest stable) I cracked it manually at version 20 finally with a lot of dependencies needed
root@test:/usr/sbin# nginx -v
Linux version: nginx/1.18.0 (quiche-e0394a8)

**Comment by S5h4D3S** [comment]
Job for nginx.service failed because a timeout was exceeded.
See "systemctl status nginx.service" and "journalctl -xe" for details.
root@test:~/nginx-1.16.1# service nginx status
● nginx.service - A high performance web server and a reverse proxy server
     Loaded: loaded (/lib/systemd/system/nginx.service; enabled; vendor preset: enabled)
     Active: failed (Result: timeout) since Tue 2020-11-03 14:32:45 UTC; 3s ago
       Docs: man:nginx(8)
    Process: 33330 ExecStartPre=/usr/sbin/nginx -t -q -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
    Process: 33342 ExecStart=/usr/sbin/nginx -g daemon on; master_process on; (code=exited, status=0/SUCCESS)
      Tasks: 0 (limit: 2280)
     Memory: 316.0K
     CGroup: /system.slice/nginx.service

Nov 03 14:31:15 test systemd[1]: Starting A high performance web server and a reverse proxy server...
Nov 03 14:31:15 test systemd[1]: nginx.service: Can't open PID file /run/nginx.pid (yet?) after start: Operation not permitted
Nov 03 14:32:45 test systemd[1]: nginx.service: start operation timed out. Terminating.
Nov 03 14:32:45 test systemd[1]: nginx.service: Killing process 33345 (nginx) with signal SIGKILL.
Nov 03 14:32:45 test systemd[1]: nginx.service: Killing process 33347 (nginx) with signal SIGKILL.
Nov 03 14:32:45 test systemd[1]: nginx.service: Killing process 33345 (nginx) with signal SIGKILL.
Nov 03 14:32:45 test systemd[1]: nginx.service: Killing process 33347 (nginx) with signal SIGKILL.
Nov 03 14:32:45 test systemd[1]: nginx.service: Failed with result 'timeout'.
Nov 03 14:32:45 test systemd[1]: Failed to start A high performance web server and a reverse proxy server.
root@test:~/nginx-1.16.1# nginx -v
nginx version: nginx/1.16.1 (quiche-e0394a8)
simple after placing make nginx binary into /usr/sbin/  it doesn't work neither under ubuntu 20 installed boringssl v1.3 openssl1.3

**Comment by S5h4D3S** [comment]
spent Usage:  2.57 GB with an upgrade to Ubuntu 20 and installing all dependencies to end up with binary that is telling nginx/1.16.1 (quiche-e0394a8) or nginx/1.18.0 (quiche-e0394a8) that I can't install it or use it. Nice waste of 10 hours please tell everyone which system it does work what dependencies are necessary and so on... or do an official release with Nginx that is possible to install it

**Comment by LPardue** [comment]
Did you try running the binary in the directory it was built?

**Comment by S5h4D3S** [comment]
I tried everything one VPS on another VPS simple end up with 2 binaries that telling we are quiche-e0394a8, but do not work tried docker, hard copy simple no chance to make it running on Ubuntu 18 nor 20  :-( I gave up I will wait until nginx or apache will release version with http/3 support.

**Comment by LPardue** [comment]
Well thats quite a lot of tests without providing any nginx error logs to help us understand what your problem might be. 

Good luck with Apache.

**Comment by ghedo** [comment]
The original report was about a build failure, which sounds like it solved, so closing this now.

**Comment by S5h4D3S** [comment]
> Did you try running the binary in the directory it was built?

I will gladly provide you logs from Nginx, but under Ubuntu 18 I was not able to make the binary. And under Ubuntu 20 there was no log generated by the created binary whatsoever. 
nginx -v told me the version
Linux version: nginx/1.18.0 (quiche-e0394a8) , but nginx was not running. I tried sudo systemctl restart Nginx and it showed me errors Nov 03 14:09:37 test systemd[1]: Nginx.service: start operation timed out. Terminating.

The original report was a failure. Now I have running Nginx 1.18 with http/2 support since http/3  on Ubuntu 18 nor Ubuntu 20 with generated binary won't work. Maybe the problem is VPS providers digital ocean Vultr probably their old obsolete servers can't running it.
