### ISSUE TITLE
Connection migration supported ？

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#698]
Hi there,

I am currently investigate in using proxy protocol within quiche， but i have a question: does quiche support connection migration in server and client？ 
if supported, there are multiple IP and Port in the same connection, how could I do ?

**Comment by junhochoi** [comment]
Currently quiche don't support connection migration yet.

**Comment by lilongyan-huawei** [comment]
> Currently quiche don't support connection migration yet.

OK~  So, does quiche support proxy protocol?

**Comment by junhochoi** [comment]
What do you mean by "proxy protocol"? If you mean HAProxy's [PROXY](https://www.haproxy.com/blog/haproxy/proxy-protocol/) protocol, we don't support it.

**Comment by Rouzip** [comment]
Will quiche implement connection migration recently and what is its priority?
