### ISSUE TITLE
running quiche-server and quiche-client without cargo run

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#703]
Hi, I want to do CPU performance testing on quiche, needs to run quiche-server and client without using cargo run. Is there any way to do this?

**Comment by junhochoi** [comment]
If you have built, binaries will be available under `tools/apps/target/{debug|release}/`

**Comment by yc1997427** [comment]
Hi, thanks, I run the binary, got this error,

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TlsFail', src/bin/quiche-server.rs:105:54
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1221
   3: core::result::Result<T,E>::unwrap
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/result.rs:973
   4: quiche_server::main
             at /home/yuwang1/quic/quiche/tools/apps/src/bin/quiche-server.rs:105
   5: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227

**Comment by junhochoi** [comment]
You need to set a valid TLS certificate (use --cert and --key option. there is an example one under examples/)

**Comment by yc1997427** [comment]
Thank you very much for your help, really appreciate. I just run again, they both work, but the client seemed couldn't connect with the server, I got  connection timed out after 30.016716215s

The command I run for the server is sudo ip netns exec blue ./quiche-server --listen  192.168.0.1:4433 --cert ~/quic/quiche/tools/apps/src/bin/cert.crt --key ~/quic/quiche/examples/cert.key,

command I run for the client is ./quiche-client 192.168.0.4:4433 --no-verify

**Comment by junhochoi** [comment]
What's error message you got? You may run server and client with RUST_LOG=trace.
Also, you need to give a URL in quiche-client, such as ./quiche-client --no-verify https://192.168.0.4/4433/pathname

**Comment by yc1997427** [comment]
The error I got was connection time out, [2020-11-05T21:30:14.860775703Z ERROR quiche_client] connection timed out after 30.01974223s

Yes, I run ./quiche-client https://192.168.0.1:4433/ --no-verify
