### ISSUE TITLE
Test failing on arm 32bit/windows

### ISSUE THREAD

**Issue by junhochoi** [cloudflare/quiche#712]
https://github.com/cloudflare/quiche/runs/1378520862?check_suite_focus=true
```failures:

---- tests::empty_stream_frame stdout ----
thread 'main' panicked at 'assertion failed: `(left == right)
  left: `Ok(40)`,
 right: `Ok(39)`', src/lib.rs:5229:9


failures:
    tests::empty_stream_frame

test result: FAILED. 292 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out
```

Not every time but fairly often.

**Comment by ghedo** [comment]
That's a known flappy test (on any architecture) IIRC, have you tried running it again?

**Comment by junhochoi** [comment]
> That's a known flappy test (on any architecture) IIRC, have you tried running it again?

I got multiple failures already. If you want I can switch to `cargo test` in #711 again but I'm afraid we will see it again.
Yes I remember this is not a new one... not sure why I see more often in those architectures.

**Comment by junhochoi** [comment]
Made a PR #716 for the fix

**Comment by junhochoi** [comment]
Another one from #711 (without #716): https://github.com/cloudflare/quiche/runs/1382192827?check_suite_focus=true
