### ISSUE TITLE
transport speed is abnormally low 

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#714]
Hi

I run quic server and client on local machines. But I found out that the transport speed between client and servers are abnormally low, around 1500 bps for 50MB file, 137bps for 200MB file. I run quiche-server and quiche-binary. I'm wondering if this is the usual performance of quiche or is there anything I need to change.

**Comment by LPardue** [comment]
How are you measuring the speed? Some trace logs and packet captures would help understand things better.

**Comment by yc1997427** [comment]
Hi, I'm measuring the speed with the .stats() method. I run the binary of quiche-server and quiche-client, don't think I can do RUST_LOG=trace. 
The command run server is ./quiche-server --root ~/quic/quiche/tools/apps/target/debug  --listen  192.168.0.1:4433 --cert ~/quic/quiche/examples/cert.crt --key ~/quic/quiche/examples/cert.key, 

run client is   ./quiche-client https://192.168.0.1:4433/output.dat --no-verify

I run both server and client on one single server seprated by namespace, the traffic flows to another server and then traverse back.

Here is the topology.
![image](https://user-images.githubusercontent.com/43573044/99829439-361c3e80-2b54-11eb-95d8-56cac4c96ad3.png)

**Comment by LPardue** [comment]
We've discussed this in the Slack and there seemed to be some issues with your testbed's performance. Is that still the case? Can we close this issue since the reproduction criteria seem hard without more detail.

**Comment by yc1997427** [comment]
Yes, sorry for taking it so long. I'll close it now.
