### ISSUE TITLE
build for win32 failed

### ISSUE THREAD

**Issue by foroughmajidi** [cloudflare/quiche#717]
I want to build quiche for win32 and built it as following:
cargo target i686-pc-windows-msvc
cargo build --target i686-pc-windows-msvc

but I got these errors:
![quiche](https://user-images.githubusercontent.com/51900859/98819316-f366b200-2441-11eb-9039-f518cb39096d.png)

**Comment by junhochoi** [comment]
please make sure you are using latest stable rustc, such as 1.47

**Comment by foroughmajidi** [comment]
it's 1.45

**Comment by ghedo** [comment]
As per @junhochoi's comment (and the build instructions in the README), Rust 1.47 or later is required to build quiche, so you'll need to upgrade your toolchain (e.g. using rustup). Closing since this is already documented.
