### ISSUE TITLE
flow control supported?

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#719]
Hi, there.
Does quiche support flow control within multiplexing?

**Comment by junhochoi** [comment]
quiche implements the connection/stream flow control mechanism what is defined in QUIC transport draft. Is there any specific you are looking?

**Comment by lilongyan-huawei** [comment]
> quiche implements the connection/stream flow control mechanism what is defined in QUIC transport draft. Is there any specific you are looking?

 I make a test about flow control:  client send multiple streams in one connection, and it receive a ApplicationClose frame from server.  what is the meaning of ApplicationClose frame?
