### ISSUE TITLE
Allow to pass into CMAKE flags when building BoringSSL

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#732]
I would love to be able to use `-DOPENSSL_C11_ATOMIC` when building the vendored BoringSSL lib as it can make a lot of difference especially when you do a lot of handshakes. Basically I would love to do the same as we did in netty-tcnative:

https://github.com/netty/netty-tcnative/pull/568

I know I could just build my own BoringSSL lib and link against it but this sounds like something that could be easily supported without the need to build BoringSSL myself.

**Comment by normanmaurer** [comment]
This would also be super useful to set things like:

```
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 
```

**Comment by normanmaurer** [comment]
For now I just define all of this via environment variables, which works but feels a bit hacky.

**Comment by cntrump** [comment]
I think you can build BoringSSL alone, and set QUICHE_BSSL_PATH=/path/to/your/boringssl

Take a look my script
https://github.com/cntrump/build_curl/blob/main/build_quiche.sh

**Comment by normanmaurer** [comment]
I know... It just felt a bit of overkill for such a thing.. Let me just close this for now as there is a way to archive it.
