### ISSUE TITLE
Add possibility to be notified once a MAX_STREAMS frame was received

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#734]
At the moment there seems to be no way to be notified once it is "safe" to retry creating a new stream.

I had the following use case here:

* stream limit of 1 stream is present.
* create one stream and close it
* try to create a new stream again.

Depending on the timing the creation of the second stream may fail as we may not have received a new MAX_STREAMS frame yet that would set the streams to 2.

It would be nice to be "notified" once there is more room for creating new streams. Ideally this would also include the number of streams that can be created before we will hit the limit again.

Without this I struggle to find a way to do smart retries as I don't know at which point I should try to create a new stream again.

Maybe I am just missing something, so I am happy to be pointed in the right direction.

**Comment by normanmaurer** [comment]
After talking with @LPardue I realised that all I need would be really a getter that can tell me how many more streams I can open. This way I could recheck this one after I fead some data into the connection via `recv` and if there is room again create the stream.

**Comment by LPardue** [comment]
Yeah I don't know if there is a good reason we don't expose the max stream ID permitted by peer, this might provide a solution for https://github.com/cloudflare/quiche/issues/397

**Comment by normanmaurer** [comment]
Is this something you consider in the short term? Be able to make smart decision about creating streams would be very useful for me.

**Comment by normanmaurer** [comment]
@bagder would this be good enough for you as well ?

**Comment by bagder** [comment]
I think so. I basically just need an answer to *"can I open a new h3 request over on this connection?"*, because otherwise I need to either queue it or create another connection to send if over.
