### ISSUE TITLE
Qlog usage 

### ISSUE THREAD

**Issue by yc1997427** [cloudflare/quiche#744]
Hi, may I ask how to use qlog in running quiche-client and quiche-server, I noticed it is in the code, but there is no option to specify qlog.

**Comment by LPardue** [comment]
Hey! Try defining the `QLOGDIR` environment variable to a writable path when you run either one of those. Quiche will generate a qlog file named after the unique connection ID.

**Comment by yc1997427** [comment]
Hi, thank you very much! Really appreciate. And if there is a way which can produce the trace of running the binary of quiche-server or client, like RUST_LOG=trace. I don't want to run with cargo.

**Comment by LPardue** [comment]
yes, run the binary directly without cargo.

**Comment by ghedo** [comment]
Looks like this was answered, so closing.
