### ISSUE TITLE
quiche_h3_conn_poll(...) uses the wrong return type in quiche.h 

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#748]
Return type in c header file is not correct:

https://github.com/cloudflare/quiche/blob/master/include/quiche.h#L505

This should be `i64` or `int64_t`. The implementation in ffi.rs is correct tho:
https://github.com/cloudflare/quiche/blob/master/src/h3/ffi.rs#L89-L92

**Comment by ghedo** [comment]
Nice catch, thanks! Fix in https://github.com/cloudflare/quiche/pull/753.
