### ISSUE TITLE
Expose error code / message of APPLICATION_CLOSE when receiving the frame

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#766]
It would be very useful to be able to get access to the error code / message of an received APPLICATION_CLOSE frame. This way a user of quiche can better understand on why a connection was closed in the first place.

For example I am using quiche in netty and currently building an h3 layer on top of it in which I would love to expose some more details about why a remote peer closed the connection

**Comment by normanmaurer** [comment]
The same may also be true for `CONNECTION_CLOSE`.

Maybe it would be just good enough to expose something that can be "queried" once a connection is marked as closed ?

**Comment by normanmaurer** [comment]
Any preference / ideas here ? I would be happy to work on a PR as well.

**Comment by normanmaurer** [comment]
Any idea ? I just encountered the problem again that the connection close frame was received due ALPN mismatch but there is no way for me to know without enabling trace logging.

**Comment by LPardue** [comment]
Seems like a reasonable idea. There's a few ways this could be done, have you got any sketches of what would address your case? Are you interested in knowing of a connection error that was **sent**?

**Comment by normanmaurer** [comment]
I am mainly interested in the receiving side (at least atm)... I was thinking of maybe just expose an "getter" on the connection (as an optional)

**Comment by normanmaurer** [comment]
I just wanted to ensure this is a "reasonable" way how to expose something like this before trying to come up with a PR.

**Comment by LPardue** [comment]
The simplest option is probably something that is the mirror of https://docs.quic.tech/quiche/struct.Connection.html#method.close. So you can access `bool: app, err: u64, reason: [u8]` of the received CONNECTION_CLOSE frame. Independent of the exact API, it seems we'd need to store the information in the library, which could be done during processing (`src/lib.rs:process_frame()`).

**Comment by normanmaurer** [comment]
yes... And the same also for `APPLICATION_CLOSE`.. @LPardue if this sounds reasonable I will work on a PR, wdyt ?

**Comment by LPardue** [comment]
yep. It's worth clarifying that in QUIC transport terms, the wire frame is always CONNECTION_CLOSE but with different type codepoints and fields, so quiche models these as different frame::Frame::Types even if they are conceptually similar. For simplicity I think just one accesor, with the `bool: app` is going to be cleanest. But while you work on this consider if you think knowing the received "transport CONNECTION_CLOSE" frame's `Frame Type` field is useful (see https://tools.ietf.org/html/draft-ietf-quic-transport-34#section-19.19)

**Comment by normanmaurer** [comment]
@LPardue I was thinking on exposing this as a struct with one getter. Otherwise we would need to have 3 getters which sounds like something horrible ... WDYT ?

**Comment by LPardue** [comment]
yeah a single getting is the way to do it here. However, you could avoid defining a struct and do something like this in the Rust API. 

```
fn get_foo(&mut self, reason: &mut [u8]) -> Result<(bool, u64, )>
```

And then the FFI can be something like 

```
ssize_t get_foo(quiche_conn *quic_conn, bool* is_app, uint64_t *stream_id, uint8_t *reason, size_t reason_len);
```

**Comment by normanmaurer** [comment]
yep... I was more talking about the rust API here. But yep good idea about the tuple here.

**Comment by normanmaurer** [comment]
Alright... I will start working on this. Stay tuned
