### ISSUE TITLE
quiche_config_set_max_idle_timeout() - unit?

### ISSUE THREAD

**Issue by bagder** [cloudflare/quiche#768]
In the `quiche.h` header file, most function calls that involve a timeout seems to specify a unit in the comment describing it. Not for this.

Is it nanoseconds?

**Comment by junhochoi** [comment]
It's milliseconds. See https://tools.ietf.org/html/draft-ietf-quic-transport-32#section-18.2

**Comment by bagder** [comment]
Thanks. Maybe add that in a comment? It's not super obvious that it uses the same unit as the underlying protocol.

**Comment by bagder** [comment]
Maybe also mention what/if quiche sets some value by default? I would presume I'm not the only user who can't recall those specific details from the spec... =)
