### ISSUE TITLE
Improve how dependent PRs are managed

### ISSUE THREAD

**Issue by walid002** [cloudflare/quiche#772]
Hey there :hand: 
Actually this is a suggestion to improve how dependent PRs are handled in this project. Example of a PR that depends on another one: https://github.com/cloudflare/quiche/pull/771. And after a quick search, you can easily find several other PRs like this.

**Solution I'd like to share**
Introduce to this project [Dpulls](https://github.com/marketplace/dpulls), a Github app that make easier to manage dependent PRs. Basically:

- :star2: It prevents a PR to be merged before its dependencies.
- :eyes: It gives more visibility to the developers so they know why a PR cannot be merged.
- :heart: Avoid any accidental merge that can break your master branch.

In addition to that:
- Dpulls has support for cross-referencing (dependency from another project).
- Doesn't require any special config to add.
- Nothing to change in your current workflow. As you usually do, just write `depends on #pr` or `depends on owner/repo#pr` if from another project, and Dpulls will do the job :muscle:  

Dpulls in action :rocket: :
![dependency (1)](https://user-images.githubusercontent.com/75539612/101259622-327ae100-372a-11eb-8aba-2a2638083d1b.png)

I'm seeing that in this project you already use the [WIP](https://github.com/marketplace/wip) Github app. Well, [Dpulls](https://github.com/marketplace/dpulls) is kinda similar to it, but for dependent PRs.

I hope that you will like this suggestion :relaxed:

**Comment by ghedo** [comment]
Thanks for the suggestion. We don't usually have that many dependent PRs to warrant adding a new bot IMO, but we'll keep your project in mind if this changes.
