### ISSUE TITLE
qlog output is malformed for packet_sent events when raw_encrypted is not None 

### ISSUE THREAD

**Issue by hawkinsw** [cloudflare/quiche#785]
Hello!

First, thanks for the community contribution of the qlog library! 

I was investigating how qlog would handle events that include raw data and noticed a problem. When raw_encrypted or raw_decrypted are not None in the object to be serialized, the resulting qlog output is corrupt. 

I have a fix for this issue and the PR is incoming. 

Thanks again for the library!
Will

**Comment by ghedo** [comment]
Fixed by https://github.com/cloudflare/quiche/commit/be23b6fcc3ce3bd595bef91931d248268b1da4c5.
