### ISSUE TITLE
quiche is slower than http2

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#787]
Hi, there
I make a test: client  requests a file which size is 200K bytes form Server，under all the same conditions, quic is slower than tcp.
quic:(the http3-client of the quiche) : the total cost time is 450ms;
tcp: (curl ): the total cost time is 150ms;

from the quiche log of server, I found some questions: 
1. there are so many ack delay that the server send slowly. 
2. there are many app_limited=false
![ack_delay](https://user-images.githubusercontent.com/46128592/102085655-e62e5000-3e51-11eb-8824-93eafaa1d957.png)
![app_limited](https://user-images.githubusercontent.com/46128592/102085664-e890aa00-3e51-11eb-9f64-055a6ad858c0.png)

So i want to know how to turn off the ack delay. thanks.

below is the  debug log of quiche.
[error (19).log](https://github.com/cloudflare/quiche/files/5688926/error.19.log)

**Comment by chenzhiguo** [comment]
mark
