### ISSUE TITLE
Enable Backtrace

### ISSUE THREAD

**Issue by Samy432** [cloudflare/quiche#796]
I would like to enable RUST_BACKTRACE=1 environmental variable.

I try setting it by 

RUST_BACKTRACE=1 cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-server -- \
      --cert tools/apps/src/bin/cert.crt \
      --key tools/apps/src/bin/cert.key

Sinnce im not able to see the and traces, i would like to know the approach in setting it up

**Comment by LPardue** [comment]
Are you hitting a panic, which would then show the generated backtrace?

**Comment by ghedo** [comment]
No reply for a while, so closing. Feel free to re-open if you can provide more information.
