### ISSUE TITLE
[proposal] Flutter plugin using dart:ffi

### ISSUE THREAD

**Issue by iapicca** [cloudflare/quiche#799]
[Flutter](https://flutter.dev/) is a popular framework for mobile (stable), web (beta) and desktop (dev) that ranks as [16th most starred repo on github](https://gitstar-ranking.com/repositories)

At the moment dart team seems to be [too busy to implement http/3 in Dart](https://github.com/dart-lang/sdk/issues/38595#issuecomment-712857906) 
it would be great if `quiche` team, possibly with the help of the [community](https://github.com/fluttercommunity/community/issues/59) could provide support for `flutter` 

I see that quiche already provides support for [android](https://github.com/cloudflare/quiche#building-for-android) and [ios](https://github.com/cloudflare/quiche#building-for-ios) **_but_**, 
as [dart:ffi](https://api.dart.dev/stable/2.10.4/dart-ffi/dart-ffi-library.html) allows [interoperability with native code](https://flutter.dev/docs/development/platform-integration/c-interop) that seems to work well with rust [ references: [1](https://medium.com/flutter-community/using-ffi-on-flutter-plugins-to-run-native-rust-code-d64c0f14f9c2), [2](https://dev.to/sunshine-chain/dart-meets-rust-a-match-made-in-heaven-9f5), [3](https://medium.com/flutter-community/how-to-call-a-rust-function-from-dart-using-ffi-f48f3ea3af2c)]
an implementation through `dart:ffi` would be definitely offer better performances (in a nutshell allowing to do [this](https://res.cloudinary.com/practicaldev/image/fetch/s--0CJOVZrW--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://i.ibb.co/VW6yrFD/flutter-channels2.jpg) instead of [that](https://res.cloudinary.com/practicaldev/image/fetch/s--SpIbrXDL--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://i.ibb.co/B3xSFNn/flutter-channels.jpg))
and [dart:ffi works also on desktop](https://timsneath.medium.com/windows-fun-with-dart-ffi-687c4619e78d)

thank you for your time

**Comment by LPardue** [comment]
Can you simply use quiche via the C FFI? For instance, this is the approach that some folks have taken with Java, integrating quiche via quiche's C FFI and the JNI.

**Comment by iapicca** [comment]
@LPardue thanks for the quic ;) ;) ;)  answer

the interaction between native code and flutter still happens through the platform
but in short yes, you can directly interact with a native function

```dart
import 'dart:ffi'; // For FFI
import 'dart:io'; // For Platform.isX

final DynamicLibrary nativeAddLib = Platform.isAndroid
    ? DynamicLibrary.open("libnative_add.so")
    : DynamicLibrary.process();
```
([source](https://flutter.dev/docs/development/platform-integration/c-interop#step-3-load-the-code-using-the-ffi-library)) 

as a matter of fact a bunch of db for flutter do exactly that
nevertheless I wouldn't use word `simply`
I believe that a bunch of abstraction is required as flutter is very much declarative

side note, I almost forgot that [dart:ffi works also on desktop](https://timsneath.medium.com/windows-fun-with-dart-ffi-687c4619e78d)

**Comment by LPardue** [comment]
I'm not sure what the ask is. Plenty of folks are integrating quiche into different runtimes etc. That can be done independent of the quiche project needing to do anything.

**Comment by iapicca** [comment]
I just think that it would be great if there was a quiche [plugin](https://pub.dev/) for flutter
even better if it comes directly from quiche

**Comment by joe-getcouragenow** [comment]
Glad this has been raised because we are also looking at this area.

As far as i know, this would mean that they you are not dependent on the networking stack ?

Also would this mean that you must run http/3 on your server ?  quiche supports http/2, fallbacks  ?

Also would that get developers access to the new Web Transport P2P aspects via quiche ?

**Comment by LPardue** [comment]
This proposal seems like something better developed and maintained by folks closer to the Flutter community.
