### ISSUE TITLE
Any John Travolta fans here?

### ISSUE THREAD

**Issue by TheKalin** [cloudflare/quiche#805]
Hi, is the https://github.com/cloudflare/quiche/blob/master/src/h3/mod.rs#L1453 some form of Easter egg? :) 

I noticed this little thing during traffic analyze and I would like to confirm if I connected  the dots well. 

![image](https://user-images.githubusercontent.com/8446513/104588728-193e4c00-5669-11eb-92dc-40bf9d8abbaa.png)

Is this a reference to the movie/soundtrack? :D 

![image](https://user-images.githubusercontent.com/8446513/104588767-28bd9500-5669-11eb-9bc8-30a1b2564bb4.png)

If it is than kudos for you :)

**Comment by LPardue** [comment]
Yes, I'm a fan of John Travolta https://twitter.com/SimmerVigor/status/1289232613002141702?s=09

**Comment by TheKalin** [comment]
Hah. Thank you for a brief moment of "WTF?!" and for bringing a smile on my face after I connected the dots :D 

I'm closing the issue :)
