### ISSUE TITLE
nginx option to disable 0-rtt

### ISSUE THREAD

**Issue by HQuest** [cloudflare/quiche#806]
As found and highlighted by a few security folks, the 0-rtt feature, while extremely helpful, is also prone to replay attacks. While quiche integration with nginx is still in experimental phases, it would still be appreciated to have a configuration option to disable 0-rtt, either per location (static pages/images serving locations can still benefit from it), per virtual host or server wide.

**Comment by ghedo** [comment]
There is one already https://nginx.org/en/docs/http/ngx_http_ssl_module.html#ssl_early_data which should work for QUIC too (and it's disabled by default). Have you tried it? If that doesn't work there is probably a bug somewhere.

**Comment by ghedo** [comment]
The original was answered, so closing this. Feel free to re-open if the above suggestion doesn't work.
