### ISSUE TITLE
how to close the ack delay?

### ISSUE THREAD

**Issue by lilongyan-huawei** [cloudflare/quiche#812]
￼
![ack-delay](https://user-images.githubusercontent.com/46128592/105002795-cb608400-5a6c-11eb-960f-ab9f0c9fe03d.png)

**Comment by lilongyan-huawei** [comment]
how to close the ack delay, and is there some problems if close it ?

**Comment by junhochoi** [comment]
ACK delay is how much time spent between data received and ack sent back. It's measured by quiche internally and no interface to change it. It will be large if you have a debug build but should be small when you have a release build, if there is no external delay when calling quiche APIs.

**Comment by lilongyan-huawei** [comment]
> ACK delay is how much time spent between data received and ack sent back. It's measured by quiche internally and no interface to change it. It will be large if you have a debug build but should be small when you have a release build, if there is no external delay when calling quiche APIs.

I want to change the source code of quiche to make ACK delay is 0, could you tell me what i should do ?

**Comment by junhochoi** [comment]
You may modify where ack frame is created https://github.com/cloudflare/quiche/blob/master/src/lib.rs#L2254

**Comment by ghedo** [comment]
We recommend to avoid messing with quiche's internals like that. However this seems to have been answered, so closing.
