### ISSUE TITLE
Is it realtime game/multiplayer ready?

### ISSUE THREAD

**Issue by greenmughal** [cloudflare/quiche#819]
I need UnReliable realtime messaging plus Reliable messaging for sending events as messages, is it possible, any hints are good.
Thanks

**Comment by LPardue** [comment]
quiche support reliable streams and unreliable datagrams. The docs describe how an application can use the methods send/recv_stream/dgram - e.g. https://docs.quic.tech/quiche/struct.Connection.html#method.stream_send

**Comment by greenmughal** [comment]
thanks
