### ISSUE TITLE
Update ring version to support Apple Silicon (m1)

### ISSUE THREAD

**Issue by normanmaurer** [cloudflare/quiche#825]
Hi there,

would it be possible to update the used ring version and so also support Apple Silicon (m1) ?

Related to: https://github.com/briansmith/ring/issues/1063#issue-723460081

**Comment by normanmaurer** [comment]
After running `cargo update` locally I can successfully compile it on Apple Silicon (m1)

**Comment by junhochoi** [comment]
It's good to hear quiche works on M1! Can you run `cargo test` also?

**Comment by normanmaurer** [comment]
@junhochoi yes all pass... Also my project which uses quiche pass all tests on Apple Silicon (m1)
