### ISSUE TITLE
Change congestion control algorithm between Cubic and NewReno?

### ISSUE THREAD

**Issue by vanvantong** [cloudflare/quiche#827]
Hi all,

As I read in this blog, quiche now supports both Cubic and NewReno:
https://blog.cloudflare.com/cubic-and-hystart-support-in-quiche/

How do I configure to select one of them manually?
Thank you in advance!

Best regards,
Van

**Comment by tbu-** [comment]
[Config::set_cc_algorithm](https://docs.rs/quiche/0.6.0/quiche/struct.Config.html#method.set_cc_algorithm)

**Comment by vanvantong** [comment]
Hi,

Thank you for your response.
When I follow the readme of quiche, there is  an instruction like this:

 $ cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-server -- \
      --cert tools/apps/src/bin/cert.crt \
      --key tools/apps/src/bin/cert.key

What is the role of this command? When I run it, there is nothing.

Best regards,
Van

**Comment by tbu-** [comment]
That command looks like it starts a QUIC server. In netstat I can see it listening on UDP port 4433 on localhost (127.0.0.1).

**Comment by vanvantong** [comment]
Thank you very much.

**Comment by junhochoi** [comment]
When you use `quiche-server`, you can specify CC algorithm to use using `--cc-algorithm <name>`. `<name>` can be `reno` or `cubic` for now. If you are writing the code, you can use the API @tbu mentioned above (there is C FFI too).
