### ISSUE TITLE
Parsing packet header failed: BufferTooShort

### ISSUE THREAD

**Issue by vanvantong** [cloudflare/quiche#833]
Hi all,

I want to create a web server and access it using Google Chrome. As I know, I have to generate a certificate and private key and use it for quiche server. I used letsencrypt to generate it.
Then, I run quiche server as follows:

_cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-server -- --cert /home/vantong/Desktop/vanvantong.tk/fullchain.pem --key /home/vantong/Desktop/vanvantong.tk/privkey.pem --root /var/www/_

When I access to this server using Google Chrome as follows:

_google-chrome --new-window -incognito --allow-file-access-from-files --no-sandbox --no-proxy-server --enable-quic --origin-to-force-quic-on=vanvantong.tk:443 --host-resolver-rules='MAP vanvantong.tk:443 127.0.0.1:4433' https://vanvantong.tk_

I got an error from console of quiche server:

_[2021-01-30T08:27:45.113775879Z ERROR quiche_server] Parsing packet header failed: BufferTooShort
[2021-01-30T08:28:00.465013926Z ERROR quiche_server] Parsing packet header failed: BufferTooShort
[2021-01-30T08:28:14.156024692Z ERROR quiche_server] Parsing packet header failed: BufferTooShort
[2021-01-30T08:28:27.550221901Z ERROR quiche_server] Parsing packet header failed: BufferTooShort_

Anybody know why? 
Thank you in advance.

Best regards,
Van

**Comment by junhochoi** [comment]
Can you try the same with adding `--quic-version=h3-29` to Chrome command line option?

**Comment by vanvantong** [comment]
Hello JunHoChoi,
When I update Google Chrome, the problem is solved. However, Google Chrome cannot access to this web server, but I can access via quiche client.
There is no error in the console of quiche server, so I don't know why there is no connection between them.

Best regards,
Van

**Comment by junhochoi** [comment]
You may try `sudo RUST_LOG=trace ./quiche-server...` to get quiche debug log. But I'm confused -- you run quiche-server with port 8080 and nginx configuration also has `listen 443 quic...`. Which one do you want to use? (nginx or quich-server?). What happen if you try to access port 443?

**Comment by vanvantong** [comment]
I want to create a web server to stream video using QUIC. Therefore, I have to use both nginx and quiche-server. 
When I access to URL: https://10.12.20.116:443, it doesn't work.
Do you have any suggestions?

**Comment by vanvantong** [comment]
I want to create a web server to stream video using QUIC. When I change from ngnix to apache, the problem is solved. 
Thank you very much.

**Comment by LPardue** [comment]
Based on your nginx configuration you need to use http:// for port 8080 and https:// for port 4433

**Comment by vanvantong** [comment]
Hello, 

For nginx, I change configuration as follows:

        _listen       8080;
        server_name  vanvantong.tk;
        #charset koi8-r;

        # Enable QUIC and HTTP/3.
        listen 4433 quic reuseport;

        # Enable HTTP/2 (optional).
        #listen 4433 ssl http2;

        ssl_certificate      fullchain.pem;
        ssl_certificate_key  privkey.pem;

        # Enable all TLS versions (TLSv1.3 is required for QUIC).
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;

        # Request buffering in not currently supported for HTTP/3.
        proxy_request_buffering off;

        # Add Alt-Svc header to negotiate HTTP/3.
        add_header alt-svc 'h3-29=":4433"; ma=86400';_

The quiche-server and google chrome as follows:

_google-chrome --new-window -incognito --allow-file-access-from-files --no-sandbox --no-proxy-server --enable-quic --quic-version=h3-29 -origin-to-force-quic-on=vanvantong.tk:4433 --host-resolver-rules='MAP vanvantong.tk:4433 10.12.20.116:4434' https://vanvantong.tk:4433

RUST_LOG=trace ./quiche-server --listen 10.12.20.116:4434 --cert /home/vantong/Desktop/vanvantong.tk/fullchain.pem --key /home/vantong/Desktop/vanvantong.tk/privkey.pem --root /home/vantong/nginx-1.16.1/html_

The web server work well, but I do not know that it is httpv1, httpv2 or h3. Attachment is the screenshot.
https://drive.google.com/file/d/1-GQrAOMH-jhS_M_WCEoQnc6eXj0LaL1k/view?usp=sharing

**Comment by LPardue** [comment]
The screenshot shows that the `server` header is quiche, and since `quiche-server` only supports HTTP/3 that is the version used to retrieve resources in this case. In the Chrome devtools Network pane you can view the Protocol used to fetch each resource - to do that right click on the `Status` column, a dialog will appear and you can select `Protocol`. This will add a `Protocol` column listing e.g. `h3-29`

I'm not seeing any problem with quiche here, so I think we can close the issue.

**Comment by vanvantong** [comment]
Thank you very much.
