### ISSUE TITLE
Build Failed - any hint  ?

### ISSUE THREAD

**Issue by iDustbin** [cloudflare/quiche#834]
error: attributes are not yet allowed on `if` expressions
    **--> src/lib.rs:2704:13
     |
2704 |             #[allow(unused_assignments)]
     |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^**

error: aborting due to previous error

**error: could not compile `quiche`.**

Caused by:
  process didn't exit successfully: `rustc --crate-name quiche --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --crate-type staticlib --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C debuginfo=2 --cfg 'feature="ffi"' -C metadata=c80c42e2ecae377f --out-dir /tmp/quiche/target/release/deps -L dependency=/tmp/quiche/target/release/deps --extern lazy_static=/tmp/quiche/target/release/deps/liblazy_static-f8727ef3a2428c1c.rlib --extern libc=/tmp/quiche/target/release/deps/liblibc-6b21ffbe201c917f.rlib --extern libm=/tmp/quiche/target/release/deps/liblibm-7cd46e9c4b302f7d.rlib --extern log=/tmp/quiche/target/release/deps/liblog-2d3ebfedb40d9f2a.rlib --extern ring=/tmp/quiche/target/release/deps/libring-4105a4a42d798bb1.rlib -L native=/tmp/quiche/target/release/build/ring-ea833506051d5a57/out` (exit code: 1)
make[1]: *** [objs/Makefile:1361: ../quiche/target/release/libquiche.a] Error 101
make[1]: Leaving directory '/tmp/nginx-1.16.1'
make: *** [Makefile:8: build] Error 2

any idea ? 
rustc --version
rustc 1.41.1

is there any newer nginx version including http3/quiche available ?

**Comment by LPardue** [comment]
From the readme 

```
quiche requires Rust 1.47 or later to build. 
```

**Comment by iDustbin** [comment]
... i removed openssl totally. 
thats the reason why im not able to download rustup.sh... 
--insecure doesnt help.
Is there any bash script available which is able to deploy this future technology on my VPS ? 
is there any way to upgrade rust through an package manager like apt ?

**Comment by iDustbin** [comment]
no comment, thanks for your help
