### ISSUE TITLE
unknown_version test fails on Android

### ISSUE THREAD

**Issue by j-vanderstoep** [cloudflare/quiche#837]
I'm getting the following error when running the unknown_version test on Android.

[200/288] quiche_device_test_src_lib#tests::unknown_version: FAILED (118ms)

STACKTRACE:
---- tests::unknown_version stderr ----
thread 'main' panicked at 'assertion failed: `(left == right)`
left: `Err(TlsFail)`,
right: `Err(UnknownVersion)`', external/rust/crates/quiche/src/lib.rs:4833:9

Any idea why I'm seeing TlsFail instead of UnknownVersion?

My temporary workaround is to ignore the test, but I would like to figure out what's wrong: See: https://android-review.googlesource.com/c/platform/external/rust/crates/quiche/+/1523319/10/src/lib.rs#4825

**Comment by ghedo** [comment]
I think it might be because you are using a newer BoringSSL version, see https://github.com/cloudflare/quiche/pull/826/commits/ecfacccb15ed7f2083001482b7f7dfb5d366ac48#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R5239

**Comment by j-vanderstoep** [comment]
Thank you!
