### ISSUE TITLE
libquiche.a does not contain symbols in quiche.h

### ISSUE THREAD

**Issue by psionic12** [cloudflare/quiche#841]
I'm trying to build an libquiche.a for android, and followed the step in README, and it built successfully:
```
QITMAC000909deMac-mini quiche % cargo ndk -t armv7-linux-androideabi -p 21 -- build
[2021-02-05T13:09:42Z INFO  cargo_ndk::cli] Using NDK at path: /Users/liuyafei/Library/Android/sdk/ndk/21.1.6352462
[2021-02-05T13:09:42Z INFO  cargo_ndk::cli] NDK API level: 21
[2021-02-05T13:09:42Z INFO  cargo_ndk::cli] Building targets: armeabi-v7a
[2021-02-05T13:09:42Z INFO  cargo_ndk::cli] Building armeabi-v7a (armv7-linux-androideabi)
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
```

then I took `libquiche.a` in `quiche/target/armv7-linux-androideabi/debug` into my ndk project, but it said `rror: undefined reference to 'quiche_enable_debug_logging(void (*)(char const*, void*), void*)'`, I use `nm` to check the symbols in the lib, and it turns out no symbols are related to "logging":

```
QITMAC000909deMac-mini debug % nm libquiche.a |grep logging
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
no symbols
```

so I guess it's not the C/C++ mangling problem, but somehow that there are some symbols missing in libquiche.a which are defined in quiche.h

what did I do wrong?

**Comment by ghedo** [comment]
Can you please try adding `--features ffi` at the end of that `cargo ndk` command?

We need to update the documentation to mention this.

**Comment by psionic12** [comment]
Hi, I wrote the command like this:
`cargo ndk --feature ffi -t armv7-linux-androideabi -p 21 -- build`
and the error came out:
`ERROR cargo_ndk::cli] unrecognized option --feature`
I checked the help information, and it seems that there's no "feature" as an argument.
my cargo is cargo 1.49.0 (d00d64df9 2020-12-05)

**Comment by psionic12** [comment]
It works.
