### ISSUE TITLE
How does `flush_egress()` in example work?

### ISSUE THREAD

**Issue by psionic12** [cloudflare/quiche#846]
I'm a little confused of the functionality of `flush_egress()` in example/http3-client.c. According to the code, it will send a UDP package with max length, which data are from `out`. 

I checked the code `pub fn send(&mut self, out: &mut [u8]) -> Result<usize>` and it will discard this package because there is not enough space for the package (since it is MAX_DATAGRAM_SIZE), so what is the purpose of doing this?

**Comment by LPardue** [comment]
I don't understand the question sorry. `send()` writes a QUIC packet into `out` and returns the size of the QUIC packet. The actual size of the QUIC packet it dependent on a number of factors (including `quiche_config_set_max_send_udp_payload_size()` )

**Comment by psionic12** [comment]
Hi, I'm sorry I debugged the code again and my conclusion of "discard the package" is wrong. 

What I didn't figure out is that `out` is a local static variable, but it is not initialized, so 
1. What is the purpose to pack the `out` (which are random data if I'm right) to a QUIC packet and send it through UDP? 
2. And is this procedure a must? I'm porting Quiche to my android project and don't know if I should implement exactly the same logic.
3. Won't this cost extra traffic data to users? I checked that `flush_egress()` get called multiple times within a http3 transition.

**Comment by LPardue** [comment]
You have the objects inverted. Quiche buffers application data on streams, once the application is done buffering, it then repeatedly calls `send()` to get quiche to packetize the buffered data. Quiche writes the produces QUIC packet to the application-owned buffer `out`. This should be called repeatedly until quiche has no work to do.

**Comment by psionic12** [comment]
So do you mean even it is named as `quiche_conn_send(conn_io->conn, out, sizeof(out));`, it writes data from the stream (which is somewhere in the Quiche library) to the buffer `out`, then I use the UDP socket to send `out` to the peer, repeatedly until the stream is empty?

**Comment by LPardue** [comment]
More or less, the processing model is explained in the Rust API docs https://docs.quic.tech/quiche/struct.Connection.html#method.send which map very closely to the C API. But note that quiche takes responsibility for framing and packetization, so you shouldn't make assumptions about the contents of packets or the state of the QUIC connection.

**Comment by psionic12** [comment]
Thanks, I'll investigate the doc.
