### ISSUE TITLE
CMake Error: The source directory "/root/quiche/deps/boringssl" does not appear to contain CMakeLists.txt.

### ISSUE THREAD

**Issue by magnate3** [cloudflare/quiche#875]
root@ubuntu:~/nginx-1.16.1# make -j$(nproc)
make -f objs/Makefile
make[1]: Entering directory '/root/nginx-1.16.1'
mkdir -p ../quiche/deps/boringssl/build ../quiche/deps/boringssl/.openssl/lib ../quiche/deps/boringssl/.openssl/include/openssl \
&& cd ../quiche/deps/boringssl/build \
&& cmake -DCMAKE_C_FLAGS="" -DCMAKE_CXX_FLAGS="" .. \
&& make VERBOSE=1 \
&& cd .. \
&& cp -r src/include/openssl/*.h .openssl/include/openssl \
&& cp build/libssl.a build/libcrypto.a .openssl/lib
sed -e "s|%%PREFIX%%|/root/nginx-1.16.1|" \
        -e "s|%%PID_PATH%%|/root/nginx-1.16.1/logs/nginx.pid|" \
        -e "s|%%CONF_PATH%%|/root/nginx-1.16.1/conf/nginx.conf|" \
        -e "s|%%ERROR_LOG_PATH%%|/root/nginx-1.16.1/logs/error.log|" \
        < man/nginx.8 > objs/nginx.8
CMake Error: The source directory "/root/quiche/deps/boringssl" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
objs/Makefile:1349: recipe for target '../quiche/deps/boringssl/.openssl/include/openssl/ssl.h' failed
make[1]: *** [../quiche/deps/boringssl/.openssl/include/openssl/ssl.h] Error 1
make[1]: Leaving directory '/root/nginx-1.16.1'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by zarnovican** [comment]
This happened to me as well. You probably didn't clone the submodule(s).

**Comment by Mryan2005** [comment]
> This happened to me as well. You probably didn't clone the submodule(s).

You are right, I find that I forget clone the submodule(s) since I read your comment, Thanks for your comment, it help me a lot.
