### ISSUE TITLE
Is there a switch/parameter to change the congestion control algorithm while running server ?

### ISSUE THREAD

**Issue by abnv418** [cloudflare/quiche#876]
Can I switch the congestion control algorithm from Cubic to New Reno or vice versa. is there a parameter to do that . ?

By. default which congestion controller works  ?

**Comment by junhochoi** [comment]
Please refer to https://docs.quic.tech/quiche/#congestion-control
Default is CUBIC.

**Comment by abnv418** [comment]
When I set the new reno in  quiche-server.rs : - 

let mut config = quiche::Config::new(quiche::PROTOCOL_VERSION).unwrap();
                    config.set_cc_algorithm_name("reno").unwrap();

                #[allow(unused_mut)]
                let mut conn =
                    quiche::accept(&scid, odcid.as_ref(), &mut config).unwrap();

I get the following error: - 

[2021-03-19T13:27:26.596062000Z ERROR quiche_server] 8f60934bf6651143ebe630ce6e137d5e85eb23a5 recv failed: TlsFail

There is no error when I dont change the congestion control. Am i setting things in wrong place or I need to take care of something else.

**Comment by abnv418** [comment]
I think it works by just setting this with other parameters : - config.set_cc_algorithm_name("reno").unwrap();

Is there a way to check which congestion control is working reno or cubic ? after we make the change.

**Comment by junhochoi** [comment]
Yes quiche-server (and quiche-client) supports the command line option to specify CC to use. https://github.com/cloudflare/quiche/blob/master/tools/apps/src/bin/quiche-server.rs#L120

Currently there is no API to check current CC of the connection. But if you don't get any errors on calling the API, the subsequent connection will use it.

**Comment by abnv418** [comment]
ok Thanks for your reply. So just a further follow up if i want nginx with http3 path to use the reno Congestion control then I believe that we can set the config.set_cc_algorithm_name("reno").unwrap();

and build the nginx with QUICHE and the default Congestion control should be reno in that case.

**Comment by junhochoi** [comment]
There is also C API provided: https://github.com/cloudflare/quiche/blob/master/include/quiche.h#L188

If you want to try in nginx, call the API where we set other config API, such as https://github.com/cloudflare/quiche/blob/master/extras/nginx/nginx-1.16.patch#L4175

**Comment by junhochoi** [comment]
Closing this, let met know if you have further question!

**Comment by abnv418** [comment]
Thanks I used the API. It seems to be working by setting the configuration to use reno cc algo. However I was not able to verify this. Do you if there is a mechanism to get the quiche logs coming into the nginx logs. ?

For Example: - 

If I put a print statement in the rust code in quiche . How to get that output on nginx error log or on terminal while running the server. The main question is can quiche send its logs to nginx output ?
