### ISSUE TITLE
no response from QUIC 

### ISSUE THREAD

**Issue by Adeelasd** [cloudflare/quiche#883]
I am setting up http3 on my AWS instance http2 seems to work fine but http3 doesn't work at all. and when I run 
RUST_LOG=trace cargo run --example http3-client 
it gives an empty response. any ideas about what I am doing wrong. Thanks.

nginx -V
nginx version: nginx/1.19.8
built with OpenSSL 1.1.1 (compatible; BoringSSL) (running with BoringSSL)
TLS SNI support enabled
configure arguments: --prefix=/etc/nginx --sbin-path=/usr/sbin/nginx --add-module=/home/ubuntu/nginx-1.19.8/debian/modules/ngx_pagespeed --add-module=/home/ubuntu/nginx-1.19.8/debian/modules/ngx_brotli --modules-path=/usr/lib/nginx/modules --conf-path=/etc/nginx/nginx.conf --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log --pid-path=/var/run/nginx.pid --lock-path=/var/run/nginx.lock --http-client-body-temp-path=/var/cache/nginx/client_temp --http-proxy-temp-path=/var/cache/nginx/proxy_temp --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp --http-scgi-temp-path=/var/cache/nginx/scgi_temp --user=nginx --group=nginx --with-compat --with-file-aio --with-threads --with-http_addition_module --with-http_auth_request_module --with-http_dav_module --with-http_flv_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_mp4_module --with-http_random_index_module --with-http_realip_module --with-http_secure_link_module --with-http_slice_module --with-http_ssl_module --with-http_stub_status_module --with-http_sub_module --with-http_v2_module --with-mail --with-mail_ssl_module --with-stream --with-stream_realip_module --with-stream_ssl_module --with-stream_ssl_preread_module --with-http_v3_module --with-http_quic_module --with-stream_quic_module --with-cc-opt='-I/home/ubuntu/boringssl/include -g -O2 -fdebug-prefix-map=/home/ubuntu/nginx-1.19.8=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' --with-ld-opt='-L/home/ubuntu/boringssl/build/ssl -L/home/ubuntu/boringssl/build/crypto -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie'

--- My config file 

server{
    index index.html index.nginx-debian.html;
    server_name ;
    root /var/www/somedir;
    listen 443 quic reuseport;
    #listen 8443 ssl;
    listen 443 ssl http2;
    proxy_request_buffering off;

    http3_max_table_capacity 50;
    http3_max_blocked_streams 30;
    http3_max_concurrent_pushes 30;
    http3_push 10;
    http3_push_preload on;
    ssl_certificate /etc/letsencrypt/live/techtacion.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/techtacion.com/privkey.pem; # managed by Certbot 
       # Enable all TLS versions (TLSv1.3 is required for QUIC).
        ssl_protocols TLSv1.3;
        
        # Add Alt-Svc header to negotiate HTTP/3.
        add_header alt-svc '$http3=":443"; ma=86400';
     
}

**Comment by LPardue** [comment]
Seems like you are running the nginx official module, not the quiche based one. So we can't really help.
