### ISSUE TITLE
Support Copa congestion control

### ISSUE THREAD

**Issue by rafibaum** [cloudflare/quiche#892]
[Copa](https://web.mit.edu/copa/) is a novel congestion control algorithm which has seen some usage, including [at Facebook](https://engineering.fb.com/2019/11/17/video-engineering/copa/). It's generally more suited to use-cases which are more latency dependent rather than throughput, since its target bitrate estimation algorithm has realistic outputs in the <100 Mb/sec range. I've created a draft of what a Copa implementation could look like over on [this branch](https://github.com/rafibaum/quiche/tree/copa) based on the work going on at #770. That being said, it's a bit rough around the edges and is based on my limited understanding both of the Copa algorithm and how congestion control works in quiche. I'm just documenting it here for anyone else who would wish to implement Copa. Also of interest may be [Facebook's QUIC implementation of Copa](https://github.com/facebookincubator/mvfst/blob/master/quic/congestion_control/Copa.cpp).

**Comment by LPardue** [comment]
Thanks for letting us know @rafibaum, this looks like some interesting work. I guess the most interesting aspect would be on how this works in practice, have you got any results you can share?

**Comment by rafibaum** [comment]
This implementation is part of some research I'm working on so I do plan on putting it through the gauntlet during evaluation. I'm focusing more on bulk file transfer workloads where Copa isn't expected to perform well since it's designed for more "bursty" workloads like web browsing or video streaming but it should still be enough to prove that the implementation is functional under a realistic scenario. I'll share my data once it's finalised (probably around June).

If you meant how Copa performs more generally, then the Facebook blog post and paper I linked in the original comment are the best sources for that. Generally Copa exhibits similar throughput to BBR (in workloads like video streaming where the bitrate is application-limited under 50Mbit/sec) while inducing less latency on high-RTT connections. Additionally, Copa is entirely insensitive to packet loss so it would outperform CUBIC over inherently lossy connections. The paper also alleges that it can compete fairly with CUBIC but Facebook was unable to verify that in their blog post.

**Comment by LPardue** [comment]
> This implementation is part of some research I'm working on so I do plan on putting it through the gauntlet during evaluation. I'm focusing more on bulk file transfer workloads where Copa isn't expected to perform well since it's designed for more "bursty" workloads like web browsing or video streaming but it should still be enough to prove that the implementation is functional under a realistic scenario. I'll share my data once it's finalised (probably around June).

Sounds great! Keep us posted, we'd be interesting in hearing about your research as you progress. If you have questions that you'd prefer to ask in a less public forum (before you publish) we can take it to email.

**Comment by LPardue** [comment]
It looks like the GH repo was deleted. @rafibaum shall we close this issue? The project is open to enhancement proposals but there doesn't seem anything concrete here any more.

**Comment by LPardue** [comment]
Closing as inactive but feel free to reopen .
