### ISSUE TITLE
quiche example doesn't work with quinn example and vice versa

### ISSUE THREAD

**Issue by est31** [cloudflare/quiche#9]
This works great in quiche:

```bash
cargo run --example server -- --name localhost --root ./
cargo run --example client -- --no-verify https://localhost:4433/Cargo.toml
```

This works great in quinn:

```bash
cargo run --example server ./
cargo run --example client https://localhost:4433/Cargo.toml
```

But trying to use the quinn client example to talk to the quiche server yields in a timeout from the quinn client, and trying to use the quiche client with the quinn server gives you a "Connection refused" error.
The two clients expose the same behaviour as if the server wasn't present *at all*.

cc @ralith @djc

**Comment by Ralith** [comment]
We get further than that in mutual interop tests, so I'm guessing it's a configuration issue. Perhaps quiche listens on a different port by default and ignores the port supplied in the URL?
