### ISSUE TITLE
How to realize the short link 0-rtt without exiting the client?

### ISSUE THREAD

**Issue by muyiwq** [cloudflare/quiche#922]
Hello, I want to realize many scenarios where clients send short links. How do I realize 0-rtt sending from clients? There is no version negotiation and retry. How to use version 29 directly instead of requiring version negotiation? Keep the client as a process without exiting, use the same config, it is not the first time to connect, why the socket is not 0-rtt? What needs to be configured? How do I need to modify the example of c? Give some suggestions, thank you in advance. . .

**Comment by muyiwq** [comment]
Both the client and the server correctly set ietf 29 at the same time. It has been solved to reduce the sending of version negotiation packets. How to reduce the sending of stateless retry packets and how to achieve 0rtt?

**Comment by junhochoi** [comment]
If you are using quiche-client and quiche-server,
- add `--no-retry` on quiche-server to disable stateless retry
- add `--wire-version ff00001d` to avoid version negotiation

to enable 0-rtt, server and client need `--early-data`. Also for client you need to add `--session-file <file>` to store a session ticket.

**Comment by muyiwq** [comment]
Thank you very much for your suggestions. But the client.c and server.c command line parameters that support c --no-retry --early-data --session-file --wire-version do not take effect when you test it. The version negotiation can be set in the code. Solution, quiche.h does not provide a function to remove retry. Early_data can be set in the client and server code. How to make --session-file take effect in the client c code? Can the specified 0-rtt file have an empty file name at random?

**Comment by junhochoi** [comment]
I think retry logic is provided in the C example. For session ticket, C API added recently at 0a08fd7.
