### ISSUE TITLE
Issue compiling with nginx 1.20.0

### ISSUE THREAD

**Issue by gaby64** [cloudflare/quiche#924]
I tried stable, beta and nightly rust

```
error[E0599]: no method named `fill` found for slice `[u8]` in the current scope
    --> src/lib.rs:2318:39
     |
2318 |             out[done..done + pad_len].fill(0);
     |                                       ^^^^ method not found in `[u8]`

error: aborting due to previous error
```

**Comment by gaby64** [comment]
> Please upgrade your rust compiler to latest stable.

I tried stable, beta and nightly

**Comment by junhochoi** [comment]
Can you check your rustc version >= 1.50 by `rustc --version`? `fill()` method is introduced in 1.50 https://doc.rust-lang.org/std/primitive.slice.html#method.fill

**Comment by junhochoi** [comment]
Thanks. Using Ci we are always testing the build with rust stable/nightly and I am also able to build without issue using the following rustc. Something may be missing but I have no idea how you get this error with rust 1.52.
```$ rustc --version
rustc 1.52.0 (88f19c6da 2021-05-03)```

**Comment by gaby64** [comment]
I did a reboot with no difference, no apt rust package

**Comment by manthanrtilva** [comment]
@gaby64 Could you run `rustc --version` command on environment you facing above problem? 

And also try to compile below sample code on same with `rustc /path/to/sample.rs`

	//sample.rs

	fn main() {
		let mut out = [0;512];
		out[0..512].fill(0);
	}

**Comment by gaby64** [comment]
I found the issue, I had an old version on the root user and I run my build script with sudo
On May 11, 2021, at 10:42 p.m., manthanrtilva ***@***.******@***.***>> wrote:

@gaby64<https://github.com/gaby64> Could you run rustc --version command on environment you facing above problem?

And also try to compile below sample code on same with rustc /path/to/sample.rs

//sample.rs

fn main() {
 let mut out = [0;512];
 out[0..512].fill(0);
}

**Comment by junhochoi** [comment]
Thanks! Great to see you have found the issue. I'll close this ticket.
