### ISSUE TITLE
stream_send does not return Done when no bytes are written

### ISSUE THREAD

**Issue by rafibaum** [cloudflare/quiche#928]
I've run into some instances where `stream_send` will return `Ok(0)` rather then `Err(quiche::Error::Done)`, and while this may be intentional behaviour I wanted to check since it seems inconsistent with how other quiche functions work.

Specifically, this issue occurs when `self.tx_cap` is equal to zero (in my use case this is because the congestion controller has set a small congestion window). `stream_send` will then call `stream.send.write(buf, fin)` with a zero-length buffer, which returns `Ok(0)` and then this result gets passed back to the user. To me, it seems like `stream_send` should return `Done` in this case since there's no further work to be done. If this is intentional, I'd love to know what the semantic differences are in quiche between `Ok(0)` and `Done` and maybe that should get documented since it might confuse others as well.

**Comment by LPardue** [comment]
Thanks for the report, this does seem to be inconsistent with the function description, which says 

```
    /// On success the number of bytes written is returned, or [`Done`] if no
    /// data was written (e.g. because the stream has no capacity).
    ```

**Comment by normanmaurer** [comment]
Fixed by https://github.com/cloudflare/quiche/pull/970
