### ISSUE TITLE
cross posting, tunneling TURN thru other protocols, in the browser

### ISSUE THREAD

**Issue by unicomp21** [cloudflare/quiche#945]
linking to here in the hope there might be some interest

https://github.com/w3c/webtransport/issues/270

**Comment by LPardue** [comment]
This doesn't have much to do with quiche, closing.

**Comment by unicomp21** [comment]
@LPardue Correct, but it could lead to revenue opportunities for cloudflare.  webrtc traffic is a big deal these days.  Perhaps a product owner would be interested?

**Comment by LPardue** [comment]
Github isn't the appropriate venue to discuss this. Our team participate in standards bodies such as the IETF and W3C, which is the best place to develop new ideas that require technological changes across industry. We've seen your threads in those venues. 

There's lots of options for carrying TURN traffic over a QUIC substrate - native application mapping, over HTTP/3, over MASQUE, over WebTransport. Quiche is a low layer library for the QUIC protocol, it will likely support any type of substrate that people wish to use. But unless there is a concrete issues with, or suggestion for, the library, then creating issues here fragments discussion.

My advice would be to try and sketch out what substrate you'd use for TURN and to test out the concept. If you find implementation issues using quiche to build the concept, that is entirely appropriate to bring to this GitHub repo.
