### ISSUE TITLE
Make new release compatible with curl 7.77.0

### ISSUE THREAD

**Issue by candrews** [cloudflare/quiche#946]
curl 7.77.0 has been released.

curl uses a change that's in quiche master, but isn't it yet in a release: https://github.com/curl/curl/commit/424aa64d54fd2c4baf69aa0c09bf5db347ff59f0

Can you please make a new release of quiche which is compatible with curl 7.77.0?

Thank you!

Originally reported at https://bugs.gentoo.org/792234

**Comment by ghedo** [comment]
Created https://github.com/cloudflare/quiche/releases/tag/0.9.0 just now.
