### ISSUE TITLE
Update Network Path Awareness to reflect macOS

### ISSUE THREAD

**Issue by DanielRussell** [cloudflare/quiche#952]
Part of the changeset [Network Path Awareness](https://github.com/cloudflare/quiche/commit/6d070ed8694216806f3ce689d71ceb7ad76d425e) by @ghedo updates all the clients, examples, and documentation from `socket.send()` to `socket.send_to()`.

On [macOS](https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/send.2.html), a call to `sendto(2)` with an address when the socket is already connected will result in an `EISCONN`, and therefore a Rust panic with a "Socket is already connected" error.  Note that on Linux, it appears that if a socket is already connected, `sendto()` will happily ignore any provided address, so this is likely a macOS-only issue.

Trying to run the example from the "Getting Started" section of the README:

```
$ system_profiler SPSoftwareDataType | grep Version
      System Version: macOS 11.4 (20F71)
      Kernel Version: Darwin 20.5.0
$ git rev-parse --short head
56edda7
$ rustc --version
rustc 1.52.1 (9bc8c42bb 2021-05-09)
$ cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://127.0.0.1:4433/
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `tools/apps/target/debug/quiche-client 'https://127.0.0.1:4433/'`
thread 'main' panicked at 'send() failed: Os { code: 56, kind: Other, message: "Socket is already connected" }', src/bin/quiche-client.rs:48:39
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The previous commit works fine (I made an `index.html` that contains "hello, world"):

```
$ git checkout 6d070ed8694216806f3ce689d71ceb7ad76d425e^
Note: switching to '6d070ed8694216806f3ce689d71ceb7ad76d425e^'.
...
HEAD is now at cbce40c ci: enable examples and all features for all test builds
$ git rev-parse --short head
cbce40c
$ cargo run --manifest-path=tools/apps/Cargo.toml --bin quiche-client -- https://127.0.0.1:4433/ --no-verify
    Finished dev [unoptimized + debuginfo] target(s) in 0.13s
     Running `tools/apps/target/debug/quiche-client 'https://127.0.0.1:4433/' --no-verify`
hello, world
```

Note that the same command for current HEAD (56edda7) runs fine on  on Debian, which makes me think this is a platform-specific concern.

I don't know what a good fix for this might be.

**Comment by LPardue** [comment]
Thanks for the report, does https://github.com/cloudflare/quiche/pull/947 fix it for you?

**Comment by DanielRussell** [comment]
It sure does (macOS and Debian).  Thanks for the quick pointer, sorry I missed it myself!

**Comment by LPardue** [comment]
No problem, thanks for reaching out and confirming. We will get this landedsoon.
