### ISSUE TITLE
Does `config` have to be mutable?

### ISSUE THREAD

**Issue by keepsimple1** [cloudflare/quiche#964]
https://github.com/cloudflare/quiche/blob/7eb57c4fc608932acc76c3ee2759c2e41e51d566/src/lib.rs#L1323-L1325

In the above function, `config` is &mut.  But I cannot find where it was mutated. Did I miss it, or is it for future considerations? I'm asking because the[ doc](https://docs.quic.tech/quiche/struct.Config.html) mentioning config shared between connections, but no further details. What's the recommended way to share the config between connections?

**Comment by ghedo** [comment]
See this answer to a similar question from a while ago https://github.com/cloudflare/quiche/issues/651#issuecomment-704389644.
