### ISSUE TITLE
Packets with packet numbers >= 2^32?

### ISSUE THREAD

**Issue by vukasink** [cloudflare/quiche#971]
Hi all,
First of all, sorry if I am misunderstanding the code and missing some obvious (not to me though) point.
I am wondering about two lines of code (2554, 2555) regarding packet numbers in lib.rs, they are part of function ``fn send_single(...``:

```rust
        let pn = self.pkt_num_spaces[epoch].next_pkt_num;
        let pn_len = packet::pkt_num_len(pn)?;
```
pkt_num_len function in packet.rs looks like the following:
```rust
pub fn pkt_num_len(pn: u64) -> Result<usize> {
    let len = if pn < u64::from(std::u8::MAX) {
        1
    } else if pn < u64::from(std::u16::MAX) {
        2
    } else if pn < u64::from(std::u32::MAX) {
        4
    } else {
        return Err(Error::InvalidPacket);
    };

    Ok(len)
}
```
It is my understanding that if pn is greater or equal than 2^32, the function will invoke an error. If that indeed is the case, then the packets with packet numbers greater or equal than 2^32 will not be processed/sent at all? But how is that possible if QUIC allows packet numbers up to 2^62 - 1.

Thanks,
Vukasin

**Comment by ghedo** [comment]
So, packet numbers can reach up to 2^62 - 1, but they are encoded in up to 4 bytes on the wire, so the numbers need to be truncated. But while quiche supports _decoding_ truncated packet numbers, it does not yet have support for encoding them. This is something we should definitely fix at some point, just haven't gotten to it yet.

**Comment by vukasink** [comment]
Thanks for clarifying it.
