### ISSUE TITLE
Cant use server initiated uni streams

### ISSUE THREAD

**Issue by serzhiio** [cloudflare/quiche#990]
Any data that i try to send via server initiated UNI stream (from server to client) cannot be sent.
stream_send() fn returns 0 bytes, stream id used is 3.
When i use BIDI streams everything is fine.

**Comment by ghedo** [comment]
One possibility is that the client doesn' offer enough stream and/or flow control credits for unidirectional streams. What is the configuration used by the client?

**Comment by serzhiio** [comment]
```    config.set_max_idle_timeout(5000);
    config.set_max_recv_udp_payload_size(1350);
    config.set_max_send_udp_payload_size(1350);
    config.set_initial_max_data(10_000_000);
    config.set_initial_max_stream_data_bidi_local(1_000_000);
    config.set_initial_max_stream_data_bidi_remote(1_000_000);
    config.set_initial_max_streams_bidi(100);
    config.set_initial_max_streams_uni(100);
    config.set_disable_active_migration(true);```

**Comment by serzhiio** [comment]
Arghhh... i got it, i've lost this option:
`config.set_initial_max_stream_data_uni(1_000_000);`
